(() => {
  'use strict';

  const cfg = window.APP_CONFIG || {};
  const root = document.getElementById('app');
  const hasSupabase = !!(cfg.supabaseUrl && cfg.supabaseAnonKey && window.supabase);
  const supabase = hasSupabase ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;

  const CATS = {
    AS: { label: 'Association Sportive', css: 'as', logo: 'assets/logo-as.png' },
    Football: { label: 'Football', css: 'football', logo: 'assets/logo-football.png' },
    Escalade: { label: 'Escalade', css: 'escalade', logo: 'assets/logo-escalade.png' },
    Gymnastique: { label: 'Gymnastique', css: 'gymnastique', logo: 'assets/logo-gymnastique.png' },
  };

  const ROLE_LABELS = {
    public: 'Élève / Parent',
    educator_football: 'Éducateur football',
    educator_escalade: 'Éducateur escalade',
    educator_gymnastique: 'Éducateur gymnastique',
    teacher_as: 'Enseignant AS',
    admin: 'Administrateur'
  };

  const seed = {
    events: [
      {id:'e1',title:'Entraînement AS multisports',category:'AS',date:'2026-09-09',time:'13:30',place:'Gymnase du Bon Sauveur',description:'Reprise des activités du mercredi.',audience:'Tous',level:'Tous'},
      {id:'e2',title:'Entraînement section football',category:'Football',date:'2026-09-10',time:'15:30',place:'Stade',description:'Séance technique et opposition.',audience:'Élèves',level:'Tous'},
      {id:'e3',title:'Option escalade',category:'Escalade',date:'2026-09-10',time:'15:30',place:'Salle d’escalade',description:'Séance de rentrée et constitution des cordées.',audience:'Élèves',level:'Tous'},
      {id:'e4',title:'Sport-études gymnastique',category:'Gymnastique',date:'2026-09-08',time:'14:30',place:'Saint-Loise Gymnastique',description:'Entraînement sport-études.',audience:'Élèves',level:'Tous'},
      {id:'e5',title:'Compétition UGSEL — Football',category:'Football',date:'2026-09-23',time:'13:00',place:'Saint-Lô',description:'Rencontre de secteur.',audience:'Élèves',level:'Collège'}
    ],
    infos: [
      {id:'i1',title:'Inscriptions AS ouvertes',text:'L’adhésion annuelle permet de participer librement aux activités proposées le midi et le mercredi.',category:'AS',importance:'IMPORTANT',publishedAt:'2026-09-05',expiresAt:'2026-09-30'},
      {id:'i2',title:'Horaires de rentrée',text:'Pensez à consulter les horaires propres à chaque dispositif sportif avant la première séance.',category:'AS',importance:'NORMAL',publishedAt:'2026-09-05',expiresAt:'2026-09-20'}
    ],
    documents: [
      {id:'d1',title:'Règlement de l’Association Sportive',category:'AS',description:'Règles de fonctionnement et informations utiles.',date:'2026-09-01',url:'#',featured:true},
      {id:'d2',title:'Horaires section football',category:'Football',description:'Horaires hebdomadaires de la section.',date:'2026-09-01',url:'#',featured:true},
      {id:'d3',title:'Horaires option escalade',category:'Escalade',description:'Organisation et horaires de l’option.',date:'2026-09-01',url:'#',featured:false},
      {id:'d4',title:'Horaires sport-études gymnastique',category:'Gymnastique',description:'Organisation des prises en charge et retours.',date:'2026-09-01',url:'#',featured:false}
    ],
    photos: [],
    products: [
      {id:'p1',name:'Sweat officiel Bon Sauveur Sport',description:'Sweat aux couleurs du Bon Sauveur Sport.',price:35,sizes:['XS','S','M','L','XL'],deadline:'2026-10-05',category:'AS'},
      {id:'p2',name:'T-shirt Association Sportive',description:'T-shirt technique pour les entraînements et événements.',price:15,sizes:['XS','S','M','L','XL'],deadline:'2026-10-05',category:'AS'}
    ],
    orders: [],
    students: [
      {id:'s1',lastName:'DUPONT',firstName:'Emma',className:'6e Avignon',specialty:'Gymnastique'},
      {id:'s2',lastName:'MARTIN',firstName:'Léo',className:'5e Auriol',specialty:'Football'},
      {id:'s3',lastName:'BERNARD',firstName:'Inès',className:'4e More',specialty:'Escalade'},
      {id:'s4',lastName:'ROBERT',firstName:'Noah',className:'3e Gaudí',specialty:'Gymnastique'},
      {id:'s5',lastName:'THOMAS',firstName:'Jade',className:'5e Coleman',specialty:'Football'},
      {id:'s6',lastName:'PETIT',firstName:'Louis',className:'4e Delaunay',specialty:'Escalade'}
    ],
    users: [
      {id:'u-foot',displayName:'Éducateur football',email:'football@demo.local',role:'educator_football'},
      {id:'u-esc',displayName:'Éducateur escalade',email:'escalade@demo.local',role:'educator_escalade'},
      {id:'u-gym',displayName:'Éducateur gymnastique',email:'gymnastique@demo.local',role:'educator_gymnastique'},
      {id:'u-teacher',displayName:'Enseignant AS',email:'enseignant@demo.local',role:'teacher_as'},
      {id:'u-admin',displayName:'Administrateur',email:'admin@demo.local',role:'admin'}
    ],
    appreciations: [
      {id:'a1',studentId:'s2',educatorId:'u-foot',term:1,text:'Très bonne implication dans les séances.',status:'validated'},
      {id:'a2',studentId:'s5',educatorId:'u-foot',term:1,text:'',status:'todo'},
      {id:'a3',studentId:'s3',educatorId:'u-esc',term:1,text:'Participation sérieuse et régulière.',status:'draft'}
    ],
    licenses: [
      {id:'l1',studentId:'s1',activity:'Gymnastique',status:'Active',date:'2026-09-02'},
      {id:'l2',studentId:'s2',activity:'Football',status:'Active',date:'2026-09-03'},
      {id:'l3',studentId:'s3',activity:'Escalade',status:'Active',date:'2026-09-04'},
      {id:'l4',studentId:'s4',activity:'Gymnastique',status:'Active',date:'2026-09-04'},
      {id:'l5',studentId:'s5',activity:'Football',status:'Active',date:'2026-09-04'},
      {id:'l6',studentId:'s6',activity:'Escalade',status:'En attente',date:'2026-09-04'}
    ],
    reports: [
      {id:'b1',date:'2026-09-02',activity:'AS multisports',participants:34,levels:'Collège',result:'',comment:'Belle reprise, forte participation.'}
    ],
    convocations: [
      {id:'c1',title:'UGSEL Football — secteur',category:'Football',date:'2026-09-23',departure:'12:45',returnTime:'17:30',place:'Saint-Lô',meetingPoint:'Porche du Bon Sauveur',equipment:'Tenue de sport, gourde',extraInfo:'Prévoir le repas si nécessaire.',studentIds:['s2','s5'],status:'published'}
    ]
  };

  const state = {
    route: 'home', adminTab: 'dashboard', categoryFilter: 'Tous', search: '',
    dark: localStorage.getItem('bs-dark') === '1', user: null, role: 'public',
    data: loadLocal(), online: navigator.onLine, authReady: false, term: 1
  };
  if (state.dark) document.body.classList.add('dark');

  function loadLocal(){
    try { const raw=localStorage.getItem('bs-app-data-v2'); return raw?migrateData(JSON.parse(raw)):structuredClone(seed); }
    catch { return structuredClone(seed); }
  }
  function migrateData(data){
    const base=structuredClone(seed); for(const key of Object.keys(base)) if(!Array.isArray(data[key])) data[key]=base[key];
    data.documents=data.documents.map(d=>({...d,featured:!!d.featured})); data.photos=data.photos||[];
    data.convocations=data.convocations.map(c=>({...c,meetingPoint:c.meetingPoint||'',extraInfo:c.extraInfo||'',studentIds:Array.isArray(c.studentIds)?c.studentIds:[]}));
    data.users=data.users||base.users; return data;
  }
  function saveLocal(){ if(!hasSupabase||cfg.demoMode)localStorage.setItem('bs-app-data-v2',JSON.stringify(state.data)); }
  function uid(prefix='x'){return prefix+Math.random().toString(36).slice(2,10)}
  function esc(v=''){return String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]))}
  function fmtDate(d){if(!d)return'';return new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
  function fmtLongDate(d){if(!d)return'';return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
  function dateParts(d){const x=new Date(d+'T12:00:00');return{day:x.getDate(),month:x.toLocaleDateString('fr-FR',{month:'short'}).replace('.','')}}
  function categoryBadge(cat){const c=CATS[cat]||CATS.AS;return`<span class="badge ${c.css}">${esc(c.label)}</span>`}
  function roleLabel(role=state.role){return ROLE_LABELS[role]||'Utilisateur'}
  function isEducator(role=state.role){return String(role).startsWith('educator_')}
  function isTeacher(role=state.role){return role==='teacher_as'||role==='admin'}
  function isAdmin(role=state.role){return role==='admin'}
  function specialtyForRole(role=state.role){return role==='educator_football'?'Football':role==='educator_escalade'?'Escalade':role==='educator_gymnastique'?'Gymnastique':null}
  function visibleByCategory(item){return state.categoryFilter==='Tous'||item.category===state.categoryFilter}
  function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
  function safeUrl(url){return /^https?:\/\//i.test(String(url||''))?String(url):''}
  function today(){return new Date().toISOString().slice(0,10)}

  function currentWeekBounds(){
    const now=new Date();now.setHours(12,0,0,0);const day=(now.getDay()+6)%7;const start=new Date(now);start.setDate(now.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);const iso=d=>d.toISOString().slice(0,10);return{start:iso(start),end:iso(end)};
  }

  async function initAuth(){
    if(hasSupabase&&!cfg.demoMode){
      const {data:{session}}=await supabase.auth.getSession(); if(session?.user)await hydrateUser(session.user);else await loadPublicData();
      supabase.auth.onAuthStateChange(async(event,session)=>{if(session?.user)await hydrateUser(session.user);else{state.user=null;state.role='public';await loadPublicData()}state.authReady=true;render();if(event==='PASSWORD_RECOVERY')setTimeout(openNewPasswordModal,120)});
    }
    state.authReady=true;render();
  }
  async function loadPublicData(){
    if(!hasSupabase||cfg.demoMode)return; const map={events:'events',infos:'announcements',documents:'documents',products:'products',photos:'photos'};
    for(const[key,table]of Object.entries(map)){const{data,error}=await supabase.from(table).select('*');if(!error&&Array.isArray(data))state.data[key]=normalizeRemote(data)}
  }
  async function hydrateUser(authUser){
    try{const{data:profile,error}=await supabase.from('profiles').select('*').eq('id',authUser.id).single();if(error)throw error;state.user={id:authUser.id,name:profile.display_name||authUser.email,email:profile.email||authUser.email};state.role=profile.role||'public';await loadRemoteData()}
    catch(e){console.error(e);state.user={id:authUser.id,name:authUser.email,email:authUser.email};state.role='public';await loadPublicData()}
  }
  async function loadRemoteData(){
    if(!hasSupabase||cfg.demoMode)return;await loadPublicData();const map={students:'students',appreciations:'appreciations',licenses:'licenses',reports:'as_reports',convocations:'convocations',orders:'orders'};
    for(const[key,table]of Object.entries(map)){const{data,error}=await supabase.from(table).select('*');if(!error&&Array.isArray(data))state.data[key]=normalizeRemote(data)}
    if(isAdmin()){const{data,error}=await supabase.from('profiles').select('*').order('display_name');if(!error&&Array.isArray(data))state.data.users=normalizeRemote(data)}
    if(isTeacher()){const{data:links,error}=await supabase.from('convocation_students').select('*');if(!error&&Array.isArray(links)){const normalized=normalizeRemote(links);state.data.convocations=state.data.convocations.map(c=>({...c,studentIds:normalized.filter(x=>x.convocationId===c.id).map(x=>x.studentId)}))}}
  }
  function normalizeRemote(rows){const snakeToCamel=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]));return rows.map(snakeToCamel)}
  function camelToSnake(o){return Object.fromEntries(Object.entries(o).map(([k,v])=>[k.replace(/[A-Z]/g,m=>'_'+m.toLowerCase()),v]))}
  function initials(){const n=state.user?.name||roleLabel();return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}

  function layout(content){
    const nav=[['home','⌂','Accueil'],['calendar','▣','Calendrier'],['documents','▤','Documents'],['shop','◫','Boutique'],['more','•••','Plus']]; const profileText=state.user?roleLabel():(cfg.demoMode?roleLabel():'Connexion');
    return`<div class="app-shell"><header class="topbar"><div class="brand" onclick="app.go('home')"><img src="assets/logo-as.png" alt="Logo Association Sportive"><div><div class="brand-title">BON SAUVEUR SPORT</div><div class="brand-sub">Saint-Lô · Association Sportive</div></div></div><div class="top-actions"><button class="icon-btn" onclick="app.toggleTheme()" aria-label="Changer le thème">${state.dark?'☀':'☾'}</button><button class="profile-btn" onclick="app.openProfile()"><span class="avatar">${state.user||cfg.demoMode?initials():'↗'}</span><span class="profile-name">${esc(profileText)}</span></button></div></header><main>${content}</main><nav class="bottom-nav" aria-label="Navigation principale">${nav.map(([r,ico,label])=>`<button class="nav-item ${state.route===r?'active':''}" onclick="app.go('${r}')"><span class="nav-ico">${ico}</span><span>${label}</span></button>`).join('')}</nav></div>`;
  }
  function render(){
    if(!state.authReady){root.innerHTML='<div class="login-wrap"><div class="card">Chargement…</div></div>';return}let page='';
    if(state.route==='home')page=homePage();if(state.route==='calendar')page=calendarPage();if(state.route==='documents')page=documentsPage();if(state.route==='shop')page=shopPage();if(state.route==='more')page=morePage();if(state.route==='convocations')page=convocationsPage();if(state.route==='appreciations')page=appreciationsPage();if(state.route==='admin')page=adminPage();if(state.route==='licenses')page=licensesPage();if(state.route==='reports')page=reportsPage();root.innerHTML=layout(page);
  }

  function homePage(){
    const bounds=currentWeekBounds();const upcoming=[...state.data.events].filter(e=>e.date>=today()).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||'')));let week=upcoming.filter(e=>e.date>=bounds.start&&e.date<=bounds.end);if(!week.length)week=upcoming.slice(0,5);const featured=state.data.documents.filter(d=>d.featured).slice(0,3);const docs=featured.length?featured:state.data.documents.slice(0,3);const urgent=state.data.infos.find(i=>i.importance==='URGENT');
    return`<div class="container home-container"><section class="hero"><div class="hero-row"><div><div class="kicker hero-kicker">SAINT-LÔ · ASSOCIATION SPORTIVE</div><h1>L’Association Sportive<br>du Bon Sauveur</h1><p>Compétitions, entraînements, convocations et informations : retrouvez ici toute l’actualité sportive du Bon Sauveur.</p></div><div class="hero-logo-stack">${Object.values(CATS).map(c=>`<div class="hero-logo"><img src="${c.logo}" alt="${esc(c.label)}"></div>`).join('')}</div></div></section>${urgent?`<div class="urgent-strip"><span class="badge urgent">URGENT</span><strong>${esc(urgent.title)}</strong><span>${esc(urgent.text||'')}</span></div>`:''}<div class="section-head"><div><h2>Cette semaine</h2><p>Les dates à retenir et les convocations associées.</p></div><button class="link-btn" onclick="app.go('calendar')">Tout voir →</button></div><div class="week-list">${week.map(weekEventCard).join('')||'<div class="empty">Aucune date importante cette semaine.</div>'}</div><div class="home-duo"><section><div class="section-head compact"><div><h2>Documents importants</h2><p>Les documents à avoir sous la main.</p></div><button class="link-btn" onclick="app.go('documents')">Tous →</button></div><div class="grid">${docs.map(homeDocumentCard).join('')||'<div class="empty">Aucun document mis en avant.</div>'}</div></section><section><div class="section-head compact"><div><h2>En images</h2><p>La vie de l’Association Sportive.</p></div>${cfg.instagramUrl?`<button class="link-btn" onclick="app.openExternal('${esc(cfg.instagramUrl)}')">Instagram ↗</button>`:''}</div>${photoGallery()}</section></div><div class="section-head"><div><h2>Accès rapides</h2></div></div><div class="grid grid-4">${quick('▣','Calendrier','Tous les rendez-vous','calendar')}${quick('✓','Convocations','Compétitions et départs','convocations')}${quick('▤','Documents','Les fichiers utiles','documents')}${quick('◫','Boutique','Commandes AS','shop')}</div></div>`;
  }
  function weekEventCard(e){const p=dateParts(e.date),conv=findConvocationForEvent(e);return`<article class="card week-card clickable" onclick="app.go('calendar')"><div class="date-badge week-date"><div class="day">${p.day}</div><div class="month">${p.month}</div></div><div class="week-main"><div class="event-title">${esc(e.title)}</div><div class="meta"><span>${esc(e.time||'')}</span><span>${e.place?'• '+esc(e.place):''}</span></div></div><div class="week-tags">${categoryBadge(e.category)}${conv?`<button class="convocation-chip" onclick="event.stopPropagation();app.openConvocation('${conv.id}')">CONVOCATION</button>`:''}</div></article>`}
  function findConvocationForEvent(e){return state.data.convocations.find(c=>c.date===e.date&&(c.category===e.category||String(c.title).toLowerCase().includes(String(e.category).toLowerCase())))}
  function homeDocumentCard(d){return`<article class="card home-doc clickable" onclick="app.openDocument('${d.id}')"><div class="doc-icon">PDF</div><div><div class="event-title">${esc(d.title)}</div><div class="meta">${categoryBadge(d.category)}<span>${fmtDate(d.date)}</span></div></div><span class="arrow">→</span></article>`}
  function photoGallery(){const photos=state.data.photos.slice(0,6);if(!photos.length)return`<div class="photo-empty"><img src="assets/logo-as.png" alt="Association Sportive"><div><strong>Les photos de l’AS apparaîtront ici.</strong><p>Ajoutez des photos depuis l’administration et, si besoin, associez chaque image à sa publication Instagram.</p></div></div>`;return`<div class="photo-strip">${photos.map(p=>`<button class="photo-card" onclick="app.openPhoto('${p.id}')"><img src="${esc(p.imageUrl)}" alt="${esc(p.caption||'Photo Association Sportive')}" loading="lazy"><span>${esc(p.caption||'Voir la photo')}</span></button>`).join('')}</div>`}
  function quick(ico,title,sub,route){return`<div class="card clickable quick" onclick="app.go('${route}')"><div class="quick-ico">${ico}</div><div><strong>${title}</strong><span>${sub}</span></div></div>`}
  function filters(){return`<div class="filters">${['Tous',...Object.keys(CATS)].map(c=>`<button class="filter-btn ${state.categoryFilter===c?'active':''}" onclick="app.filter('${c}')">${c==='Tous'?'Tout':esc(CATS[c].label)}</button>`).join('')}</div>`}
  function eventCard(e){const p=dateParts(e.date),conv=findConvocationForEvent(e);return`<article class="card event-card"><div class="date-badge"><div class="day">${p.day}</div><div class="month">${p.month}</div></div><div><div class="event-title">${esc(e.title)}</div><div class="meta"><span>${esc(e.time||'')}</span><span>${e.place?'• '+esc(e.place):''}</span></div></div><div class="event-actions">${categoryBadge(e.category)}${conv?`<button class="convocation-chip" onclick="app.openConvocation('${conv.id}')">CONVOCATION</button>`:''}</div></article>`}

  function calendarPage(){const q=state.search.toLowerCase();const rows=state.data.events.filter(visibleByCategory).filter(e=>`${e.title} ${e.place||''}`.toLowerCase().includes(q)).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||'')));return`<div class="container"><div class="page-title"><div><div class="kicker">CALENDRIER</div><h1>À venir</h1><p>Les entraînements, compétitions et rendez-vous sportifs.</p></div>${isTeacher()?'<button class="btn" onclick="app.openCrud(\'event\')">+ Événement</button>':''}</div>${filters()}<input class="search" placeholder="Rechercher un événement ou un lieu…" value="${esc(state.search)}" oninput="app.search(this.value)"><div class="grid" style="margin-top:15px">${rows.map(eventCard).join('')||'<div class="empty">Aucun événement ne correspond à votre recherche.</div>'}</div></div>`}
  function documentsPage(){const q=state.search.toLowerCase();const docs=state.data.documents.filter(visibleByCategory).filter(d=>`${d.title} ${d.description||''}`.toLowerCase().includes(q));return`<div class="container"><div class="page-title"><div><div class="kicker">DOCUMENTS</div><h1>Documents</h1><p>Les fichiers utiles de l’Association Sportive.</p></div>${isTeacher()?'<button class="btn" onclick="app.openCrud(\'document\')">+ Document</button>':''}</div>${filters()}<input class="search" placeholder="Rechercher un document…" value="${esc(state.search)}" oninput="app.search(this.value)"><div class="grid grid-2" style="margin-top:15px">${docs.map(d=>`<article class="card doc-card"><div class="doc-icon">PDF</div><div class="grow"><div class="event-title">${esc(d.title)}</div><div class="meta"><span>${fmtDate(d.date)}</span>${d.featured?'<span class="badge important">IMPORTANT</span>':''}</div><p class="info-text">${esc(d.description||'')}</p><div class="actions">${categoryBadge(d.category)}<button class="btn secondary" onclick="app.openDocument('${d.id}')">Consulter</button></div></div></article>`).join('')||'<div class="empty">Aucun document disponible.</div>'}</div></div>`}
  function shopPage(){return`<div class="container"><div class="page-title"><div><div class="kicker">BOUTIQUE</div><h1>Boutique AS</h1><p>Les commandes de l’Association Sportive.</p></div>${isTeacher()?'<button class="btn" onclick="app.openCrud(\'product\')">+ Produit</button>':''}</div><div class="grid grid-2">${state.data.products.map(p=>`<article class="card product"><div class="product-photo"><img src="${esc(p.imageUrl||'assets/logo-as.png')}" alt="Produit"></div><div class="product-body"><div class="event-title">${esc(p.name)}</div><p class="info-text">${esc(p.description||'')}</p><div class="product-price">${Number(p.price||0).toFixed(2).replace('.',',')} €</div><div class="meta">Commande avant le ${fmtDate(p.deadline)}</div><div class="actions"><button class="btn yellow" onclick="app.order('${p.id}')">Commander</button></div></div></article>`).join('')}</div></div>`}

  function convocationsPage(){if(!cfg.demoMode&&hasSupabase&&!state.user)return`<div class="container"><div class="empty"><h2>Convocations</h2><p>Connectez-vous pour consulter les convocations qui vous concernent.</p><button class="btn" onclick="app.openProfile()">Se connecter</button></div></div>`;return`<div class="container"><div class="page-title"><div><div class="kicker">COMPÉTITIONS</div><h1>Convocations</h1><p>Départ, retour, point de rendez-vous et informations utiles.</p></div>${isTeacher()?'<button class="btn" onclick="app.openCrud(\'convocation\')">+ Convocation</button>':''}</div><div class="grid">${state.data.convocations.map(convocationCard).join('')||'<div class="empty">Aucune convocation en cours.</div>'}</div></div>`}
  function convocationCard(c){const count=(c.studentIds||[]).length;return`<article class="card convocation-card clickable" onclick="app.openConvocation('${c.id}')"><div class="row-between"><div><div class="event-title">${esc(c.title)}</div><div class="meta"><span>${fmtLongDate(c.date)}</span><span>• ${esc(c.place||'')}</span></div></div>${categoryBadge(c.category)}</div><div class="grid grid-3 convocation-meta"><div><div class="kicker">Départ</div><strong>${esc(c.departure||'—')}</strong></div><div><div class="kicker">Retour</div><strong>${esc(c.returnTime||'—')}</strong></div><div><div class="kicker">Rendez-vous</div><strong>${esc(c.meetingPoint||'À préciser')}</strong></div></div>${c.extraInfo?`<p class="info-text"><strong>Info :</strong> ${esc(c.extraInfo)}</p>`:''}${isTeacher()?`<div class="participant-count">${count} élève${count>1?'s':''} sélectionné${count>1?'s':''}</div>`:''}</article>`}
  function morePage(){const tiles=[['✓','Convocations','convocations']];if(isEducator())tiles.push(['✎','Appréciations','appreciations']);if(isTeacher())tiles.push(['⚑','Licences','licenses'],['↗','Bilans AS','reports'],['⚙','Administration','admin']);return`<div class="container"><div class="page-title"><div><div class="kicker">PLUS</div><h1>Outils</h1><p>Les fonctions adaptées à votre profil.</p></div></div><div class="grid more-grid">${tiles.map(t=>`<div class="card clickable more-tile" onclick="app.go('${t[2]}')"><div class="big-icon">${t[0]}</div><strong>${t[1]}</strong></div>`).join('')}</div><div class="section-head"><div><h2>Votre profil</h2></div></div><div class="card"><strong>${esc(roleLabel())}</strong><p class="info-text">${state.user?esc(state.user.name):cfg.demoMode?'Mode démonstration':'Consultation publique'} · ${state.online?'En ligne':'Hors ligne'}</p><div class="actions"><button class="btn secondary" onclick="app.openProfile()">${state.user?'Mon compte':cfg.demoMode?'Changer de profil démo':'Connexion sécurisée'}</button></div></div></div>`}

  function educatorStudents(){const specialty=specialtyForRole();return state.data.students.filter(s=>!specialty||s.specialty===specialty).sort((a,b)=>`${a.lastName} ${a.firstName}`.localeCompare(`${b.lastName} ${b.firstName}`,'fr'))}
  function appreciationFor(studentId,term=state.term){const educatorId=state.user?.id||demoEducatorId();return state.data.appreciations.find(a=>a.studentId===studentId&&Number(a.term)===Number(term)&&(!a.educatorId||a.educatorId===educatorId))}
  function demoEducatorId(){return state.role==='educator_football'?'u-foot':state.role==='educator_escalade'?'u-esc':state.role==='educator_gymnastique'?'u-gym':''}
  function appreciationsPage(){
    if(!isEducator())return forbidden();const students=educatorStudents();const rows=students.map(s=>{const a=appreciationFor(s.id)||{text:'',status:'todo'};return`<tr><td><strong>${esc(s.lastName)} ${esc(s.firstName)}</strong><div class="meta">${esc(s.className)} · ${esc(s.specialty)}</div></td><td><textarea class="appreciation-text" lang="fr" spellcheck="true" placeholder="Saisir l’appréciation…" onchange="app.saveAppreciation('${s.id}',this.value)">${esc(a.text||'')}</textarea><div class="mini-actions"><button class="text-btn" onclick="app.cleanAppreciation('${s.id}')">Nettoyer la forme</button>${a.text?`<button class="text-btn" onclick="app.copyAppreciation('${s.id}')">Copier</button>`:''}</div></td><td><span class="badge ${a.status==='validated'?'normal':a.status==='draft'?'important':'urgent'}">${a.status==='validated'?'VALIDÉ':a.status==='draft'?'BROUILLON':'À FAIRE'}</span><div class="mini-actions column">${a.text?`<button class="btn tiny ${a.status==='validated'?'secondary':''}" onclick="app.toggleAppreciationValidation('${s.id}')">${a.status==='validated'?'Repasser en brouillon':'Valider'}</button>`:''}${a.id||a.text?`<button class="text-btn danger-text" onclick="app.deleteAppreciation('${s.id}')">Supprimer</button>`:''}</div></td></tr>`}).join('');const done=students.filter(s=>appreciationFor(s.id)?.status==='validated').length;const deadline=cfg.appreciationsDeadline||'2026-11-30';
    return`<div class="container"><div class="page-title"><div><div class="kicker">ÉDUCATEUR</div><h1>Appréciations</h1><p>${esc(CATS[specialtyForRole()]?.label||'Groupe')} · trimestre ${state.term}</p></div><div class="actions top-actions-inline"><button class="btn secondary" onclick="app.copyAllAppreciations('educator')">Copier toutes</button><button class="btn" onclick="app.exportAppreciationsCsv('educator')">Exporter CSV</button></div></div><div class="card"><div class="row-between appreciation-progress"><strong>${done} / ${students.length} appréciations validées</strong><span class="badge important">Échéance · ${fmtDate(deadline)}</span></div><div class="progress"><span style="width:${Math.round(done/Math.max(students.length,1)*100)}%"></span></div><p class="note correction-note">✓ Correcteur orthographique du navigateur activé. Le bouton « Nettoyer la forme » harmonise espaces, majuscule et ponctuation avant validation.</p></div><div class="card table-card" style="margin-top:14px"><table class="admin-table appreciation-table"><thead><tr><th>Élève</th><th>Appréciation</th><th>Statut</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
  }
  function licensesPage(){if(!isTeacher())return forbidden();const students=Object.fromEntries(state.data.students.map(s=>[s.id,s]));return`<div class="container"><div class="page-title"><div><div class="kicker">GESTION</div><h1>Licences</h1><p>La liste qui alimente notamment la sélection des convocations.</p></div><button class="btn" onclick="app.openCrud('license')">+ Licence</button></div><div class="card table-card"><table class="admin-table"><thead><tr><th>Élève</th><th>Classe</th><th>Activité</th><th>Statut</th><th>Date</th></tr></thead><tbody>${state.data.licenses.map(l=>{const s=students[l.studentId]||{};return`<tr><td><strong>${esc((s.lastName||'')+' '+(s.firstName||''))}</strong></td><td>${esc(s.className||'')}</td><td>${esc(l.activity||'')}</td><td><span class="badge ${String(l.status).toLowerCase()==='active'?'normal':'important'}">${esc(l.status||'')}</span></td><td>${fmtDate(l.date)}</td></tr>`}).join('')}</tbody></table></div></div>`}
  function reportsPage(){if(!isTeacher())return forbidden();return`<div class="container"><div class="page-title"><div><div class="kicker">BILAN AS</div><h1>Bilans du mercredi</h1><p>Une saisie rapide pour préparer le bilan annuel.</p></div><button class="btn" onclick="app.openCrud('report')">+ Bilan</button></div><div class="grid">${state.data.reports.map(r=>`<article class="card"><div class="row-between"><div><div class="event-title">${esc(r.activity)}</div><div class="meta">${fmtDate(r.date)} · ${esc(r.levels||'')}</div></div><div class="date-badge"><div class="day">${esc(r.participants)}</div><div class="month">élèves</div></div></div><p class="info-text">${esc(r.comment||'')}</p></article>`).join('')}</div></div>`}

  function adminPage(){
    if(!isTeacher())return forbidden();const tabs=[['dashboard','Tableau de bord'],['infos','Informations'],['events','Événements'],['convocations','Convocations'],['documents','Documents'],['photos','Photos'],['products','Boutique'],['appreciations','Appréciations']];if(isAdmin())tabs.push(['users','Utilisateurs']);let body='';if(state.adminTab==='dashboard')body=adminDashboard();if(state.adminTab==='infos')body=adminList('infos','Informations','announcement');if(state.adminTab==='events')body=adminList('events','Événements','event');if(state.adminTab==='convocations')body=adminList('convocations','Convocations','convocation');if(state.adminTab==='documents')body=adminList('documents','Documents','document');if(state.adminTab==='photos')body=adminList('photos','Photos','photo');if(state.adminTab==='products')body=adminList('products','Boutique','product');if(state.adminTab==='appreciations')body=adminAppreciations();if(state.adminTab==='users')body=adminUsers();return`<div class="container"><div class="page-title"><div><div class="kicker">ADMINISTRATION</div><h1>Bonjour ${esc((state.user?.name||'').split(' ')[0]||'')}</h1><p>Publier, organiser et récupérer les informations en quelques clics.</p></div></div><div class="admin-layout"><aside class="card admin-side"><div class="admin-menu">${tabs.map(t=>`<button class="${state.adminTab===t[0]?'active':''}" onclick="app.adminTab('${t[0]}')">${t[1]}</button>`).join('')}</div></aside><section>${body}</section></div></div>`;
  }
  function adminDashboard(){const missing=Math.max(0,state.data.students.length-state.data.appreciations.filter(a=>a.status==='validated').length);return`<div class="grid grid-2"><div class="card clickable" onclick="app.openCrud('announcement')"><div class="kicker">Raccourci</div><h2>+ Information</h2><p class="info-text">Publier une information en quelques secondes.</p></div><div class="card clickable" onclick="app.openCrud('event')"><div class="kicker">Raccourci</div><h2>+ Événement</h2><p class="info-text">Ajouter une date au calendrier.</p></div></div><div class="section-head"><div><h2>Vue synthétique</h2></div></div><div class="grid grid-3">${stat('Événements',state.data.events.length)}${stat('Documents',state.data.documents.length)}${stat('Convocations',state.data.convocations.length)}${stat('Appréciations à compléter',missing)}${stat('Commandes boutique',state.data.orders.length)}${stat('Licenciés',state.data.licenses.filter(l=>String(l.status).toLowerCase()==='active').length)}</div>`}
  function stat(label,n){return`<div class="card admin-stat"><div><div class="info-text">${label}</div><strong>${n}</strong></div><span class="quick-ico small">↗</span></div>`}
  function adminList(key,title,type){const rows=state.data[key]||[];return`<div class="card"><div class="row-between"><div><h2 class="flush">${title}</h2><p class="info-text">${rows.length} élément(s)</p></div><button class="btn" onclick="app.openCrud('${type}')">+ Ajouter</button></div><div class="table-card inner-table"><table class="admin-table"><thead><tr><th>Titre</th><th>Catégorie</th><th>Date</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.title||r.name||r.caption||r.activity||'Sans titre')}</strong></td><td>${r.category?categoryBadge(r.category):'—'}</td><td>${fmtDate(r.date||r.publishedAt||r.deadline)}</td><td><div class="table-actions"><button class="btn secondary tiny" onclick="app.editItem('${type}','${r.id}')">Modifier</button><button class="btn secondary tiny" onclick="app.duplicate('${key}','${r.id}')">Dupliquer</button><button class="btn danger tiny" onclick="app.remove('${key}','${r.id}')">Supprimer</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
  function adminAppreciations(){const students=Object.fromEntries(state.data.students.map(s=>[s.id,s]));const users=Object.fromEntries((state.data.users||[]).map(u=>[u.id,u]));const rows=state.data.appreciations.slice().sort((a,b)=>{const sa=students[a.studentId]||{},sb=students[b.studentId]||{};return`${sa.lastName} ${sa.firstName}`.localeCompare(`${sb.lastName} ${sb.firstName}`,'fr')});return`<div class="card"><div class="row-between"><div><h2 class="flush">Appréciations des éducateurs</h2><p class="info-text">Relecture et transfert rapide vers ÉcoleDirect.</p></div><div class="actions no-margin"><button class="btn secondary" onclick="app.copyAllAppreciations('admin')">Copier les validées</button><button class="btn" onclick="app.exportAppreciationsCsv('admin')">Exporter CSV</button></div></div><div class="table-card inner-table"><table class="admin-table"><thead><tr><th>Élève</th><th>Éducateur</th><th>Appréciation</th><th>Statut</th><th></th></tr></thead><tbody>${rows.map(a=>{const s=students[a.studentId]||{},u=users[a.educatorId]||{};return`<tr><td><strong>${esc((s.lastName||'')+' '+(s.firstName||''))}</strong><div class="meta">${esc(s.className||'')}</div></td><td>${esc(u.displayName||specialtyForEducatorId(a.educatorId)||'Éducateur')}</td><td class="appreciation-preview">${esc(a.text||'—')}</td><td><span class="badge ${a.status==='validated'?'normal':a.status==='draft'?'important':'urgent'}">${a.status==='validated'?'VALIDÉ':a.status==='draft'?'BROUILLON':'À FAIRE'}</span></td><td>${a.text?`<button class="btn secondary tiny" onclick="app.copyTextById('${a.id}')">Copier</button>`:''}</td></tr>`}).join('')}</tbody></table></div></div>`}
  function specialtyForEducatorId(id){return id==='u-foot'?'Football':id==='u-esc'?'Escalade':id==='u-gym'?'Gymnastique':''}
  function adminUsers(){if(!isAdmin())return forbidden();const users=state.data.users||[];return`<div class="card"><div class="row-between"><div><h2 class="flush">Utilisateurs sécurisés</h2><p class="info-text">Un compte personnel par éducateur ou enseignant.</p></div><button class="btn" onclick="app.openInviteUser()">+ Utilisateur</button></div><div class="table-card inner-table"><table class="admin-table"><thead><tr><th>Nom</th><th>E-mail</th><th>Rôle</th><th>Actions</th></tr></thead><tbody>${users.map(u=>`<tr><td><strong>${esc(u.displayName||u.display_name||'Utilisateur')}</strong></td><td>${esc(u.email||'')}</td><td><span class="badge normal">${esc(roleLabel(u.role))}</span></td><td><div class="table-actions"><button class="btn secondary tiny" onclick="app.openUserRole('${u.id}')">Modifier rôle</button><button class="btn secondary tiny" onclick="app.sendPasswordReset('${esc(u.email||'')}')">Réinitialiser le mot de passe</button></div></td></tr>`).join('')}</tbody></table></div><p class="note">Les mots de passe ne sont jamais visibles dans l’administration. La réinitialisation envoie un lien sécurisé à l’utilisateur.</p></div>`}
  function forbidden(){return`<div class="container"><div class="empty"><h2>Accès réservé</h2><p>Cette rubrique n’est pas disponible avec votre profil.</p></div></div>`}

  function modal(html,wide=false){const d=document.createElement('div');d.className='modal-backdrop';d.id='modal-root';d.innerHTML=`<div class="modal ${wide?'wide':''}">${html}</div>`;d.addEventListener('click',e=>{if(e.target===d)d.remove()});document.body.appendChild(d)}
  function closeModal(){document.getElementById('modal-root')?.remove()}
  function roleDescription(role){if(role==='public')return'Consultation';if(String(role).startsWith('educator_'))return'Appréciations de sa spécialité';if(role==='teacher_as')return'Convocations, licences, bilans et contenus';return'Tous les droits, utilisateurs compris'}
  function openProfile(){if(cfg.demoMode){modal(`<div class="modal-head"><h2>Profil de démonstration</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><p class="info-text">Choisissez un profil pour tester les droits de l’application.</p><div class="role-grid">${Object.entries(ROLE_LABELS).map(([k,v])=>`<button class="role-btn ${state.role===k?'active':''}" onclick="app.setRole('${k}')"><strong>${esc(v)}</strong><div class="note">${roleDescription(k)}</div></button>`).join('')}</div><p class="note">Le mode démonstration ne remplace pas l’authentification réelle. Dès que Supabase est configuré, chaque éducateur et enseignant utilise son propre mot de passe.</p>`);return}if(!state.user){openLoginModal();return}modal(`<div class="modal-head"><h2>Mon compte</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><p><strong>${esc(state.user.name||'')}</strong></p><p class="info-text">${esc(state.user.email||'')} · ${esc(roleLabel())}</p><div class="actions"><button class="btn secondary" onclick="app.openNewPasswordModal()">Changer mon mot de passe</button><button class="btn danger" onclick="app.logout()">Se déconnecter</button></div>`)}
  function openLoginModal(){if(!hasSupabase){modal(`<div class="modal-head"><h2>Connexion sécurisée</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><div class="empty"><p>La connexion est prête dans l’application, mais Supabase doit encore être relié dans <strong>config.js</strong> pour activer les comptes et mots de passe réels.</p></div>`);return}modal(`<div class="modal-head"><h2>Connexion sécurisée</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><form onsubmit="app.login(event)"><div class="field"><label>E-mail</label><input name="email" type="email" required autocomplete="username"></div><div class="field" style="margin-top:12px"><label>Mot de passe</label><input name="password" type="password" required autocomplete="current-password"></div><button class="btn full-btn" style="margin-top:16px">Se connecter</button></form><div class="actions"><button class="text-btn" onclick="app.openForgotPassword()">Mot de passe oublié ?</button></div>`)}
  function openForgotPassword(){modal(`<div class="modal-head"><h2>Mot de passe oublié</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><form onsubmit="app.requestOwnPasswordReset(event)"><div class="field"><label>E-mail</label><input name="email" type="email" required></div><button class="btn full-btn" style="margin-top:16px">Envoyer le lien</button></form>`)}
  function openNewPasswordModal(){closeModal();modal(`<div class="modal-head"><h2>Nouveau mot de passe</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><form onsubmit="app.updateOwnPassword(event)"><div class="field"><label>Nouveau mot de passe</label><input name="password" type="password" minlength="10" required autocomplete="new-password"></div><div class="field" style="margin-top:12px"><label>Confirmer</label><input name="confirm" type="password" minlength="10" required autocomplete="new-password"></div><p class="note">10 caractères minimum recommandés, avec lettres, chiffres et un caractère spécial.</p><button class="btn full-btn">Enregistrer</button></form>`)}

  function openCrud(type,item=null){
    const cOpt=Object.keys(CATS).map(c=>`<option value="${c}" ${item?.category===c?'selected':''}>${esc(CATS[c].label)}</option>`).join('');const head=`<div class="modal-head"><h2>${item?'Modifier':'Ajouter'} ${crudLabel(type)}</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div>`;let fields='';
    if(type==='event')fields=`${input('title','Titre',item?.title,true)}${select('category','Catégorie',cOpt)}${input('date','Date',item?.date,true,'date')}${input('time','Heure',item?.time,false,'time')}${input('place','Lieu',item?.place)}${input('audience','Public concerné',item?.audience||'Tous')}${textarea('description','Description',item?.description)}`;
    if(type==='announcement')fields=`${input('title','Titre',item?.title,true)}${select('category','Catégorie',cOpt)}${select('importance','Importance',`<option ${item?.importance==='NORMAL'?'selected':''}>NORMAL</option><option ${item?.importance==='IMPORTANT'?'selected':''}>IMPORTANT</option><option ${item?.importance==='URGENT'?'selected':''}>URGENT</option>`)}${input('publishedAt','Date de publication',item?.publishedAt||today(),true,'date')}${input('expiresAt','Fin de publication',item?.expiresAt,false,'date')}${textarea('text','Description',item?.text)}`;
    if(type==='document')fields=`${input('title','Titre',item?.title,true)}${select('category','Catégorie',cOpt)}${input('date','Date',item?.date||today(),true,'date')}${input('url','Lien / URL',item?.url||'#')}${checkbox('featured','Afficher dans « Documents importants »',!!item?.featured)}${textarea('description','Description',item?.description)}`;
    if(type==='photo')fields=`${input('imageUrl','URL de l’image',item?.imageUrl,true,'url')}${input('instagramUrl','Lien vers la publication Instagram',item?.instagramUrl,false,'url')}${input('date','Date',item?.date||today(),false,'date')}${checkbox('featured','Mettre en avant',item?.featured!==false)}${textarea('caption','Légende',item?.caption)}`;
    if(type==='product')fields=`${input('name','Nom du produit',item?.name,true)}${input('price','Prix (€)',item?.price,true,'number')}${input('deadline','Date limite',item?.deadline,true,'date')}${input('sizes','Tailles (séparées par des virgules)',Array.isArray(item?.sizes)?item.sizes.join(', '):(item?.sizes||''))}${textarea('description','Description',item?.description)}`;
    if(type==='convocation')fields=convocationFields(item,cOpt);
    if(type==='license')fields=`${select('studentId','Élève',state.data.students.map(s=>`<option value="${s.id}" ${item?.studentId===s.id?'selected':''}>${esc(s.lastName)} ${esc(s.firstName)} — ${esc(s.className)}</option>`).join(''))}${select('activity','Activité',Object.keys(CATS).map(c=>`<option value="${c}" ${item?.activity===c?'selected':''}>${esc(CATS[c].label)}</option>`).join(''))}${select('status','Statut',`<option ${item?.status==='Active'?'selected':''}>Active</option><option ${item?.status==='En attente'?'selected':''}>En attente</option><option ${item?.status==='Inactive'?'selected':''}>Inactive</option>`)}${input('date','Date',item?.date||today(),true,'date')}`;
    if(type==='report')fields=`${input('activity','Activité',item?.activity,true)}${input('date','Date',item?.date||today(),true,'date')}${input('participants','Nombre de participants',item?.participants,true,'number')}${input('levels','Niveaux / classes',item?.levels)}${input('result','Résultats éventuels',item?.result)}${textarea('comment','Commentaire',item?.comment)}`;
    modal(`${head}<form onsubmit="app.saveCrud(event,'${type}','${item?.id||''}')"><div class="form-grid">${fields}</div><div class="actions modal-actions"><button type="button" class="btn secondary" onclick="app.closeModal()">Annuler</button><button class="btn">${item?'Enregistrer':'Publier'}</button></div></form>`,type==='convocation');if(type==='convocation')setTimeout(()=>{updateStudentPickerSummary();filterStudentPicker(item?.category||'AS')},0);
  }
  function convocationFields(item,cOpt){const category=item?.category||'AS';return`${input('title','Compétition',item?.title,true)}${select('category','Catégorie',cOpt,'app.filterStudentPicker(this.value)')}${input('date','Date',item?.date,true,'date')}${input('place','Lieu de la compétition',item?.place)}${input('departure','Heure de départ',item?.departure,false,'time')}${input('returnTime','Heure de retour',item?.returnTime,false,'time')}${input('meetingPoint','Lieu du point de rendez-vous',item?.meetingPoint)}${textarea('equipment','Matériel nécessaire',item?.equipment)}${textarea('extraInfo','Informations complémentaires',item?.extraInfo)}${studentPicker(category,item?.studentIds||[])}`}
  function studentPicker(category,selected){const candidates=licensedStudentEntries();return`<div class="field full"><label>Élèves convoqués · issus des licences actives</label><details class="student-picker" open><summary><span id="student-picker-summary">Sélectionner les élèves</span><span>⌄</span></summary><div class="student-picker-body"><input id="student-search" class="search compact-search" type="search" placeholder="Rechercher un élève…" oninput="app.searchStudentPicker(this.value)"><div id="student-options" class="student-options">${candidates.map(({student,license})=>`<label class="student-option" data-name="${esc(normalizeName(student.lastName+' '+student.firstName))}" data-activity="${esc(license.activity)}"><input type="checkbox" name="studentIds" value="${student.id}" ${selected.includes(student.id)?'checked':''} onchange="app.updateStudentPickerSummary()"><span><strong>${esc(student.lastName)} ${esc(student.firstName)}</strong><small>${esc(student.className)} · ${esc(license.activity)}</small></span></label>`).join('')||'<div class="empty small-empty">Aucune licence active.</div>'}</div><div class="paste-box"><label>Ou coller une liste d’élèves</label><textarea id="pasted-students" placeholder="DUPONT Emma\nMARTIN Léo"></textarea><button type="button" class="btn secondary" onclick="app.matchPastedStudents()">Ajouter depuis la liste</button></div></div></details></div>`}
  function licensedStudentEntries(){const byId=Object.fromEntries(state.data.students.map(s=>[s.id,s]));const seen=new Set(),out=[];for(const l of state.data.licenses){if(String(l.status||'').toLowerCase()!=='active')continue;const s=byId[l.studentId];if(!s||seen.has(s.id))continue;seen.add(s.id);out.push({student:s,license:l})}return out.sort((a,b)=>`${a.student.lastName} ${a.student.firstName}`.localeCompare(`${b.student.lastName} ${b.student.firstName}`,'fr'))}
  function updateStudentPickerSummary(){const checks=[...document.querySelectorAll('#modal-root input[name="studentIds"]:checked')];const el=document.getElementById('student-picker-summary');if(el)el.textContent=checks.length?`${checks.length} élève${checks.length>1?'s':''} sélectionné${checks.length>1?'s':''}`:'Sélectionner les élèves'}
  function filterStudentPicker(category){document.querySelectorAll('#student-options .student-option').forEach(el=>{const activity=el.dataset.activity;const hidden=category!=='AS'&&activity!==category;el.dataset.categoryHidden=hidden?'1':'0';el.hidden=hidden})}
  function searchStudentPicker(value){const q=normalizeName(value);document.querySelectorAll('#student-options .student-option').forEach(el=>{const byCategory=el.dataset.categoryHidden==='1';const bySearch=!!q&&!el.dataset.name.includes(q);el.hidden=byCategory||bySearch})}
  function normalizeName(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
  function matchPastedStudents(){const input=document.getElementById('pasted-students');if(!input)return;const lines=input.value.split(/\n|,|;/).map(normalizeName).filter(Boolean);let matched=0;document.querySelectorAll('#student-options .student-option').forEach(el=>{if(el.dataset.categoryHidden==='1')return;const name=el.dataset.name;const match=lines.some(line=>name===line||name.includes(line)||line.includes(name));if(match){const cb=el.querySelector('input');if(cb&&!cb.checked){cb.checked=true;matched++}}});updateStudentPickerSummary();toast(`${matched} élève${matched>1?'s':''} ajouté${matched>1?'s':''} depuis la liste`)}
  function crudLabel(t){return({event:'un événement',announcement:'une information',document:'un document',photo:'une photo',product:'un produit',convocation:'une convocation',license:'une licence',report:'un bilan'})[t]||'un élément'}
  function input(name,label,value='',req=false,type='text'){return`<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value??'')}" ${req?'required':''}></div>`}
  function select(name,label,opts,onchange=''){return`<div class="field"><label>${label}</label><select name="${name}" ${onchange?`onchange="${onchange}"`:''}>${opts}</select></div>`}
  function textarea(name,label,value=''){return`<div class="field full"><label>${label}</label><textarea name="${name}" lang="fr" spellcheck="true">${esc(value??'')}</textarea></div>`}
  function checkbox(name,label,checked=false){return`<label class="check-field field full"><input name="${name}" type="checkbox" ${checked?'checked':''}><span>${label}</span></label>`}

  async function saveCrud(ev,type,id){ev.preventDefault();const form=new FormData(ev.target);const obj=Object.fromEntries(form.entries());const map={event:['events','events'],announcement:['infos','announcements'],document:['documents','documents'],photo:['photos','photos'],product:['products','products'],convocation:['convocations','convocations'],license:['licenses','licenses'],report:['reports','as_reports']};const[key,table]=map[type];if(type==='document')obj.featured=form.get('featured')==='on';if(type==='photo')obj.featured=form.get('featured')==='on';if(type==='product'){obj.price=Number(obj.price||0);obj.sizes=(obj.sizes||'').split(',').map(x=>x.trim()).filter(Boolean);obj.category='AS'}if(type==='report')obj.participants=Number(obj.participants||0);if(type==='convocation'){obj.status='published';obj.studentIds=form.getAll('studentIds')}if(hasSupabase&&!cfg.demoMode){const selectedStudents=type==='convocation'?[...obj.studentIds]:[];delete obj.studentIds;const remote=camelToSnake(obj);let savedId=id;for(const k of['time','departure','return_time','deadline','expires_at'])if(remote[k]==='')remote[k]=null;let result;if(id)result=await supabase.from(table).update(remote).eq('id',id).select().single();else result=await supabase.from(table).insert(remote).select().single();if(result.error){toast('Erreur : '+result.error.message);return}savedId=result.data?.id||id;if(type==='convocation'&&savedId){const del=await supabase.from('convocation_students').delete().eq('convocation_id',savedId);if(del.error){toast('Convocation enregistrée, mais erreur sur la liste des élèves');return}if(selectedStudents.length){const ins=await supabase.from('convocation_students').insert(selectedStudents.map(studentId=>({convocation_id:savedId,student_id:studentId})));if(ins.error){toast('Convocation enregistrée, mais erreur sur la liste des élèves');return}}}await loadRemoteData()}else{obj.id=id||uid(type[0]);const arr=state.data[key];const ix=arr.findIndex(x=>x.id===obj.id);if(ix>=0)arr[ix]={...arr[ix],...obj};else arr.unshift(obj);saveLocal()}closeModal();render();toast(id?'Modification enregistrée':'Publication effectuée')}
  function editItem(type,id){const key={event:'events',announcement:'infos',document:'documents',photo:'photos',product:'products',convocation:'convocations'}[type];const item=state.data[key]?.find(x=>x.id===id);if(item)openCrud(type,item)}
  function duplicate(key,id){const arr=state.data[key],item=arr.find(x=>x.id===id);if(!item)return;arr.unshift({...structuredClone(item),id:uid('d'),title:item.title?item.title+' — copie':undefined,name:item.name?item.name+' — copie':undefined,caption:item.caption?item.caption+' — copie':undefined});saveLocal();render();toast('Élément dupliqué')}
  async function remove(key,id){if(!confirm('Supprimer cet élément ?'))return;const table={events:'events',infos:'announcements',documents:'documents',photos:'photos',products:'products',convocations:'convocations'}[key];if(hasSupabase&&!cfg.demoMode&&table){const{error}=await supabase.from(table).delete().eq('id',id);if(error){toast(error.message);return}await loadRemoteData()}else{state.data[key]=state.data[key].filter(x=>x.id!==id);saveLocal()}render();toast('Élément supprimé')}
  function openDocument(id){const d=state.data.documents.find(x=>x.id===id);if(!d)return;const url=safeUrl(d.url);if(url)window.open(url,'_blank','noopener');else toast('Aucun fichier ou lien n’est encore associé à ce document.')}
  function openPhoto(id){const p=state.data.photos.find(x=>x.id===id);if(!p)return;const link=safeUrl(p.instagramUrl);modal(`<div class="modal-head"><h2>${esc(p.caption||'Photo de l’AS')}</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><img class="photo-modal" src="${esc(p.imageUrl)}" alt="${esc(p.caption||'Photo')}">${link?`<div class="actions"><button class="btn" onclick="app.openExternal('${esc(link)}')">Voir sur Instagram ↗</button></div>`:''}`)}
  function openExternal(url){const u=safeUrl(url);if(u)window.open(u,'_blank','noopener')}
  function openConvocation(id){const c=state.data.convocations.find(x=>x.id===id);if(!c)return;const students=Object.fromEntries(state.data.students.map(s=>[s.id,s]));const selected=(c.studentIds||[]).map(x=>students[x]).filter(Boolean);const list=isTeacher()&&selected.length?`<div class="convocation-students"><div class="kicker">Élèves convoqués</div><div class="student-chip-list">${selected.map(s=>`<span class="student-chip">${esc(s.lastName)} ${esc(s.firstName)} · ${esc(s.className)}</span>`).join('')}</div></div>`:'';modal(`<div class="modal-head"><div><div class="kicker">CONVOCATION</div><h2>${esc(c.title)}</h2></div><button class="icon-btn" onclick="app.closeModal()">×</button></div><div class="convocation-detail"><div class="detail-block"><span>Date</span><strong>${fmtLongDate(c.date)}</strong></div><div class="detail-block"><span>Lieu</span><strong>${esc(c.place||'À préciser')}</strong></div><div class="detail-block"><span>Départ</span><strong>${esc(c.departure||'À préciser')}</strong></div><div class="detail-block"><span>Retour</span><strong>${esc(c.returnTime||'À préciser')}</strong></div><div class="detail-block full"><span>Point de rendez-vous</span><strong>${esc(c.meetingPoint||'À préciser')}</strong></div>${c.equipment?`<div class="detail-block full"><span>Matériel nécessaire</span><strong>${esc(c.equipment)}</strong></div>`:''}${c.extraInfo?`<div class="detail-block full"><span>Informations complémentaires</span><strong>${esc(c.extraInfo)}</strong></div>`:''}</div>${list}${isTeacher()?`<div class="actions"><button class="btn secondary" onclick="app.closeModal();app.editItem('convocation','${c.id}')">Modifier</button></div>`:''}`,true)}

  function order(productId){const p=state.data.products.find(x=>x.id===productId);if(!p)return;const opts=(p.sizes||[]).map(s=>`<option>${esc(s)}</option>`).join('');modal(`<div class="modal-head"><h2>Commander</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><p><strong>${esc(p.name)}</strong></p><form onsubmit="app.saveOrder(event,'${p.id}')"><div class="form-grid">${input('name','Nom et prénom','',true)}${select('size','Taille',opts)}${input('quantity','Quantité','1',true,'number')}</div><div class="actions"><button class="btn yellow">Valider la commande</button></div></form>`)}
  function saveOrder(e,productId){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());state.data.orders.push({id:uid('o'),productId,...fd,quantity:Number(fd.quantity||1),status:'received'});saveLocal();closeModal();toast('Commande enregistrée')}

  async function saveAppreciation(studentId,text){const educatorId=state.user?.id||demoEducatorId();let a=appreciationFor(studentId);if(!a){a={id:cfg.demoMode||!hasSupabase?uid('a'):null,studentId,educatorId,term:state.term,text:'',status:'todo'};state.data.appreciations.push(a)}a.text=text;a.status=text.trim()?'draft':'todo';a.educatorId=educatorId;if(hasSupabase&&!cfg.demoMode){const payload=camelToSnake({studentId,educatorId,term:state.term,text:a.text,status:a.status});let result;if(a.id)result=await supabase.from('appreciations').update(payload).eq('id',a.id).select().single();else result=await supabase.from('appreciations').insert(payload).select().single();if(result.error){toast('Erreur : '+result.error.message);return}a.id=result.data.id}else saveLocal();toast('Brouillon enregistré');render()}
  async function toggleAppreciationValidation(studentId){const a=appreciationFor(studentId);if(!a?.text?.trim()){toast('Saisissez une appréciation avant de la valider.');return}a.status=a.status==='validated'?'draft':'validated';await persistAppreciation(a);render();toast(a.status==='validated'?'Appréciation validée':'Repassée en brouillon')}
  async function persistAppreciation(a){if(hasSupabase&&!cfg.demoMode){const{error}=await supabase.from('appreciations').update({text:a.text,status:a.status,updated_at:new Date().toISOString()}).eq('id',a.id);if(error){toast(error.message);return false}}else saveLocal();return true}
  async function deleteAppreciation(studentId){const a=appreciationFor(studentId);if(!a)return;if(!confirm('Supprimer cette appréciation ?'))return;if(hasSupabase&&!cfg.demoMode&&a.id){const{error}=await supabase.from('appreciations').delete().eq('id',a.id);if(error){toast(error.message);return}}state.data.appreciations=state.data.appreciations.filter(x=>x!==a);saveLocal();render();toast('Appréciation supprimée')}
  async function cleanAppreciation(studentId){const a=appreciationFor(studentId);if(!a?.text)return;let t=a.text.trim().replace(/\s+/g,' ').replace(/\s+([,.;:!?])/g,'$1');t=t.charAt(0).toUpperCase()+t.slice(1);if(!/[.!?]$/.test(t))t+='.';a.text=t;a.status='draft';await persistAppreciation(a);render();toast('Mise en forme harmonisée')}
  function copyAppreciation(studentId){const a=appreciationFor(studentId);if(a?.text)copyText(a.text)}
  function copyTextById(id){const a=state.data.appreciations.find(x=>x.id===id);if(a?.text)copyText(a.text)}
  function appreciationRowsForExport(scope){const students=Object.fromEntries(state.data.students.map(s=>[s.id,s]));let list=state.data.appreciations.filter(a=>a.status==='validated'&&a.text?.trim());if(scope==='educator'){const educatorId=state.user?.id||demoEducatorId();list=list.filter(a=>a.educatorId===educatorId||(!a.educatorId&&educatorStudents().some(s=>s.id===a.studentId)))}return list.map(a=>({a,s:students[a.studentId]||{}})).sort((x,y)=>`${x.s.lastName} ${x.s.firstName}`.localeCompare(`${y.s.lastName} ${y.s.firstName}`,'fr'))}
  function copyAllAppreciations(scope){const rows=appreciationRowsForExport(scope);if(!rows.length){toast('Aucune appréciation validée à copier.');return}const text=rows.map(({a,s})=>`${s.lastName||''} ${s.firstName||''} — ${s.className||''}\n${a.text}`).join('\n\n');copyText(text)}
  function exportAppreciationsCsv(scope){const rows=appreciationRowsForExport(scope);if(!rows.length){toast('Aucune appréciation validée à exporter.');return}const lines=[['Nom','Prénom','Classe','Activité','Appréciation'],...rows.map(({a,s})=>[s.lastName||'',s.firstName||'',s.className||'',s.specialty||'',a.text||''])];const csv='\ufeff'+lines.map(row=>row.map(csvCell).join(';')).join('\r\n');downloadBlob(csv,'appreciations-ecoledirect.csv','text/csv;charset=utf-8')}
  function csvCell(v){return`"${String(v??'').replace(/"/g,'""')}"`}
  async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copié dans le presse-papiers')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copié dans le presse-papiers')}}
  function downloadBlob(content,name,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}

  function openInviteUser(){if(!isAdmin())return;const opts=Object.entries(ROLE_LABELS).filter(([r])=>r!=='public').map(([r,l])=>`<option value="${r}">${esc(l)}</option>`).join('');modal(`<div class="modal-head"><h2>Ajouter un utilisateur</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><form onsubmit="app.inviteUser(event)"><div class="form-grid">${input('displayName','Nom affiché','',true)}${input('email','E-mail','',true,'email')}${select('role','Rôle',opts)}</div><p class="note">L’utilisateur recevra un e-mail sécurisé pour créer son mot de passe. Aucun mot de passe n’est stocké dans le code.</p><div class="actions modal-actions"><button class="btn">Envoyer l’invitation</button></div></form>`)}
  async function inviteUser(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());if(cfg.demoMode||!hasSupabase){state.data.users.push({id:uid('u'),...data});saveLocal();closeModal();render();toast('Utilisateur ajouté en mode démonstration');return}const{data:result,error}=await supabase.functions.invoke('admin-users',{body:{action:'invite',email:data.email,displayName:data.displayName,role:data.role,redirectTo:location.origin+location.pathname}});if(error||result?.error){toast('Invitation impossible : '+(error?.message||result?.error||'fonction Supabase à déployer'));return}closeModal();await loadRemoteData();render();toast('Invitation envoyée')}
  function openUserRole(id){const u=state.data.users.find(x=>x.id===id);if(!u)return;const opts=Object.entries(ROLE_LABELS).filter(([r])=>r!=='public').map(([r,l])=>`<option value="${r}" ${u.role===r?'selected':''}>${esc(l)}</option>`).join('');modal(`<div class="modal-head"><h2>Modifier le rôle</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div><p><strong>${esc(u.displayName||'Utilisateur')}</strong></p><form onsubmit="app.saveUserRole(event,'${u.id}')">${select('role','Rôle',opts)}<div class="actions"><button class="btn">Enregistrer</button></div></form>`)}
  async function saveUserRole(e,id){e.preventDefault();const role=new FormData(e.target).get('role');if(cfg.demoMode||!hasSupabase){const u=state.data.users.find(x=>x.id===id);if(u)u.role=role;saveLocal();closeModal();render();toast('Rôle modifié');return}const{error}=await supabase.from('profiles').update({role}).eq('id',id);if(error){toast(error.message);return}closeModal();await loadRemoteData();render();toast('Rôle modifié')}
  async function sendPasswordReset(email){if(!email){toast('Aucune adresse e-mail associée.');return}if(cfg.demoMode||!hasSupabase){toast('Réinitialisation simulée : activez Supabase pour envoyer le lien sécurisé.');return}const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error){toast(error.message);return}toast('Lien de réinitialisation envoyé')}
  async function requestOwnPasswordReset(e){e.preventDefault();const email=new FormData(e.target).get('email');await sendPasswordReset(email);closeModal()}
  async function updateOwnPassword(e){e.preventDefault();const fd=new FormData(e.target),password=fd.get('password'),confirmPw=fd.get('confirm');if(password!==confirmPw){toast('Les deux mots de passe ne correspondent pas.');return}if(!hasSupabase){toast('Supabase doit être configuré.');return}const{error}=await supabase.auth.updateUser({password});if(error){toast(error.message);return}closeModal();toast('Mot de passe mis à jour')}

  const app={
    go(route){state.route=route;state.search='';state.categoryFilter='Tous';render();window.scrollTo({top:0,behavior:'smooth'})},filter(c){state.categoryFilter=c;render()},search(v){state.search=v;render();const s=document.querySelector('.search');if(s){s.focus();s.setSelectionRange(v.length,v.length)}},toggleTheme(){state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);localStorage.setItem('bs-dark',state.dark?'1':'0');render()},openProfile,closeModal,openLoginModal,openForgotPassword,openNewPasswordModal,
    setRole(r){state.role=r;state.user=r==='public'?null:{id:r==='educator_football'?'u-foot':r==='educator_escalade'?'u-esc':r==='educator_gymnastique'?'u-gym':r==='teacher_as'?'u-teacher':'u-admin',name:roleLabel(r),email:`${r}@demo.local`};closeModal();render();toast('Profil : '+roleLabel(r))},adminTab(t){state.adminTab=t;render()},openCrud,saveCrud,editItem,duplicate,remove,openDocument,openPhoto,openExternal,openConvocation,filterStudentPicker,searchStudentPicker,updateStudentPickerSummary,matchPastedStudents,order,saveOrder,saveAppreciation,toggleAppreciationValidation,deleteAppreciation,cleanAppreciation,copyAppreciation,copyTextById,copyAllAppreciations,exportAppreciationsCsv,openInviteUser,inviteUser,openUserRole,saveUserRole,sendPasswordReset,requestOwnPasswordReset,updateOwnPassword,
    async login(e){e.preventDefault();if(!supabase){toast('Supabase n’est pas configuré.');return}const fd=Object.fromEntries(new FormData(e.target).entries());const{error}=await supabase.auth.signInWithPassword({email:fd.email,password:fd.password});if(error)toast('Connexion impossible : '+error.message);else closeModal()},async logout(){if(supabase)await supabase.auth.signOut();state.user=null;state.role='public';closeModal();await loadPublicData();render()}
  };
  window.app=app;
  window.addEventListener('online',()=>{state.online=true});window.addEventListener('offline',()=>{state.online=false});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);initAuth();
})();