(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const C={navy:[16,33,63],blue:[7,87,201],yellow:[255,210,26],ink:[19,33,58],muted:[103,118,142],line:[220,229,240],paper:[250,252,255],white:[255,255,255],pale:[243,247,252],football:[37,130,233],escalade:[112,87,217],gym:[152,89,206],as:[213,174,0],green:[32,145,83],red:[190,45,67]};
const accent=s=>s==='Section Football'?C.football:s==='Option Escalade'?C.escalade:s==='Sport-études Gymnastique'?C.gym:C.as;
const str=v=>String(v??'');
function tx(doc,t,x,y,size=10,style='normal',color=C.ink,opts={}){doc.setFont('helvetica',style);doc.setFontSize(size);doc.setTextColor(...color);doc.text(Array.isArray(t)?t:str(t),x,y,opts)}
function wrap(doc,t,w,size=10,max=2){doc.setFontSize(size);return doc.splitTextToSize(str(t),w).slice(0,max)}
function rounded(doc,x,y,w,h,fill=C.white,stroke=C.line,r=4){doc.setFillColor(...fill);doc.setDrawColor(...stroke);doc.roundedRect(x,y,w,h,r,r,'FD')}
async function logo(){try{return await V.logoData()}catch{return null}}
function top(doc,lg,title,sub,right=''){
 doc.setFillColor(...C.navy);doc.rect(0,0,297,34,'F');doc.setFillColor(...C.yellow);doc.rect(0,34,297,2.6,'F');
 if(lg)try{doc.setFillColor(...C.white);doc.roundedRect(10,5,24,24,5,5,'F');doc.addImage(lg,'PNG',12,7,20,20)}catch{}
 tx(doc,'ASSOCIATION SPORTIVE DU BON SAUVEUR',40,10,7,'bold',[187,202,225]);tx(doc,title,40,24,20,'bold',C.white);tx(doc,sub,40,31,7.5,'bold',C.yellow);
 if(right)tx(doc,right,286,23,8.5,'bold',C.yellow,{align:'right'});
}
function bottom(doc,p,total){doc.setDrawColor(...C.line);doc.line(12,198,285,198);tx(doc,'BON SAUVEUR · SAINT-LÔ',12,204,6.5,'bold',C.muted);tx(doc,`${p}/${total}`,285,204,6.5,'bold',C.muted,{align:'right'})}
function dateRange(events){if(!events.length)return'';const a=V.fmtShort(events[0].date),b=V.fmtShort(events[events.length-1].date);return a===b?a:`${a} → ${b}`}
function chip(doc,label,x,y,w,color,light=false){doc.setFillColor(...(light?[241,246,253]:color));doc.roundedRect(x,y,w,7,3.5,3.5,'F');tx(doc,label,x+w/2,y+4.8,6.5,'bold',light?color:C.white,{align:'center'})}
function eventCard(doc,e,x,y,w,h,hasConv,full=false){
 const a=accent(e.specialty),d=new Date(e.date+'T12:00:00'),day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();
 rounded(doc,x,y,w,h,C.white,C.line,5);doc.setFillColor(...a);doc.roundedRect(x,y,5,h,2.5,2.5,'F');
 doc.setFillColor(...C.navy);doc.roundedRect(x+10,y+8,30,30,7,7,'F');tx(doc,day,x+25,y+24,19,'bold',C.white,{align:'center'});tx(doc,mon,x+25,y+32,6,'bold',C.yellow,{align:'center'});
 const titleX=x+47,titleW=w-57-(hasConv?31:0),fs=full?14:12.5,lines=wrap(doc,e.title,titleW,fs,2);tx(doc,lines,titleX,y+14,fs,'bold',C.ink);const titleEnd=y+14+(lines.length-1)*5.5;
 const spec=str(e.specialty||'Association Sportive'),pw=Math.min(full?62:51,Math.max(25,spec.length*2));chip(doc,spec,titleX,titleEnd+5,pw,a,true);
 tx(doc,`${e.startTime||'—'}${e.endTime?'  →  '+e.endTime:''}`,titleX,y+h-14,8.7,'bold',C.ink);tx(doc,str(e.place||'—'),titleX,y+h-7,7.4,'normal',C.muted);tx(doc,str(e.ageCategory||'Toutes catégories'),x+w-9,y+h-7,7.1,'bold',C.muted,{align:'right'});
 if(hasConv)chip(doc,'CONVOCATION',x+w-34,y+8,27,C.blue,false);
}
app.exportCalendarPDF=async()=>{
 const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),sp=V.edu();const events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');
 const lg=await logo(),per=5,pages=Math.ceil(events.length/per),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});
 for(let p=0;p<pages;p++){if(p)doc.addPage('a4','landscape');doc.setFillColor(...C.paper);doc.rect(0,0,297,210,'F');const ch=events.slice(p*per,p*per+per);top(doc,lg,'CALENDRIER AS',sp||'Association Sportive',dateRange(ch));tx(doc,'RENDEZ-VOUS À VENIR',12,46,7,'bold',C.blue);
  const rows=Math.ceil(ch.length/2),gap=7,bodyTop=51,bodyBottom=193,available=bodyBottom-bodyTop,h=Math.min(43,(available-gap*(rows-1))/rows),w=133;
  ch.forEach((e,i)=>{const lastOdd=ch.length%2===1&&i===ch.length-1,col=i%2,row=Math.floor(i/2),x=lastOdd?12:(12+col*(w+7)),y=bodyTop+row*(h+gap),cw=lastOdd?273:w,has=(d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&c.title===e.title));eventCard(doc,e,x,y,cw,h,has,lastOdd)});bottom(doc,p+1,pages)}
 doc.save(sp?`Calendrier_${V.clean(sp)}.pdf`:'Calendrier_AS_Bon_Sauveur.pdf');
};
function infoBox(doc,label,value,x,y,w,h=23){rounded(doc,x,y,w,h,C.pale,C.line,4);tx(doc,label.toUpperCase(),x+6,y+7,5.6,'bold',C.muted);const l=wrap(doc,value,w-12,10.2,2);tx(doc,l,x+6,y+16,10.2,'bold',C.ink)}
function datePanel(doc,c,x,y,w,h,a){rounded(doc,x,y,w,h,C.navy,C.navy,6);doc.setFillColor(...a);doc.roundedRect(x,y,5,h,3,3,'F');const d=new Date(c.date+'T12:00:00');const wd=d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),day=String(d.getDate()).padStart(2,'0'),mo=d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase(),yr=d.getFullYear();tx(doc,wd,x+12,y+15,7,'bold',C.yellow);tx(doc,day,x+12,y+48,34,'bold',C.white);tx(doc,mo,x+12,y+59,10,'bold',C.white);tx(doc,String(yr),x+12,y+67,7,'bold',[190,204,226]);tx(doc,'PROFESSEUR RÉFÉRENT',x+12,y+88,5.6,'bold',[177,193,216]);tx(doc,c.teacher||'À renseigner',x+12,y+98,9,'bold',C.white);chip(doc,c.specialty||'Association Sportive',x+12,y+h-18,w-24,a,false)}
function studentArea(doc,names,x,y,w,h){rounded(doc,x,y,w,h,C.white,C.line,5);tx(doc,'ÉLÈVES CONVOQUÉS',x+8,y+10,7,'bold',C.blue);tx(doc,String(names.length),x+w-8,y+10,7,'bold',C.muted,{align:'right'});const cols=w>180?4:3,cw=(w-16)/cols;names.slice(0,16).forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),xx=x+8+col*cw,yy=y+16+row*8.5;doc.setFillColor(...C.pale);doc.roundedRect(xx,yy,cw-4,7,3.5,3.5,'F');tx(doc,n,xx+3,yy+4.8,6.4,'bold',C.ink)})}
app.exportConvocation=async id=>{
 const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),lg=await logo(),a=accent(c.specialty),rest=names.slice(16),pages=1+Math.ceil(rest.length/32),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});
 doc.setFillColor(...C.paper);doc.rect(0,0,297,210,'F');top(doc,lg,'CONVOCATION',c.specialty||'Association Sportive',V.fmtShort(c.date));datePanel(doc,c,12,48,66,141,a);
 tx(doc,(c.activity||'ACTIVITÉ').toUpperCase(),88,54,7,'bold',a);const title=wrap(doc,c.title||c.activity,185,20,2);tx(doc,title,88,68,20,'bold',C.ink);chip(doc,c.ageCategory||'Toutes catégories',242,52,43,a,true);
 infoBox(doc,'Lieu',c.place||'—',88,82,60,24);infoBox(doc,'Départ',c.departure||'—',153,82,38,24);infoBox(doc,'Retour',c.returnTime||'—',196,82,38,24);infoBox(doc,'Rendez-vous',c.meetingPoint||'—',239,82,46,24);
 rounded(doc,88,112,197,29,[255,249,220],[239,210,74],5);doc.setFillColor(...C.yellow);doc.roundedRect(88,112,5,29,3,3,'F');tx(doc,'INFORMATIONS IMPORTANTES',99,120,6,'bold',C.blue);const info=wrap(doc,c.extraInfo||'Aucune information particulière.',176,10.5,2);tx(doc,info,99,132,10.5,'bold',C.ink);
 studentArea(doc,names,88,147,197,42);bottom(doc,1,pages);
 for(let p=1;p<pages;p++){doc.addPage('a4','landscape');doc.setFillColor(...C.paper);doc.rect(0,0,297,210,'F');top(doc,lg,'CONVOCATION',c.title||c.activity||'',V.fmtShort(c.date));const chunk=rest.slice((p-1)*32,p*32);rounded(doc,12,49,273,142,C.white,C.line,6);tx(doc,'ÉLÈVES CONVOQUÉS — SUITE',20,63,8,'bold',C.blue);const cols=4,cw=62;chunk.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=20+col*66,y=73+row*13;doc.setFillColor(...C.pale);doc.roundedRect(x,y,cw,9,4,4,'F');tx(doc,n,x+4,y+6.2,7.2,'bold',C.ink)});bottom(doc,p+1,pages)}
 doc.save(`Convocation_${V.clean(c.title||c.activity||'AS')}.pdf`);
};
function visibleLicenseRows(d){const names=[...document.querySelectorAll('.admin-table tbody tr td:first-child strong')].map(x=>x.textContent.trim()).filter(Boolean);return names.length?(d.licenses||[]).filter(l=>names.includes(l.fullName)):(d.licenses||[])}
function productName(d,id){return(d.products||[]).find(p=>p.id===id)?.name||'Produit'}
function student(d,id){return(d.students||[]).find(s=>s.id===id)||{}}
async function excelLogo(wb){try{const l=await logo();if(!l)return null;return wb.addImage({base64:l.split(',')[1]||l,extension:'png'})}catch{return null}}
function styleSheet(ws,title,subtitle,headers,rows,statusColumns=[]){const n=headers.length;ws.mergeCells(1,2,1,n);ws.getCell(1,2).value=title;ws.getCell(1,2).font={name:'Aptos Display',size:20,bold:true,color:{argb:'FFFFFFFF'}};ws.getCell(1,2).alignment={vertical:'middle'};ws.mergeCells(2,2,2,n);ws.getCell(2,2).value=subtitle;ws.getCell(2,2).font={name:'Aptos',size:10,color:{argb:'FFD8E4F4'}};for(let c=1;c<=n;c++){ws.getCell(1,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF10213F'}};ws.getCell(2,c).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF10213F'}}}ws.getRow(1).height=30;ws.getRow(2).height=22;const hr=ws.getRow(4);headers.forEach((h,i)=>{const cell=hr.getCell(i+1);cell.value=h;cell.font={name:'Aptos',size:10,bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0757C9'}};cell.alignment={vertical:'middle',horizontal:'left'};cell.border={bottom:{style:'medium',color:{argb:'FFFFD21A'}}}});hr.height=24;rows.forEach((r,ri)=>{const row=ws.getRow(5+ri);headers.forEach((h,i)=>{const cell=row.getCell(i+1);cell.value=r[i]??'';cell.font={name:'Aptos',size:10,color:{argb:'FF13213A'}};cell.alignment={vertical:'middle',wrapText:true};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:ri%2?'FFF7F9FC':'FFFFFFFF'}};cell.border={bottom:{style:'hair',color:{argb:'FFDCE5F0'}}};if(statusColumns.includes(i)){const v=String(r[i]||'').toLowerCase();if(v.includes('payé')||v==='oui'||v.includes('distribué')){cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE8F7EE'}};cell.font={name:'Aptos',size:10,bold:true,color:{argb:'FF146B39'}}}else if(v.includes('attente')||v==='non'||v.includes('à distribuer')){cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFEEF1'}};cell.font={name:'Aptos',size:10,bold:true,color:{argb:'FFB5233C'}}}}});row.height=22});headers.forEach((h,i)=>{let max=Math.max(12,h.length+2);rows.forEach(r=>max=Math.max(max,String(r[i]??'').length+2));ws.getColumn(i+1).width=Math.min(34,max)});ws.views=[{state:'frozen',ySplit:4}];ws.autoFilter={from:{row:4,column:1},to:{row:4,column:n}}}
async function saveBook(wb,name){const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
app.exportExcel=async kind=>{
 if(!window.ExcelJS)return alert('Module Excel indisponible.');const d=V.read(),wb=new ExcelJS.Workbook();wb.creator='Association Sportive du Bon Sauveur';wb.created=new Date();const img=await excelLogo(wb);let specs=[];
 if(kind==='licenses'){const ls=visibleLicenseRows(d);specs.push(['Licences','LICENCES AS','Association Sportive du Bon Sauveur — Saint-Lô',['Nom & prénom','Classe','Catégorie','Spécialité','Cotisation','Statut','Montant','Charte'],ls.map(l=>[l.fullName,l.className,l.category,l.sectionOption,l.contribution,l.paymentStatus,Number(l.amount||0),l.charterSigned]),[5]]);const paid=ls.filter(l=>l.paymentStatus==='Payé').reduce((s,l)=>s+Number(l.amount||0),0),wait=ls.filter(l=>l.paymentStatus!=='Payé').reduce((s,l)=>s+Number(l.amount||0),0);specs.push(['Synthèse','SYNTHÈSE LICENCES','Comptabilité de la sélection',['Indicateur','Valeur'],[['Licences',ls.length],['Encaissé',paid],['À encaisser',wait]],[]])}
 else if(kind==='reports')specs.push(['Bilans','BILANS AS','Suivi des activités et compétitions',['Date','Activité','Professeur référent','Niveau','Lieu','Catégorie','Nombre d’élèves','Commentaire'],(d.reports||[]).map(r=>[r.date,r.activity,r.teacher,r.level,r.place,r.category,r.participants,r.comment||'']),[]]);
 else if(kind==='orders')specs.push(['Commandes','COMMANDES BOUTIQUE','Suivi des paiements et distributions',['Élève','Classe','Produit','Taille','Qté','Paiement','Statut paiement','Distribution','Date'],(d.orders||[]).map(o=>[o.studentName,o.className,productName(d,o.productId),o.size,o.quantity||1,o.paymentMethod,o.paid?'Payé':'En attente',o.distributed?'Distribué':'À distribuer',o.createdAt]),[6,7]]);
 else if(kind==='appreciations')specs.push(['Appréciations','APPRÉCIATIONS','Suivi trimestriel',( ['Élève','Classe','Trimestre','Appréciation','Statut']),(d.appreciations||[]).map(a=>{const s=student(d,a.studentId);return[s.fullName||V.studentName(d,a.studentId),s.className||'',a.term,a.text||'',a.status==='validated'?'Validé':'Brouillon']}),[4]]);
 else if(kind==='convocations'){const rows=[];(d.convocations||[]).forEach(c=>(c.studentIds||[]).forEach(id=>rows.push([c.activity,c.title,c.ageCategory,c.specialty,c.date,c.place,c.departure,c.returnTime,c.meetingPoint,c.teacher||'',V.studentName(d,id)])));specs.push(['Convocations','CONVOCATIONS','Association Sportive du Bon Sauveur',['Activité','Titre','Catégorie','Spécialité','Date','Lieu','Départ','Retour','Rendez-vous','Professeur','Élève'],rows,[]])}
 else if(kind==='calendar')specs.push(['Calendrier','CALENDRIER AS','Rendez-vous sportifs',['Titre','Catégorie','Spécialité','Date','Départ','Retour','Lieu'],(d.events||[]).map(e=>[e.title,e.ageCategory,e.specialty,e.date,e.startTime,e.endTime,e.place]),[]]);
 else return;
 specs.forEach(([name,title,sub,headers,rows,status])=>{const ws=wb.addWorksheet(name);styleSheet(ws,title,sub,headers,rows,status);if(img!==null)try{ws.addImage(img,{tl:{col:0,row:0},ext:{width:52,height:52}})}catch{}});await saveBook(wb,`${kind==='licenses'?'Licences':kind==='reports'?'Bilans_AS':kind==='orders'?'Commandes_AS':kind==='appreciations'?'Appreciations_AS':kind==='convocations'?'Convocations_AS':'Calendrier_AS'}.xlsx`)
};
})();