(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const ED_LOGO='assets/logo-ecoledirecte.svg';
function route(){const h=document.querySelector('.page-title h1')?.textContent?.trim()||'';const k=document.querySelector('.page-title .kicker')?.textContent?.trim()||'';if(h==='À venir')return'calendar';if(h==='Convocations')return'convocations';if(h==='Bilans AS')return'reports';if(h==='Outils')return'more';if(h==='Licences')return'licenses';if(h==='Gestion des commandes')return'orders';if(h==='Appréciations')return'appreciations';if(h==='Documents')return'documents';if(h==='Boutique AS')return'shop';if(h==='Réglages'||k==='ADMINISTRATION')return'admin';return'home'}
function exactButtons(label){return [...document.querySelectorAll('button')].filter(b=>b.textContent.trim()===label)}
function removeOrderExportDuplicate(){if(route()!=='orders')return;const a=exactButtons('Exporter Excel');a.slice(1).forEach(b=>b.remove())}
function fixSchoolDirectLogo(){document.querySelectorAll('.v10-teacher button').forEach(b=>{let img=b.querySelector('img');if(!img){img=document.createElement('img');b.prepend(img)}if(img.getAttribute('src')!==ED_LOGO)img.setAttribute('src',ED_LOGO);img.alt='ÉcoleDirecte'})}
function statusColIndex(t){return[...t.querySelectorAll('thead th')].findIndex(th=>th.textContent.trim().toUpperCase()==='STATUT')}
function patchLicenseStatus(){if(route()!=='licenses')return;const d=V.read();document.querySelectorAll('.admin-table').forEach(t=>{const i=statusColIndex(t);if(i<0)return;t.querySelectorAll('tbody tr').forEach(row=>{const name=row.querySelector('td strong')?.textContent?.trim();if(!name)return;const l=(d.licenses||[]).find(x=>x.fullName===name);if(!l)return;const td=row.children[i];if(!td)return;let btn=td.querySelector('.v11-license-status');if(!btn){td.innerHTML='';btn=document.createElement('button');btn.type='button';btn.className='v11-license-status';td.appendChild(btn);btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const data=V.read(),lic=(data.licenses||[]).find(x=>x.id===l.id);if(!lic)return;lic.paymentStatus=lic.paymentStatus==='Payé'?'En attente':'Payé';V.write(data);app.go('licenses')})}const paid=l.paymentStatus==='Payé';btn.classList.toggle('paid',paid);btn.classList.toggle('pending',!paid);btn.innerHTML=`<span>${paid?'Payé':'En attente'}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 7h11l-3-3M17 17H6l3 3"/></svg>`})})}
function currentTerm(){const txt=document.querySelector('.term-tab.active')?.textContent||'Trimestre 1';const m=txt.match(/(\d+)/);return Number(m?.[1]||1)}
function openAppEditor(id,row){const ta=row.querySelector(`textarea[id="app-${CSS.escape(id)}"]`)||row.querySelector('.appreciation-text');if(!ta)return;const cells=row.querySelectorAll('td'),name=cells[0]?.querySelector('strong')?.textContent?.trim()||'Élève',cls=cells[0]?.querySelector('.meta')?.textContent?.trim()||'',prev=cells[1]?.textContent?.trim()||'—',term=currentTerm();const m=V.modal('Rédiger une appréciation',`<div class="v11-app-editor"><div class="v11-app-student"><div><span>Élève</span><strong>${V.esc(name)}</strong><small>${V.esc(cls)}</small></div><span class="v11-term-chip">Trimestre ${term}</span></div><div class="v11-prev"><span>Trimestre précédent</span><p>${V.esc(prev||'—')}</p></div><label class="v11-editor-field"><span>Appréciation</span><textarea id="v11-app-text" maxlength="900" placeholder="Rédiger l’appréciation…">${V.esc(ta.value||'')}</textarea><small><b id="v11-count">${(ta.value||'').length}</b> caractères</small></label><div class="v11-editor-actions"><button type="button" class="btn secondary" id="v11-draft">Enregistrer le brouillon</button><button type="button" class="btn" id="v11-validate">Vérifier & valider</button></div></div>`,true);const x=m.querySelector('#v11-app-text'),count=m.querySelector('#v11-count');x?.focus();x?.setSelectionRange(x.value.length,x.value.length);x?.addEventListener('input',()=>count.textContent=x.value.length);m.querySelector('#v11-draft')?.addEventListener('click',()=>{app.saveApp(id,term,x.value.trim(),'draft');document.getElementById('v7-modal')?.remove()});m.querySelector('#v11-validate')?.addEventListener('click',()=>{ta.value=x.value.trim();document.getElementById('v7-modal')?.remove();requestAnimationFrame(()=>app.validateApp(id,term))})}
function patchAppreciations(){if(route()!=='appreciations')return;document.querySelectorAll('.appreciation-table tbody tr').forEach(row=>{const ta=row.querySelector('.appreciation-text');if(!ta)return;const id=(ta.id||'').replace(/^app-/,'');if(!id||row.querySelector('.v11-app-write'))return;const btn=document.createElement('button');btn.type='button';btn.className='btn v11-app-write';btn.textContent=ta.value.trim()?'Modifier l’appréciation':'Rédiger';btn.addEventListener('click',e=>{e.preventDefault();openAppEditor(id,row)});const cell=row.lastElementChild||row.children[0];cell.appendChild(btn)})}
function fixNavOverlap(){document.querySelector('.bottom-nav')?.classList.add('v11-nav')}
function fixButtons(){document.querySelectorAll('.v10-event-actions,.v10-card-actions,.top-actions-inline,.v10-modal-actions').forEach(x=>x.classList.add('v11-actions'))}
function refresh(){removeOrderExportDuplicate();fixSchoolDirectLogo();patchLicenseStatus();patchAppreciations();fixNavOverlap();fixButtons()}
const oldOpen=app.openConv?.bind(app);if(oldOpen&&!app.__v11OpenConv){app.openConv=function(...args){const r=oldOpen(...args);requestAnimationFrame(()=>{fixSchoolDirectLogo();document.querySelector('.v7-modal')?.scrollTo?.({top:0})});return r};app.__v11OpenConv=true}
if(!app.__v11Wrapped){['go','setRole','theme','search','licenseFilter','clearLicenseFilters','setTerm'].forEach(k=>{const fn=app[k];if(typeof fn!=='function')return;app[k]=function(...args){const r=fn.apply(this,args);requestAnimationFrame(refresh);return r}});app.__v11Wrapped=true}
let scheduled=false;const root=document.getElementById('app');if(root&&window.MutationObserver)new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;refresh()})}).observe(root,{childList:true,subtree:true});
refresh();window.ASV11={refresh,version:'v11-20260908-1'};
})();