(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
function route(){const h=document.querySelector('.page-title h1')?.textContent?.trim()||'';if(h==='Gestion des commandes')return'orders';if(h==='Appréciations')return'appreciations';return''}
function dedupeExport(){const r=route();if(!['orders','appreciations'].includes(r))return;const a=[...document.querySelectorAll('button')].filter(b=>b.textContent.trim()==='Exporter Excel');a.slice(1).forEach(b=>b.remove())}
function orderForRow(row,d){const cells=row.querySelectorAll('td');const name=cells[0]?.textContent?.trim()||'';const product=cells[2]?.textContent?.trim()||'';return(d.orders||[]).find(o=>o.studentName===name&&((d.products||[]).find(p=>p.id===o.productId)?.name||'Produit')===product)||(d.orders||[]).find(o=>o.studentName===name)}
function statusButton(value,kind,id){const paid=!!value;const label=kind==='paid'?(paid?'Payé':'En attente'):(paid?'Distribué':'À distribuer');return `<button type="button" class="v12-order-status ${paid?'on':'off'}" data-order="${id}" data-kind="${kind}"><span>${label}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 9 4-4 4 4M16 15l-4 4-4-4"/></svg></button>`}
function patchOrders(){if(route()!=='orders')return;const d=V.read();document.querySelectorAll('.admin-table').forEach(t=>{const heads=[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim().toLowerCase()),pi=heads.findIndex(x=>x==='payé'||x==='statut paiement'),di=heads.findIndex(x=>x==='distribué'||x==='distribution');if(pi<0||di<0)return;t.querySelectorAll('tbody tr').forEach(row=>{const o=orderForRow(row,d);if(!o)return;[[pi,'paid',o.paid],[di,'distributed',o.distributed]].forEach(([i,k,val])=>{const td=row.children[i];if(!td)return;const sig=`${o.id}|${k}|${val?'1':'0'}`;if(td.dataset.v12Status===sig)return;td.innerHTML=statusButton(val,k,o.id);td.dataset.v12Status=sig;td.querySelector('button').onclick=e=>{e.preventDefault();e.stopPropagation();app.toggleOrder(o.id,k);requestAnimationFrame(()=>{dedupeExport();patchOrders()})}})})})}
function appreciationText(row){const ta=row.querySelector('.appreciation-text');return ta?.value?.trim()||''}
async function copyText(text,btn){if(!text)return;try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const old=btn.innerHTML;btn.innerHTML='<span>Copié ✓</span>';btn.classList.add('copied');setTimeout(()=>{btn.innerHTML=old;btn.classList.remove('copied')},1400)}
function patchAppreciations(){if(route()!=='appreciations')return;document.querySelectorAll('.appreciation-table tbody tr').forEach(row=>{const ta=row.querySelector('.appreciation-text');if(!ta)return;const last=row.lastElementChild;if(!last)return;let group=last.querySelector('.v12-app-actions');if(!group){group=document.createElement('div');group.className='v12-app-actions';const write=row.querySelector('.v11-app-write');if(write)group.appendChild(write);const copy=document.createElement('button');copy.type='button';copy.className='btn secondary v12-copy-app';copy.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg><span>Copier</span>';copy.onclick=e=>{e.preventDefault();e.stopPropagation();copyText(appreciationText(row),copy)};group.appendChild(copy);last.appendChild(group)}const cp=group.querySelector('.v12-copy-app'),has=!!appreciationText(row);cp.disabled=!has;cp.title=has?'Copier l’appréciation':'Aucune appréciation à copier'})}
function refresh(){dedupeExport();patchOrders();patchAppreciations()}
if(!app.__v12Wrapped){['go','setRole','search','licenseFilter','clearLicenseFilters','setTerm','saveApp','validateApp','toggleOrder'].forEach(k=>{const fn=app[k];if(typeof fn!=='function')return;app[k]=function(...args){const r=fn.apply(this,args);requestAnimationFrame(refresh);return r}});app.__v12Wrapped=true}
let scheduled=false;const root=document.getElementById('app');if(root&&window.MutationObserver)new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;refresh()})}).observe(root,{childList:true,subtree:true});
refresh();window.ASV12={refresh,version:'v12-20260908-1'};
})();