(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const C={blue:[12,91,205],blue2:[25,124,232],navy:[17,55,126],yellow:[255,211,27],ink:[24,43,84],muted:[102,121,155],line:[217,229,244],paper:[252,253,255],white:[255,255,255],purple:[128,69,214],gold:[229,176,0],paleBlue:[234,245,255],palePurple:[246,238,255],paleYellow:[255,248,214]};
const accent=s=>s==='Section Football'?C.blue2:s==='Option Escalade'?C.purple:s==='Sport-études Gymnastique'?C.purple:C.gold;
const safe=v=>String(v??'');
function font(doc,size=10,style='normal',color=C.ink){doc.setFont('helvetica',style);doc.setFontSize(size);doc.setTextColor(...color)}
function tx(doc,t,x,y,size=10,style='normal',color=C.ink,opts={}){font(doc,size,style,color);doc.text(Array.isArray(t)?t:safe(t),x,y,opts)}
function wrap(doc,t,w,size=10,max=2){font(doc,size);return doc.splitTextToSize(safe(t),w).slice(0,max)}
function round(doc,x,y,w,h,fill=C.white,stroke=C.line,r=5){doc.setFillColor(...fill);doc.setDrawColor(...stroke);doc.roundedRect(x,y,w,h,r,r,'FD')}
function brush(doc,x,y,w,color,thick=2.8,dir=1){doc.setDrawColor(...color);doc.setLineCap('round');const ys=[0,2.1,-1.7,3.7,-3.1];const cuts=[0,7,3,11,5];ys.forEach((dy,i)=>{doc.setLineWidth(Math.max(.7,thick-(i*.35)));const x1=x+cuts[i],x2=x+w-(i*3);doc.line(x1,y+dy,x2,y+dy+dir*(i%2?1.2:-.8))});doc.setLineCap('butt')}
function dots(doc,x,y,color,cols=6,rows=3,step=4){doc.setFillColor(...color);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const rad=.35+(c%3)*.08;doc.circle(x+c*step,y+r*step,rad,'F')}}
function chip(doc,label,x,y,w,color,fill=null){doc.setFillColor(...(fill||color));doc.roundedRect(x,y,w,7.5,3.8,3.8,'F');tx(doc,label,x+w/2,y+5.1,6.4,'bold',fill?color:C.white,{align:'center'})}
async function logo(){try{return await V.logoData()}catch{return null}}
function headerArt(doc,lg,title,sub,right=''){
 doc.setFillColor(...C.paper);doc.rect(0,0,297,210,'F');
 brush(doc,7,10,67,C.yellow,3.4,1);brush(doc,225,10,66,C.blue2,3.2,-1);brush(doc,221,22,60,C.yellow,2.2,1);dots(doc,5,3,[186,219,250],8,4,3.6);dots(doc,272,2,[186,219,250],6,4,3.6);
 if(lg)try{doc.addImage(lg,'PNG',10,8,31,31)}catch{}
 tx(doc,title.toUpperCase(),52,22,24,'bolditalic',C.navy);if(doc.setCharSpace)doc.setCharSpace(0);
 brush(doc,50,27,94,C.yellow,3.2,1);tx(doc,sub,56,30,9.2,'bolditalic',C.navy);
 if(right){doc.setFillColor(...C.paleBlue);doc.roundedRect(213,31,72,9,4.5,4.5,'F');tx(doc,right,249,37,7.2,'bold',C.navy,{align:'center'})}
}
function footerArt(doc,page,total){brush(doc,0,203,91,C.blue2,2.7,1);brush(doc,14,207,103,C.yellow,2.4,-1);brush(doc,206,204,91,C.blue2,2.7,-1);dots(doc,3,194,[183,218,249],9,2,3.5);tx(doc,'ASSOCIATION SPORTIVE DU BON SAUVEUR',12,196,6.2,'bold',C.navy);tx(doc,'Saint-Lô',112,203,13,'bolditalic',C.navy);tx(doc,`${page}/${total}`,285,203,6.2,'bold',C.muted,{align:'right'})}
function dateRange(events){if(!events.length)return'';const a=V.fmtShort(events[0].date),b=V.fmtShort(events[events.length-1].date);return a===b?a:`${a} → ${b}`}
function iconClock(doc,x,y,color){doc.setDrawColor(...color);doc.setLineWidth(1.4);doc.circle(x,y,3.1,'S');doc.line(x,y,x,y-1.7);doc.line(x,y,x+1.5,y+.8)}
function iconPin(doc,x,y,color){doc.setDrawColor(...color);doc.setLineWidth(1.2);doc.circle(x,y-1,2.2,'S');doc.line(x-1.4,y+.5,x,y+3);doc.line(x+1.4,y+.5,x,y+3);doc.circle(x,y-1,.55,'F')}
function iconPeople(doc,x,y,color){doc.setFillColor(...color);doc.circle(x-1.7,y-1.2,1.1,'F');doc.circle(x+1.7,y-1.2,1.1,'F');doc.roundedRect(x-3.3,y+.2,3,2.3,1,1,'F');doc.roundedRect(x+.3,y+.2,3,2.3,1,1,'F')}
function sportMark(doc,s,x,y,w,h,a){doc.setDrawColor(...a);doc.setLineWidth(2.4);if(s==='Section Football'){doc.circle(x+w*.58,y+h*.42,5,'S');for(let i=0;i<5;i++)doc.line(x+w*.58,y+h*.42,x+w*(.58+Math.cos(i*1.256)*.055),y+h*(.42+Math.sin(i*1.256)*.10));brush(doc,x+w*.3,y+h*.7,w*.58,a,1.8,-1)}else if(s==='Option Escalade'){doc.line(x+w*.45,y+h*.8,x+w*.62,y+h*.28);doc.line(x+w*.62,y+h*.28,x+w*.75,y+h*.55);doc.circle(x+w*.56,y+h*.46,1.4,'F');brush(doc,x+w*.3,y+h*.74,w*.5,a,1.5,1)}else if(s==='Sport-études Gymnastique'){doc.circle(x+w*.59,y+h*.36,1.5,'F');doc.line(x+w*.59,y+h*.38,x+w*.51,y+h*.55);doc.line(x+w*.51,y+h*.55,x+w*.63,y+h*.68);doc.line(x+w*.54,y+h*.48,x+w*.72,y+h*.42);brush(doc,x+w*.35,y+h*.76,w*.45,a,1.5,-1)}else{doc.circle(x+w*.58,y+h*.43,2.8,'S');doc.line(x+w*.5,y+h*.57,x+w*.68,y+h*.3);brush(doc,x+w*.34,y+h*.76,w*.48,a,1.5,1)}}
function eventCard(doc,e,x,y,w,h,hasConv,wide=false){const a=accent(e.specialty),d=new Date(e.date+'T12:00:00'),day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();round(doc,x,y,w,h,C.white,C.line,5.5);doc.setFillColor(...a);doc.roundedRect(x,y,5,h,2.5,2.5,'F');brush(doc,x+w*.68,y+8,w*.24,a,1.2,-1);sportMark(doc,e.specialty,x+w*.64,y+6,w*.31,h-12,a);doc.setFillColor(...a);doc.roundedRect(x+9,y+8,27,31,6,6,'F');tx(doc,day,x+22.5,y+23,18,'bold',C.white,{align:'center'});tx(doc,mon,x+22.5,y+32,6.5,'bold',C.white,{align:'center'});const titleX=x+43,titleW=w*(wide?.48:.46),lines=wrap(doc,e.title,titleW,wide?12.2:10.7,2);tx(doc,lines,titleX,y+14,wide?12.2:10.7,'bold',C.ink);const spec=safe(e.specialty||'Association Sportive'),pw=Math.min(wide?54:47,Math.max(25,spec.length*1.85));chip(doc,spec,titleX,y+29,pw,a,e.specialty==='Association Sportive'?C.paleYellow:e.specialty==='Section Football'?C.paleBlue:C.palePurple);iconClock(doc,titleX+2,y+h-16,a);tx(doc,`${e.startTime||'—'} → ${e.endTime||'—'}`,titleX+9,y+h-13.5,7.8,'bold',C.ink);iconPin(doc,titleX+2,y+h-7,a);tx(doc,e.place||'—',titleX+9,y+h-4.5,6.8,'normal',C.ink);iconPeople(doc,x+w-38,y+h-7,a);tx(doc,e.ageCategory||'Toutes catégories',x+w-32,y+h-4.5,6.4,'bold',C.ink);if(hasConv){chip(doc,'CONVOCATION',x+w-33,y+7,27,C.blue2)}}
app.exportCalendarPDF=async()=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),sp=V.edu();const events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');const lg=await logo(),per=5,pages=Math.ceil(events.length/per),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});for(let p=0;p<pages;p++){if(p)doc.addPage('a4','landscape');const ch=events.slice(p*per,p*per+per);headerArt(doc,lg,'Calendrier AS','Rendez-vous à venir',dateRange(ch));const topY=51,g=6;if(ch.length<=2){const w=(273-g)/2;ch.forEach((e,i)=>eventCard(doc,e,12+i*(w+g),topY,w,110,(d.convocations||[]).some(c=>c.id===e.convocationId),true))}else{const w3=(273-2*g)/3,h1=58;ch.slice(0,3).forEach((e,i)=>eventCard(doc,e,12+i*(w3+g),topY,w3,h1,(d.convocations||[]).some(c=>c.id===e.convocationId)));const rest=ch.slice(3),w2=(273-g)/2,y2=topY+h1+g;rest.forEach((e,i)=>eventCard(doc,e,12+i*(w2+g),y2,w2,62,(d.convocations||[]).some(c=>c.id===e.convocationId),true))}footerArt(doc,p+1,pages)}doc.save(sp?`Calendrier_${V.clean(sp)}.pdf`:'Calendrier_AS_Bon_Sauveur.pdf')};
function infoLine(doc,label,value,x,y,w,icon='pin'){const color=C.blue;tx(doc,label.toUpperCase(),x+9,y+4,5.6,'bold',C.blue);if(icon==='clock')iconClock(doc,x+3,y+1.8,color);else if(icon==='people')iconPeople(doc,x+3,y+1.8,color);else iconPin(doc,x+3,y+1.8,color);const lines=wrap(doc,value,w-10,9.2,2);tx(doc,lines,x+9,y+12,9.2,'bold',C.ink);doc.setDrawColor(...C.line);doc.setLineWidth(.7);doc.line(x+9,y+18,x+w,y+18)}
function dateSplash(doc,c,x,y,a){const d=new Date(c.date+'T12:00:00'),wd=d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),day=String(d.getDate()).padStart(2,'0'),mo=d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase();brush(doc,x,y,49,a,4.1,1);tx(doc,wd,x+3,y-5,6.3,'bold',C.navy);tx(doc,day,x+5,y+18,28,'bolditalic',a);tx(doc,mo,x+5,y+27,7.2,'bold',C.navy);tx(doc,String(d.getFullYear()),x+5,y+34,6.2,'bold',C.muted)}
function students(doc,names,x,y,w){tx(doc,'ÉLÈVES CONVOQUÉS',x,y,6.6,'bold',C.blue);iconPeople(doc,x-4,y-1,C.blue);let cx=x,cy=y+6;names.slice(0,16).forEach(n=>{const ww=Math.max(29,Math.min(53,10+n.length*1.7));if(cx+ww>x+w){cx=x;cy+=9}doc.setFillColor(...C.paleBlue);doc.roundedRect(cx,cy,ww,7,3.5,3.5,'F');tx(doc,n,cx+ww/2,cy+4.8,6.4,'bold',C.navy,{align:'center'});cx+=ww+4})}
app.exportConvocation=async id=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),lg=await logo(),a=accent(c.specialty),rest=names.slice(16),pages=1+Math.ceil(rest.length/32),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});headerArt(doc,lg,'Convocation',c.specialty||'Association Sportive',V.fmtShort(c.date));dateSplash(doc,c,14,64,a);brush(doc,75,57,197,C.blue2,2.2,-1);tx(doc,(c.activity||'ACTIVITÉ').toUpperCase(),79,54,6.5,'bold',C.blue);const title=wrap(doc,c.title||c.activity,150,19,2);tx(doc,title,79,68,19,'bolditalic',C.navy);chip(doc,c.specialty||'Association Sportive',79,80,55,a,C.paleBlue);chip(doc,c.ageCategory||'Toutes catégories',139,80,42,C.blue2,C.paleBlue);brush(doc,205,65,71,C.yellow,2.5,1);dots(doc,250,47,[191,219,249],8,4,3.6);infoLine(doc,'Lieu',c.place||'—',79,99,44,'pin');infoLine(doc,'Départ',c.departure||'—',128,99,40,'clock');infoLine(doc,'Retour',c.returnTime||'—',173,99,40,'clock');infoLine(doc,'Point de rendez-vous',c.meetingPoint||'—',218,99,67,'people');infoLine(doc,'Professeur référent',c.teacher||'À renseigner',79,127,78,'people');doc.setFillColor(...C.paleYellow);doc.roundedRect(165,121,120,31,5,5,'F');brush(doc,168,128,38,C.yellow,2.3,1);tx(doc,'INFORMATIONS IMPORTANTES',172,130,6.1,'bold',C.blue);tx(doc,wrap(doc,c.extraInfo||'Aucune information particulière.',104,10.2,2),172,141,10.2,'bold',C.ink);students(doc,names,79,166,206);sportMark(doc,c.specialty,226,150,56,35,a);footerArt(doc,1,pages);for(let p=1;p<pages;p++){doc.addPage('a4','landscape');headerArt(doc,lg,'Convocation',c.title||c.activity||'',V.fmtShort(c.date));tx(doc,'ÉLÈVES CONVOQUÉS — SUITE',18,55,10,'bolditalic',C.navy);brush(doc,16,59,91,C.yellow,2.5,1);const chunk=rest.slice((p-1)*32,p*32);students(doc,chunk,18,72,260);footerArt(doc,p+1,pages)}doc.save(`Convocation_${V.clean(c.title||c.activity||'AS')}.pdf`)};
window.ASV12Exports={version:'v12-20260908-1'};
})();