(()=>{
'use strict';
const V=window.ASV7, app=window.app;
if(!V||!app)return;
const C={blue:[18,99,214],blue2:[59,132,232],navy:[19,52,112],yellow:[255,210,35],ink:[23,44,83],muted:[101,120,151],line:[215,228,244],paper:[252,254,255],white:[255,255,255],purple:[126,72,210],gold:[225,177,16],paleBlue:[236,246,255],palePurple:[247,240,255],paleYellow:[255,249,219]};
const safe=v=>String(v??'');
const accent=s=>s==='Section Football'?C.blue2:(s==='Option Escalade'||s==='Sport-études Gymnastique')?C.purple:C.gold;
const pale=s=>s==='Section Football'?C.paleBlue:(s==='Option Escalade'||s==='Sport-études Gymnastique')?C.palePurple:C.paleYellow;
function font(doc,size=10,style='normal',color=C.ink){doc.setFont('helvetica',style);doc.setFontSize(size);doc.setTextColor(...color)}
function tx(doc,text,x,y,size=10,style='normal',color=C.ink,opts={}){font(doc,size,style,color);doc.text(Array.isArray(text)?text:safe(text),x,y,opts)}
function wrap(doc,text,w,size=10,max=2,style='normal'){font(doc,size,style);return doc.splitTextToSize(safe(text),w).slice(0,max)}
function round(doc,x,y,w,h,fill=C.white,stroke=C.line,r=5){doc.setFillColor(...fill);doc.setDrawColor(...stroke);doc.setLineWidth(.65);doc.roundedRect(x,y,w,h,r,r,'FD')}
function line(doc,x1,y1,x2,y2,color=C.line,width=.6){doc.setDrawColor(...color);doc.setLineWidth(width);doc.line(x1,y1,x2,y2)}
function brush(doc,x,y,w,color,thick=2.8,dir=1){doc.setDrawColor(...color);doc.setLineCap('round');[[0,0],[2.1,5],[-1.6,2],[3.4,9],[-2.8,4]].forEach(([dy,cut],i)=>{doc.setLineWidth(Math.max(.65,thick-i*.34));doc.line(x+cut,y+dy,x+w-i*3,y+dy+dir*(i%2?1:-.7))});doc.setLineCap('butt')}
function dots(doc,x,y,color,cols=6,rows=3,step=3.8){doc.setFillColor(...color);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)doc.circle(x+c*step,y+r*step,.32+(c%2)*.08,'F')}
function chip(doc,label,x,y,w,color,fill){doc.setFillColor(...(fill||color));doc.roundedRect(x,y,w,7.5,3.8,3.8,'F');tx(doc,label,x+w/2,y+5.1,6.1,'bold',fill?color:C.white,{align:'center'})}
async function logo(){try{return await V.logoData()}catch{return null}}
function iconClock(doc,x,y,color){doc.setDrawColor(...color);doc.setLineWidth(1.2);doc.circle(x,y,2.8,'S');doc.line(x,y,x,y-1.5);doc.line(x,y,x+1.3,y+.7)}
function iconPin(doc,x,y,color){doc.setDrawColor(...color);doc.setLineWidth(1.05);doc.circle(x,y-1,1.9,'S');doc.line(x-1.2,y+.2,x,y+2.5);doc.line(x+1.2,y+.2,x,y+2.5);doc.circle(x,y-1,.42,'F')}
function iconPeople(doc,x,y,color){doc.setFillColor(...color);doc.circle(x-1.45,y-1.05,.95,'F');doc.circle(x+1.45,y-1.05,.95,'F');doc.roundedRect(x-2.9,y+.15,2.7,2.1,.8,.8,'F');doc.roundedRect(x+.2,y+.15,2.7,2.1,.8,.8,'F')}
function header(doc,lg,title,sub,right=''){doc.setFillColor(...C.paper);doc.rect(0,0,297,210,'F');dots(doc,4,3,[205,229,250],8,3,3.5);dots(doc,274,3,[205,229,250],6,3,3.5);brush(doc,6,10,61,C.yellow,3.2,1);brush(doc,229,11,58,C.blue2,3,-1);brush(doc,224,23,54,C.yellow,2.1,1);if(lg)try{doc.addImage(lg,'PNG',10,7,28,28)}catch{}tx(doc,title.toUpperCase(),48,19.5,22,'bolditalic',C.blue);brush(doc,47,25.5,94,C.yellow,3,1);tx(doc,sub,53,30,8.8,'bolditalic',C.ink);if(right){doc.setFillColor(...C.paleBlue);doc.roundedRect(214,30.5,71,9.5,4.7,4.7,'F');tx(doc,right,249.5,36.8,6.9,'bold',C.blue,{align:'center'})}}
function footer(doc,page,total){line(doc,12,194,285,194,C.line,.6);brush(doc,0,202,82,C.blue2,2.4,1);brush(doc,12,206,96,C.yellow,2.15,-1);brush(doc,220,203,77,C.blue2,2.35,-1);tx(doc,'ASSOCIATION SPORTIVE DU BON SAUVEUR',12,190,6,'bold',C.blue);tx(doc,'Saint-Lô',112,203,12.5,'bolditalic',C.blue);tx(doc,`${page}/${total}`,285,190,6,'bold',C.muted,{align:'right'})}
function dateRange(events){if(!events.length)return'';const a=V.fmtShort(events[0].date),b=V.fmtShort(events[events.length-1].date);return a===b?a:`${a} → ${b}`}
function hasConv(d,e){return (d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&(!e.title||c.title===e.title)))}
function sportWatermark(doc,s,x,y,w,h,a){const px=x+w-28,py=y+h/2;doc.setDrawColor(...a);doc.setLineWidth(1.7);if(s==='Section Football'){doc.circle(px,py,11,'S');doc.circle(px,py,3.5,'S');for(let i=0;i<6;i++){const ang=i*Math.PI/3;doc.line(px+3.5*Math.cos(ang),py+3.5*Math.sin(ang),px+10.4*Math.cos(ang),py+10.4*Math.sin(ang))}brush(doc,x+w-54,y+h-17,39,a,1.3,-1)}else if(s==='Option Escalade'){doc.line(px-12,py+12,px-3,py-13);doc.line(px-3,py-13,px+12,py+8);doc.circle(px-2,py-4,1.4,'F');doc.line(px-2,py-2,px-9,py+5);doc.line(px-2,py-2,px+6,py+4);brush(doc,x+w-50,y+h-16,35,a,1.2,1)}else if(s==='Sport-études Gymnastique'){doc.circle(px,py-9,1.5,'F');doc.line(px,py-7,px-8,py+1);doc.line(px-8,py+1,px+3,py+9);doc.line(px-5,py-1,px+10,py-5);doc.line(px+3,py+9,px+11,py+2);brush(doc,x+w-49,y+h-16,33,a,1.2,-1)}else{doc.circle(px-4,py-3,3,'S');doc.circle(px+6,py+5,2.4,'S');doc.line(px-12,py+10,px+11,py-10);brush(doc,x+w-50,y+h-16,35,a,1.2,1)}}
function infoSegment(doc,label,value,x,y,w,icon,a){if(icon==='clock')iconClock(doc,x+2.5,y+3,a);else if(icon==='pin')iconPin(doc,x+2.5,y+3,a);else iconPeople(doc,x+2.5,y+3,a);tx(doc,label.toUpperCase(),x+8,y+2.4,4.8,'bold',C.muted);tx(doc,wrap(doc,value,w-9,6.9,1,'bold'),x+8,y+8.5,6.9,'bold',C.ink)}
function eventCard(doc,e,x,y,w,h,hasConvocation){const a=accent(e.specialty),p=pale(e.specialty),d=new Date(e.date+'T12:00:00'),day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();round(doc,x,y,w,h,C.white,C.line,6);doc.setFillColor(...a);doc.roundedRect(x,y,4,h,2,2,'F');doc.setFillColor(...a);doc.roundedRect(x+9,y+9,26,31,6,6,'F');tx(doc,day,x+22,y+23,17,'bold',C.white,{align:'center'});tx(doc,mon,x+22,y+32,6,'bold',C.white,{align:'center'});const cx=x+42,titleW=Math.max(45,w-78),titleSize=w>125?12.4:10.1;tx(doc,wrap(doc,e.title,titleW,titleSize,2,'bold'),cx,y+15,titleSize,'bold',C.ink);const spec=safe(e.specialty||'Association Sportive'),cw=Math.min(w>125?54:44,Math.max(24,spec.length*1.55));chip(doc,spec,cx,y+30,cw,a,p);if(hasConvocation)chip(doc,'CONVOCATION',x+w-32,y+8,27,C.blue2,C.paleBlue);sportWatermark(doc,e.specialty,x,y,w,h,a);const bandY=y+h-22;line(doc,cx,bandY-4,x+w-8,bandY-4,C.line,.55);const avail=w-49,seg=avail/3;infoSegment(doc,'Horaire',`${e.startTime||'—'} → ${e.endTime||'—'}`,cx,bandY,seg,'clock',a);infoSegment(doc,'Lieu',e.place||'—',cx+seg,bandY,seg,'pin',a);infoSegment(doc,'Catégorie',e.ageCategory||'Toutes catégories',cx+seg*2,bandY,seg,'people',a)}
app.exportCalendarPDF=async()=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),sp=V.edu();const events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');const lg=await logo(),per=6,pages=Math.ceil(events.length/per),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});for(let p=0;p<pages;p++){if(p)doc.addPage('a4','landscape');const ch=events.slice(p*per,p*per+per);header(doc,lg,'Calendrier AS',sp||'Rendez-vous à venir',dateRange(ch));const n=ch.length,left=12,top=51,gap=6,W=273;if(n===1){eventCard(doc,ch[0],left,top,W,104,hasConv(d,ch[0]))}else if(n===2){const w=(W-gap)/2;ch.forEach((e,i)=>eventCard(doc,e,left+i*(w+gap),top,w,104,hasConv(d,e)))}else if(n===3){const w=(W-gap*2)/3;ch.forEach((e,i)=>eventCard(doc,e,left+i*(w+gap),top,w,104,hasConv(d,e)))}else if(n===4){const w=(W-gap)/2,h=60;ch.forEach((e,i)=>eventCard(doc,e,left+(i%2)*(w+gap),top+Math.floor(i/2)*(h+gap),w,h,hasConv(d,e)))}else{const w3=(W-gap*2)/3,h=59;ch.slice(0,3).forEach((e,i)=>eventCard(doc,e,left+i*(w3+gap),top,w3,h,hasConv(d,e)));const rest=ch.slice(3),y2=top+h+gap,w2=(W-gap)/2;rest.forEach((e,i)=>eventCard(doc,e,left+i*(w2+gap),y2,w2,67,hasConv(d,e)))}footer(doc,p+1,pages)}doc.save(sp?`Calendrier_${V.clean(sp)}.pdf`:'Calendrier_AS_Bon_Sauveur.pdf')};
function infoBox(doc,label,value,x,y,w,icon,a){round(doc,x,y,w,24,C.white,C.line,4.5);if(icon==='clock')iconClock(doc,x+7,y+8,a);else if(icon==='people')iconPeople(doc,x+7,y+8,a);else iconPin(doc,x+7,y+8,a);tx(doc,label.toUpperCase(),x+13,y+7,5.3,'bold',C.blue);tx(doc,wrap(doc,value,w-17,8.7,2,'bold'),x+13,y+15,8.7,'bold',C.ink)}
function dateHero(doc,c,x,y,a){const d=new Date(c.date+'T12:00:00'),wd=d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),day=String(d.getDate()).padStart(2,'0'),mo=d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase();doc.setFillColor(...a);doc.roundedRect(x,y,46,50,8,8,'F');tx(doc,wd,x+23,y+9,6.1,'bold',C.white,{align:'center'});tx(doc,day,x+23,y+29,25,'bolditalic',C.white,{align:'center'});tx(doc,mo,x+23,y+40,6.3,'bold',C.white,{align:'center'});tx(doc,String(d.getFullYear()),x+23,y+46,5.3,'bold',C.white,{align:'center'})}
function convHero(doc,c,x,y,w,h,a){round(doc,x,y,w,h,C.paleBlue,C.line,6);brush(doc,x+8,y+8,94,C.yellow,2.4,1);tx(doc,(c.activity||'ACTIVITÉ').toUpperCase(),x+9,y+13,6.1,'bold',C.blue);tx(doc,wrap(doc,c.title||c.activity,w-88,18.5,2,'bolditalic'),x+9,y+28,18.5,'bolditalic',C.blue);chip(doc,c.specialty||'Association Sportive',x+9,y+37,54,a,pale(c.specialty));chip(doc,c.ageCategory||'Toutes catégories',x+69,y+37,43,C.blue2,C.paleBlue);sportWatermark(doc,c.specialty,x+w-72,y+3,68,h-6,a)}
function students(doc,names,x,y,w){round(doc,x,y,w,29,C.white,C.line,5);iconPeople(doc,x+8,y+9,C.blue);tx(doc,'ÉLÈVES CONVOQUÉS',x+15,y+8,6.4,'bold',C.blue);let cx=x+15,cy=y+14;names.slice(0,18).forEach(n=>{const ww=Math.max(29,Math.min(50,10+n.length*1.55));if(cx+ww>x+w-5){cx=x+15;cy+=8}doc.setFillColor(...C.paleBlue);doc.roundedRect(cx,cy,ww,6.8,3.4,3.4,'F');tx(doc,n,cx+ww/2,cy+4.6,6.2,'bold',C.ink,{align:'center'});cx+=ww+4})}
app.exportConvocation=async id=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),lg=await logo(),a=accent(c.specialty),pages=1+Math.max(0,Math.ceil((names.length-18)/32)),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});header(doc,lg,'Convocation',c.specialty||'Association Sportive',V.fmtShort(c.date));dateHero(doc,c,12,49,a);convHero(doc,c,64,49,221,50,a);infoBox(doc,'Lieu',c.place||'—',12,106,61,'pin',a);infoBox(doc,'Départ',c.departure||'—',78,106,46,'clock',a);infoBox(doc,'Retour',c.returnTime||'—',129,106,46,'clock',a);infoBox(doc,'Point de rendez-vous',c.meetingPoint||'—',180,106,105,'people',a);infoBox(doc,'Professeur référent',c.teacher||'À renseigner',12,136,82,'people',a);round(doc,99,136,186,24,C.paleYellow,[255,224,114],4.5);brush(doc,105,142,46,C.yellow,1.7,1);tx(doc,'INFORMATIONS IMPORTANTES',105,144,5.6,'bold',C.blue);tx(doc,wrap(doc,c.extraInfo||'Aucune information particulière.',170,9.3,2,'bold'),105,153,9.3,'bold',C.ink);students(doc,names,12,167,273);footer(doc,1,pages);const rest=names.slice(18);for(let p=1;p<pages;p++){doc.addPage('a4','landscape');header(doc,lg,'Convocation',c.title||c.activity||'',V.fmtShort(c.date));tx(doc,'ÉLÈVES CONVOQUÉS — SUITE',18,56,11,'bolditalic',C.blue);brush(doc,17,61,90,C.yellow,2.4,1);students(doc,rest.slice((p-1)*32,p*32),18,72,261);footer(doc,p+1,pages)}doc.save(`Convocation_${V.clean(c.title||c.activity||'AS')}_${c.date||''}.pdf`)};
window.ASV14={version:'v14-20260908-1'};
})();