(()=>{
'use strict';
const V=window.ASV7, app=window.app;
if(!V||!app) return;

const C={blue:'#0757C9',blue2:'#0D63D9',navy:'#12254B',yellow:'#FFD51C',ink:'#101E3A',muted:'#6D7890',line:'#DCE5F2',panel:'#FAFCFF',purple:'#8248D4',purpleLite:'#F0E8FF',blueLite:'#EAF4FF',yellowLite:'#FFF7CF',white:'#FFFFFF'};
const safe=v=>String(v??'');
const specialtyColor=s=>s==='Section Football'?C.blue2:(s==='Option Escalade'||s==='Sport-études Gymnastique')?C.purple:C.yellow;
const specialtyLite=s=>s==='Section Football'?C.blueLite:(s==='Option Escalade'||s==='Sport-études Gymnastique')?C.purpleLite:C.yellowLite;
const FONT_DISPLAY='Impact, "Arial Narrow", "Avenir Next Condensed", sans-serif';
const FONT_COND='"Avenir Next Condensed", "Arial Narrow", "Roboto Condensed", Arial, sans-serif';
const FONT_BODY='"Avenir Next", Arial, sans-serif';

function rr(ctx,x,y,w,h,r,fill,stroke,line=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke()}}
function brush(ctx,x,y,w,color,th=7){ctx.save();ctx.strokeStyle=color;ctx.lineCap='round';for(let i=0;i<5;i++){ctx.globalAlpha=.96-i*.12;ctx.lineWidth=Math.max(2,th-i);ctx.beginPath();ctx.moveTo(x+(i%2?8:0),y+i*4);ctx.lineTo(x+w-i*10,y+(i%2?2:-2)+i*4);ctx.stroke()}ctx.restore()}
function dots(ctx,x,y,color,cols=4,rows=4,gap=11,r=2.5){ctx.save();ctx.fillStyle=color;ctx.globalAlpha=.45;for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){ctx.beginPath();ctx.arc(x+i*gap,y+j*gap,r,0,Math.PI*2);ctx.fill()}ctx.restore()}
function text(ctx,t,x,y,size,weight=700,color=C.ink,align='left',family=FONT_BODY,italic=false){ctx.save();ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.font=`${italic?'italic ':''}${weight} ${size}px ${family}`;ctx.fillText(safe(t),x,y);ctx.restore()}
function fitText(ctx,t,x,y,maxW,size,weight=800,color=C.ink,family=FONT_COND,min=16){let s=size;ctx.save();while(s>min){ctx.font=`${weight} ${s}px ${family}`;if(ctx.measureText(safe(t)).width<=maxW)break;s-=1}ctx.fillStyle=color;ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.font=`${weight} ${s}px ${family}`;ctx.fillText(safe(t),x,y);ctx.restore();return s}
function wrapLines(ctx,t,maxW,size,weight=700,family=FONT_BODY,maxLines=3){ctx.save();ctx.font=`${weight} ${size}px ${family}`;const words=safe(t).split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxW)line=test;else{if(line)lines.push(line);line=word;if(lines.length>=maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);ctx.restore();return lines}
function drawWrapped(ctx,t,x,y,maxW,size,lh,weight=700,color=C.ink,family=FONT_BODY,maxLines=3){const lines=wrapLines(ctx,t,maxW,size,weight,family,maxLines);lines.forEach((l,i)=>text(ctx,l,x,y+i*lh,size,weight,color,'left',family));return lines.length}
function pill(ctx,label,x,y,w,h,bg,fg=C.blue){rr(ctx,x,y,w,h,h/2,bg,null);text(ctx,label,x+w/2,y+h*.68,Math.max(12,Math.min(18,h*.45)),800,fg,'center',FONT_COND)}
function iconClock(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y-7);ctx.lineTo(x+6,y+3);ctx.stroke();ctx.restore()}
function iconPin(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y-4,10,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x-7,y+3);ctx.lineTo(x,y+17);ctx.lineTo(x+7,y+3);ctx.stroke();ctx.beginPath();ctx.arc(x,y-4,3,0,Math.PI*2);ctx.fill();ctx.restore()}
function iconPeople(ctx,x,y,color){ctx.save();ctx.fillStyle=color;[[-10,-7],[10,-7],[0,-12]].forEach(([dx,dy])=>{ctx.beginPath();ctx.arc(x+dx,y+dy,6,0,Math.PI*2);ctx.fill()});rr(ctx,x-19,y+2,12,13,6,color,null);rr(ctx,x-6,y-1,12,17,6,color,null);rr(ctx,x+7,y+2,12,13,6,color,null);ctx.restore()}
function iconBus(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;rr(ctx,x-14,y-15,28,28,6,null,color,3);ctx.beginPath();ctx.moveTo(x-9,y-6);ctx.lineTo(x+9,y-6);ctx.stroke();ctx.beginPath();ctx.arc(x-8,y+10,3,0,Math.PI*2);ctx.arc(x+8,y+10,3,0,Math.PI*2);ctx.fill();ctx.restore()}
function iconBall(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,25,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.stroke();for(let a=0;a<Math.PI*2;a+=Math.PI*2/5){ctx.beginPath();ctx.moveTo(x+7*Math.cos(a),y+7*Math.sin(a));ctx.lineTo(x+22*Math.cos(a),y+22*Math.sin(a));ctx.stroke()}ctx.restore()}
function iconGym(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.arc(x,y-24,6,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y-17);ctx.lineTo(x-7,y+2);ctx.lineTo(x+14,y+20);ctx.moveTo(x-5,y-7);ctx.lineTo(x-23,y+1);ctx.moveTo(x+2,y-8);ctx.lineTo(x+24,y-20);ctx.stroke();ctx.restore()}
function iconClimb(ctx,x,y,color){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x+21,y-28);ctx.lineTo(x+8,y+28);ctx.stroke();ctx.beginPath();ctx.arc(x-3,y-15,6,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(x-3,y-8);ctx.lineTo(x+4,y+5);ctx.lineTo(x-8,y+22);ctx.moveTo(x+2,y);ctx.lineTo(x+18,y-10);ctx.moveTo(x+4,y+5);ctx.lineTo(x+15,y+21);ctx.stroke();ctx.restore()}
function specialtyIcon(ctx,s,x,y,color){if(s==='Section Football')iconBall(ctx,x,y,color);else if(s==='Option Escalade')iconClimb(ctx,x,y,color);else if(s==='Sport-études Gymnastique')iconGym(ctx,x,y,color);else{iconBall(ctx,x-16,y,color);iconBall(ctx,x+18,y+8,color)}}
function dateParts(date){const d=new Date(date+'T12:00:00');return{day:String(d.getDate()).padStart(2,'0'),mon:d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase(),weekday:d.toLocaleDateString('fr-FR',{weekday:'long'}),monthLong:d.toLocaleDateString('fr-FR',{month:'long'}),year:d.getFullYear()}}
async function loadImg(src){return await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
async function loadLogo(){try{return await loadImg('assets/logo-as.png')}catch{return null}}
function pageCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function drawProgrammeHeader(ctx,w,events){const label=events.length?dateParts(events[0].date):null;const end=events.length?dateParts(events[events.length-1].date):null;let period='RENDEZ-VOUS À VENIR';if(label){period+=` — ${label.monthLong.toUpperCase()} ${label.year}`;if(end&&end.monthLong!==label.monthLong)period+=` / ${end.monthLong.toUpperCase()} ${end.year}`}
 brush(ctx,78,318,820,C.yellow,14);fitText(ctx,period,95,365,800,44,900,C.blue,FONT_COND,28);dots(ctx,48,325,C.blue,4,4,12,3)}
function drawProgrammeCard(ctx,e,x,y,w,h,hasConv){const col=specialtyColor(e.specialty), lite=specialtyLite(e.specialty), p=dateParts(e.date);rr(ctx,x,y,w,h,22,C.white,C.line,2);ctx.fillStyle=col;rr(ctx,x,y,9,h,8,col,null);const dateW=105;text(ctx,p.day,x+35,y+78,62,900,col,'left',FONT_DISPLAY);text(ctx,p.mon,x+38,y+111,28,900,C.blue,'left',FONT_COND);brush(ctx,x+35,y+121,72,C.yellow,6);ctx.strokeStyle=C.line;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+dateW+16,y+30);ctx.lineTo(x+dateW+16,y+h-30);ctx.stroke();const cx=x+dateW+42;const badge=safe(e.specialty||'Association Sportive');const bw=Math.min(w-190,Math.max(150,badge.length*10+42));pill(ctx,badge.toUpperCase(),cx,y+28,bw,34,lite,col);if(hasConv)pill(ctx,'CONVOCATION',x+w-170,y+28,145,34,C.yellow,C.blue);drawWrapped(ctx,e.title,cx,y+103,w-dateW-95,31,34,900,C.blue,FONT_COND,2);const iy=y+h-122;iconPeople(ctx,cx+8,iy+5,C.blue);text(ctx,'Catégorie',cx+38,iy,17,800,C.blue,'left',FONT_COND);text(ctx,e.ageCategory||'Toutes catégories',cx+38,iy+24,19,700,C.ink,'left',FONT_BODY);iconClock(ctx,cx+8,iy+52,C.blue);text(ctx,'Horaires',cx+38,iy+48,17,800,C.blue,'left',FONT_COND);text(ctx,`${e.startTime||'—'} – ${e.endTime||'—'}`,cx+38,iy+72,19,700,C.ink,'left',FONT_BODY);iconPin(ctx,cx+8,iy+100,C.blue);text(ctx,'Lieu',cx+38,iy+94,17,800,C.blue,'left',FONT_COND);drawWrapped(ctx,e.place||'—',cx+38,iy+118,w-dateW-210,18,22,700,C.ink,FONT_BODY,2);specialtyIcon(ctx,e.specialty,x+w-68,y+96,col);dots(ctx,x+w-75,y+h-70,col,4,4,10,2.4)}
async function programmeCanvas(events,d){const bgParts=(window.AS_TPL_PARTS&&window.AS_TPL_PARTS.programme)||[];let bg=null;if(window.AS_V16_TEMPLATES&&window.AS_V16_TEMPLATES.programme){try{bg=await loadImg(window.AS_V16_TEMPLATES.programme)}catch{}}else if(bgParts.length){try{bg=await loadImg('data:image/jpeg;base64,'+bgParts.join(''))}catch{}}
 const W=1100,H=1554,c=pageCanvas(W,H),ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);if(bg)ctx.drawImage(bg,0,0,W,H);else{ctx.fillStyle=C.white;ctx.fillRect(0,0,W,H);text(ctx,'PROGRAMME',50,150,96,900,'#222','left',FONT_DISPLAY);text(ctx,'ASSOCIATION SPORTIVE BON SAUVEUR',54,187,26,900,'#222','left',FONT_COND)}drawProgrammeHeader(ctx,W,events);const conv=e=>(d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&(!e.title||c.title===e.title)));const n=events.length, left=35,right=35,gap=28,top=410;let boxes=[];if(n===1)boxes=[[left,top,W-left-right,650]];else if(n===2)boxes=[[left,top,(W-left-right-gap)/2,600],[left+(W-left-right+gap)/2,top,(W-left-right-gap)/2,600]];else if(n===3)boxes=[[left,top,(W-left-right-gap)/2,470],[left+(W-left-right+gap)/2,top,(W-left-right-gap)/2,470],[left,top+495,W-left-right,430]];else{const cw=(W-left-right-gap)/2,ch=n===5?420:470;for(let i=0;i<Math.min(4,n);i++)boxes.push([left+(i%2)*(cw+gap),top+Math.floor(i/2)*(ch+24),cw,ch]);if(n===5)boxes.push([left,top+2*(ch+24),W-left-right,330])}events.forEach((e,i)=>{const b=boxes[i];if(b)drawProgrammeCard(ctx,e,...b,conv(e))});text(ctx,'BON SAUVEUR — SAINT-LÔ',W/2,H-48,15,800,C.blue,'center',FONT_COND);return c}

async function drawConvocationDecor(ctx,W,H,logo){ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.save();ctx.lineWidth=38;ctx.strokeStyle='#294A9F';ctx.beginPath();ctx.ellipse(W*.34,-35,W*.33,130,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=22;ctx.beginPath();ctx.ellipse(W*.34,-35,W*.25,102,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=C.yellow;ctx.lineWidth=32;ctx.beginPath();ctx.ellipse(W*.55,-38,W*.24,94,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=18;ctx.beginPath();ctx.ellipse(W*.55,-38,W*.18,69,0,0,Math.PI*2);ctx.stroke();ctx.restore();text(ctx,'CONVOCATION',48,112,78,900,'#242424','left',FONT_DISPLAY);text(ctx,'ASSOCIATION SPORTIVE BON SAUVEUR',52,146,24,900,'#242424','left',FONT_COND);if(logo)ctx.drawImage(logo,W-190,20,145,145);ctx.fillStyle='#294A9F';ctx.fillRect(0,H-38,W*.28,38);ctx.fillStyle=C.yellow;ctx.beginPath();ctx.moveTo(W*.30,H);ctx.lineTo(W*.36,H-38);ctx.lineTo(W*.42,H-38);ctx.lineTo(W*.40,H);ctx.fill();ctx.fillStyle='#294A9F';ctx.beginPath();ctx.moveTo(W*.46,H);ctx.lineTo(W*.49,H-38);ctx.lineTo(W*.56,H-38);ctx.lineTo(W*.55,H);ctx.fill();ctx.fillStyle=C.yellow;ctx.beginPath();ctx.moveTo(W*.61,H);ctx.lineTo(W*.64,H-38);ctx.lineTo(W*.73,H-38);ctx.lineTo(W*.72,H);ctx.fill();ctx.fillStyle='#294A9F';ctx.fillRect(W*.86,H-38,W*.14,38)}
function infoCard(ctx,label,value,x,y,w,h,icon,col=C.blue){rr(ctx,x,y,w,h,15,C.panel,C.line,2);if(icon==='pin')iconPin(ctx,x+35,y+35,col);else if(icon==='clock')iconClock(ctx,x+35,y+35,col);else if(icon==='bus')iconBus(ctx,x+35,y+35,col);else iconPeople(ctx,x+35,y+35,col);text(ctx,label,x+72,y+26,18,900,col,'left',FONT_COND);drawWrapped(ctx,value,x+72,y+56,w-92,25,28,800,C.ink,FONT_BODY,2)}
async function convocationCanvas(c,d){const W=1400,H=991,can=pageCanvas(W,H),ctx=can.getContext('2d');let bg=null;if(window.AS_V16_TEMPLATES&&window.AS_V16_TEMPLATES.convocation){try{bg=await loadImg(window.AS_V16_TEMPLATES.convocation)}catch{}}const logo=await loadLogo();if(bg)ctx.drawImage(bg,0,0,W,H);else await drawConvocationDecor(ctx,W,H,logo);const col=specialtyColor(c.specialty),lite=specialtyLite(c.specialty),p=dateParts(c.date);brush(ctx,95,185,260,C.yellow,10);text(ctx,c.specialty||'Association Sportive',125,215,30,900,C.blue,'left',FONT_COND,true);fitText(ctx,c.title||c.activity,120,300,970,64,900,C.blue,FONT_COND,34);specialtyIcon(ctx,c.specialty,1190,275,col);pill(ctx,c.specialty||'Association Sportive',120,320,220,42,col===C.yellow?C.yellow:C.blue,col===C.yellow?C.blue:C.white);pill(ctx,c.ageCategory||'Toutes catégories',360,320,170,42,C.yellow,C.blue);rr(ctx,42,390,300,455,18,C.panel,C.line,2);text(ctx,p.weekday.toUpperCase(),95,445,34,900,C.blue,'left',FONT_COND);text(ctx,p.day,92,600,130,900,C.blue,'left',FONT_DISPLAY);brush(ctx,88,620,175,C.yellow,10);text(ctx,p.monthLong.toUpperCase(),92,675,44,900,C.blue,'left',FONT_COND);text(ctx,p.year,145,725,38,900,C.blue,'center',FONT_COND);specialtyIcon(ctx,c.specialty,190,790,col);infoCard(ctx,'Lieu',c.place||'—',365,390,300,105,'pin',col);infoCard(ctx,'Départ',c.departure||'—',685,390,200,105,'bus',col);infoCard(ctx,'Retour',c.returnTime||'—',905,390,200,105,'bus',col);infoCard(ctx,'Point de rendez-vous',c.meetingPoint||'—',1125,390,235,105,'people',col);infoCard(ctx,'Professeur référent',c.teacher||'À renseigner',365,515,480,105,'people',col);rr(ctx,865,515,495,105,15,C.yellowLite,'#F4D23A',2);brush(ctx,905,535,235,C.yellow,7);text(ctx,'Informations importantes',905,565,25,900,C.blue,'left',FONT_COND,true);drawWrapped(ctx,c.extraInfo||'Aucune information particulière.',905,595,420,20,24,700,C.ink,FONT_BODY,2);rr(ctx,365,640,995,205,16,C.panel,C.line,2);iconPeople(ctx,410,695,C.blue);text(ctx,'ÉLÈVES CONVOQUÉS',455,700,28,900,C.blue,'left',FONT_COND);brush(ctx,455,710,260,'#9CCBFF',6);const names=(c.studentIds||[]).map(id=>V.studentName(d,id)).filter(Boolean);let x=455,y=745;names.slice(0,20).forEach(n=>{const width=Math.min(240,Math.max(130,n.length*12+45));if(x+width>1325){x=455;y+=58}pill(ctx,n,x,y,width,42,C.blueLite,C.ink);x+=width+20});text(ctx,'BON SAUVEUR — SAINT-LÔ',W/2,H-60,17,800,C.blue,'center',FONT_COND);return can}
async function saveCanvasPDF(canvas,orientation,name){const {jsPDF}=window.jspdf||{};if(!jsPDF){alert('Export PDF indisponible.');return}const doc=new jsPDF({orientation,unit:'mm',format:'a4',compress:true});const W=orientation==='landscape'?297:210,H=orientation==='landscape'?210:297;doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,W,H,undefined,'FAST');doc.save(name)}

app.exportCalendarPDF=async()=>{try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;const d=V.read(),sp=V.edu();const events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');const per=5;const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});for(let i=0;i<events.length;i+=per){if(i)doc.addPage('a4','portrait');const c=await programmeCanvas(events.slice(i,i+per),d);doc.addImage(c.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297,undefined,'FAST')}doc.save(sp?`Programme_${V.clean(sp)}.pdf`:'Programme_AS_Bon_Sauveur.pdf')}catch(err){console.error('[V16 programme]',err);alert('Impossible de générer le programme PDF.')}};
app.exportConvocation=async id=>{try{if(document.fonts&&document.fonts.ready)await document.fonts.ready;const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const canvas=await convocationCanvas(c,d);await saveCanvasPDF(canvas,'landscape',`Convocation_${V.clean(c.title||c.activity||'AS')}_${c.date||''}.pdf`)}catch(err){console.error('[V16 convocation]',err);alert('Impossible de générer la convocation PDF.')}};
window.ASV16={version:'v16-20260908-1',templates:'decor utilisateur + typographie sportive'};
})();