(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const C={blue:[24,72,165],blue2:[37,91,202],yellow:[255,210,21],purple:[126,69,197],ink:[38,38,38],muted:[92,103,119],line:[214,224,237],white:[255,255,255],pale:[248,250,253],paleYellow:[255,248,214]};
const safe=v=>String(v??'').trim();
const clean=v=>safe(v)||'—';
const accent=s=>s==='Section Football'?C.blue2:(s==='Option Escalade'||s==='Sport-études Gymnastique')?C.purple:C.yellow;
function font(doc,size=10,style='normal',color=C.ink){doc.setFont('helvetica',style);doc.setFontSize(size);doc.setTextColor(...color)}
function tx(doc,t,x,y,size=10,style='normal',color=C.ink,opt={}){font(doc,size,style,color);doc.text(Array.isArray(t)?t:safe(t),x,y,opt)}
function fit(doc,t,maxW,start=14,min=7,style='bold'){let s=start;while(s>min){font(doc,s,style);if(doc.getTextWidth(safe(t))<=maxW)break;s-=.4}return s}
function wrap(doc,t,w,size=10,style='normal',max=3){font(doc,size,style);return doc.splitTextToSize(safe(t),w).slice(0,max)}
function box(doc,x,y,w,h,fill=C.white,stroke=C.line,r=3){doc.setFillColor(...fill);doc.setDrawColor(...stroke);doc.setLineWidth(.45);doc.roundedRect(x,y,w,h,r,r,'FD')}
function line(doc,x1,y1,x2,y2,color=C.line,w=.45){doc.setDrawColor(...color);doc.setLineWidth(w);doc.line(x1,y1,x2,y2)}
function dateParts(date){const d=new Date(date+'T12:00:00');return{day:String(d.getDate()).padStart(2,'0'),mon:d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase(),weekday:d.toLocaleDateString('fr-FR',{weekday:'long'}),month:d.toLocaleDateString('fr-FR',{month:'long'}),year:d.getFullYear()}}
function monthRange(events){if(!events.length)return'RENDEZ-VOUS À VENIR';const a=dateParts(events[0].date),b=dateParts(events[events.length-1].date);return a.month===b.month&&a.year===b.year?`RENDEZ-VOUS À VENIR – ${a.month.toUpperCase()} ${a.year}`:`RENDEZ-VOUS À VENIR – ${a.month.toUpperCase()} ${a.year} / ${b.month.toUpperCase()} ${b.year}`}
async function templateData(name){const r=await fetch(`assets/${name}-template.png.b64`,{cache:'no-store'});if(!r.ok)throw new Error('template');const s=(await r.text()).trim();if(!s)throw new Error('template');return 'data:image/png;base64,'+s}
function pill(doc,label,x,y,w,bg,fg=C.white){doc.setFillColor(...bg);doc.roundedRect(x,y,w,8,4,4,'F');tx(doc,label,x+w/2,y+5.4,6.2,'bold',fg,{align:'center'})}
function labelValue(doc,label,value,x,y,w,valueSize=8.2){tx(doc,label.toUpperCase(),x,y,5.5,'bold',C.blue2);tx(doc,wrap(doc,clean(value),w,valueSize,'bold',2),x,y+6.2,valueSize,'bold',C.ink)}
function eventCard(doc,e,x,y,w,h,hasConv){const a=accent(e.specialty),p=dateParts(e.date);box(doc,x,y,w,h,C.white,C.line,4);doc.setFillColor(...a);doc.roundedRect(x,y,3.2,h,1.5,1.5,'F');const dateW=27;tx(doc,p.day,x+8,y+20,19,'bold',a===C.yellow?C.ink:a);tx(doc,p.mon,x+8,y+28,7,'bold',C.blue2);line(doc,x+dateW,y+8,x+dateW,y+h-8,C.line,.45);const cx=x+dateW+7;const usable=w-dateW-14;const titleSize=fit(doc,e.title,usable,11.8,8,'bold');tx(doc,wrap(doc,e.title,usable,titleSize,'bold',2),cx,y+14,titleSize,'bold',C.ink);const spec=safe(e.specialty||'Association Sportive');tx(doc,spec.toUpperCase(),cx,y+33,5.9,'bold',a===C.yellow?C.ink:a);if(hasConv){doc.setFillColor(...C.yellow);doc.roundedRect(x+w-35,y+7,30,8,4,4,'F');tx(doc,'CONVOCATION',x+w-20,y+12.6,5.2,'bold',C.blue,{align:'center'})}const by=y+h-28;labelValue(doc,'Catégorie',e.ageCategory||'Toutes catégories',cx,by,usable*.40,7.2);labelValue(doc,'Horaires',`${clean(e.startTime)} - ${clean(e.endTime)}`,cx+usable*.47,by,usable*.48,7.2);labelValue(doc,'Lieu',e.place||'—',cx,by+14,usable,7,2)}
app.exportCalendarPDF=async()=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),sp=V.edu();const events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');let bg;try{bg=await templateData('programme')}catch{return alert('Décor PROGRAMME introuvable.')}const per=5,pages=Math.ceil(events.length/per),doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a3',compress:true});for(let p=0;p<pages;p++){if(p)doc.addPage('a3','portrait');const ch=events.slice(p*per,p*per+per),W=297,H=420;doc.addImage(bg,'PNG',0,0,W,H,undefined,'FAST');tx(doc,monthRange(ch),17,92,12,'bold',C.blue2);line(doc,17,97,280,97,C.line,.6);const conv=e=>(d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&(!e.title||c.title===e.title)));if(ch.length===1){eventCard(doc,ch[0],17,111,263,135,conv(ch[0]))}else if(ch.length===2){eventCard(doc,ch[0],17,111,127,132,conv(ch[0]));eventCard(doc,ch[1],153,111,127,132,conv(ch[1]))}else if(ch.length===3){eventCard(doc,ch[0],17,111,127,105,conv(ch[0]));eventCard(doc,ch[1],153,111,127,105,conv(ch[1]));eventCard(doc,ch[2],17,226,263,100,conv(ch[2]))}else{const cw=127,chh=101,g=9;ch.slice(0,4).forEach((e,i)=>eventCard(doc,e,17+(i%2)*(cw+g),111+Math.floor(i/2)*(chh+10),cw,chh,conv(e)));if(ch[4])eventCard(doc,ch[4],17,333,263,58,conv(ch[4]))}tx(doc,`${p+1}/${pages}`,279,404,6.2,'bold',C.muted,{align:'right'})}doc.save(sp?`Programme_${V.clean(sp)}.pdf`:'Programme_AS_Bon_Sauveur.pdf')};
function infoBox(doc,label,value,x,y,w,h,fill=C.white){box(doc,x,y,w,h,fill,C.line,3);labelValue(doc,label,value,x+6,y+8,w-12,9)}
app.exportConvocation=async id=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');let bg;try{bg=await templateData('convocation')}catch{return alert('Décor CONVOCATION introuvable.')}const names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a3',compress:true}),W=420,H=297,p=dateParts(c.date),a=accent(c.specialty);doc.addImage(bg,'PNG',0,0,W,H,undefined,'FAST');tx(doc,(c.specialty||'Association Sportive').toUpperCase(),20,66,7.2,'bold',a===C.yellow?C.ink:a);const title=safe(c.title||c.activity||'Convocation'),ts=fit(doc,title,295,22,13,'bold');tx(doc,wrap(doc,title,295,ts,'bold',2),20,83,ts,'bold',C.blue2);pill(doc,c.ageCategory||'Toutes catégories',344,69,42,C.yellow,C.blue);pill(doc,c.specialty||'Association Sportive',20,91,58,a,a===C.yellow?C.ink:C.white);tx(doc,p.weekday.toUpperCase(),20,118,7.4,'bold',C.blue2);tx(doc,p.day,20,145,24,'bold',C.blue2);tx(doc,p.month.toUpperCase(),20,157,8,'bold',C.blue2);tx(doc,String(p.year),20,166,6.8,'bold',C.muted);line(doc,53,104,53,241,C.line,.6);infoBox(doc,'Lieu',c.place||'—',63,106,70,34);infoBox(doc,'Départ',c.departure||'—',139,106,55,34);infoBox(doc,'Retour',c.returnTime||'—',200,106,55,34);infoBox(doc,'Point de rendez-vous',c.meetingPoint||'—',261,106,139,34);infoBox(doc,'Professeur référent',c.teacher||'À renseigner',63,148,120,34);infoBox(doc,'Informations importantes',c.extraInfo||'Aucune information particulière.',190,148,210,34,C.paleYellow);box(doc,63,192,337,51,C.white,C.line,3);tx(doc,'ÉLÈVES CONVOQUÉS',70,204,7,'bold',C.blue2);let x=70,y=218;for(const n of names){const ww=Math.max(29,Math.min(60,12+n.length*1.6));if(x+ww>392){x=70;y+=11}if(y>238)break;doc.setFillColor(239,246,255);doc.roundedRect(x,y-6,ww,8.3,4,4,'F');tx(doc,n,x+ww/2,y,6.8,'bold',C.ink,{align:'center'});x+=ww+5}tx(doc,'BON SAUVEUR – SAINT-LÔ',210,268,6.4,'bold',C.blue2,{align:'center'});tx(doc,'1/1',402,268,6,'bold',C.muted,{align:'right'});doc.save(`Convocation_${V.clean(c.title||c.activity||'AS')}_${c.date||''}.pdf`)};
window.ASV18={version:'v18-20260908-png-templates-2'};
})();