(()=>{
'use strict';const V=window.ASV7,app=window.app;if(!V||!app)return;const COPY='<svg viewBox="0 0 24 24"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg>';
function route(){const h=document.querySelector('.page-title h1')?.textContent?.trim()||'';return h==='Licences'?'licenses':h==='Gestion des commandes'?'orders':h==='Appréciations'?'appreciations':''}
function status(label,on){return `<button type="button" class="v19-status ${on?'paid':'pending'}"><span>${label}</span><svg viewBox="0 0 24 24"><path d="m8 9 4-4 4 4M16 15l-4 4-4-4"/></svg></button>`}
function licenses(){if(route()!=='licenses')return;const d=V.read();document.querySelectorAll('.admin-table').forEach(t=>{const i=[...t.querySelectorAll('thead th')].findIndex(x=>x.textContent.trim().toUpperCase()==='STATUT');if(i<0)return;t.querySelectorAll('tbody tr').forEach(row=>{const name=row.querySelector('td strong')?.textContent?.trim(),l=(d.licenses||[]).find(x=>x.fullName===name);if(!l)return;const td=row.children[i];if(!td)return;td.innerHTML=status(l.paymentStatus==='Payé'?'Payé':'En attente',l.paymentStatus==='Payé');td.querySelector('button').onclick=e=>{e.preventDefault();const x=V.read(),q=(x.licenses||[]).find(z=>z.id===l.id);if(!q)return;q.paymentStatus=q.paymentStatus==='Payé'?'En attente':'Payé';V.write(x);app.go('licenses')}})})}
function orders(){if(route()!=='orders')return;document.querySelectorAll('.admin-table').forEach(t=>{let heads=[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim().toLowerCase()),ready=heads.findIndex(x=>x==='prêt');if(ready>=0)t.querySelectorAll('tr').forEach(r=>r.children[ready]?.remove());heads=[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim().toLowerCase());const pi=heads.findIndex(x=>x==='payé'||x.includes('paiement')),di=heads.findIndex(x=>x==='distribué'||x==='distribution'),d=V.read();t.querySelectorAll('tbody tr').forEach(row=>{const name=row.querySelector('td strong')?.textContent?.trim()||'',o=(d.orders||[]).find(x=>x.studentName===name);if(!o)return;[[pi,'paid',!!o.paid,'Payé','En attente'],[di,'distributed',!!o.distributed,'Distribué','À distribuer']].forEach(([i,k,on,yes,no])=>{if(i<0)return;const td=row.children[i];if(!td)return;td.innerHTML=status(on?yes:no,on);td.querySelector('button').onclick=e=>{e.preventDefault();app.toggleOrder(o.id,k)}})})})}
async function copyText(text,btn){if(!text)return;try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}const old=btn.innerHTML;btn.textContent='Copié ✓';setTimeout(()=>btn.innerHTML=old,1200)}
function term(){return Number((document.querySelector('.term-tab.active')?.textContent.match(/\d+/)||['1'])[0])}
function editor(id,row){const ta=row.querySelector('.appreciation-text');if(!ta)return;const c=row.querySelectorAll('td'),name=c[0]?.querySelector('strong')?.textContent?.trim()||'Élève',cl=c[0]?.querySelector('.meta')?.textContent?.trim()||'',prev=c[1]?.textContent?.trim()||'—',t=term(),m=V.modal('Rédiger une appréciation',`<div class="v19-app-editor"><div class="v19-app-student"><div><span>Élève</span><strong>${V.esc(name)}</strong><small>${V.esc(cl)}</small></div><span>Trimestre ${t}</span></div><div class="v19-prev"><span>Trimestre précédent</span><p>${V.esc(prev)}</p></div><label class="v19-editor-field"><span>Appréciation</span><textarea id="v19-app-text" maxlength="900">${V.esc(ta.value||'')}</textarea><small><b id="v19-count">${(ta.value||'').length}</b> caractères</small></label><div class="v19-editor-actions"><button class="btn secondary" id="v19-draft">Enregistrer le brouillon</button><button class="btn" id="v19-validate">Vérifier & valider</button></div></div>`,true),x=m.querySelector('#v19-app-text'),n=m.querySelector('#v19-count');x.focus();x.setSelectionRange(x.value.length,x.value.length);x.oninput=()=>n.textContent=x.value.length;m.querySelector('#v19-draft').onclick=()=>{app.saveApp(id,t,x.value.trim(),'draft');V.closeModal()};m.querySelector('#v19-validate').onclick=()=>{ta.value=x.value.trim();V.closeModal();requestAnimationFrame(()=>app.validateApp(id,t))}}
function apps(){if(route()!=='appreciations')return;[...document.querySelectorAll('button')].filter(b=>b.textContent.trim()==='Exporter Excel').slice(1).forEach(b=>b.remove());document.querySelectorAll('.appreciation-table tbody tr').forEach(row=>{const ta=row.querySelector('.appreciation-text');if(!ta)return;const id=(ta.id||'').replace(/^app-/,'');const cells=row.querySelectorAll('td'),dest=cells[1]||row.firstElementChild;let box=dest.querySelector('.v19-current');if(!box){box=document.createElement('div');box.className='v19-current';dest.appendChild(box)}const txt=ta.value.trim();box.innerHTML=`<span>APPRÉCIATION ACTUELLE</span><p>${V.esc(txt||'Aucune appréciation rédigée')}</p>`;ta.closest('td')?.classList.add('v19-hidden-source');let a=row.querySelector('.v19-app-actions');if(!a){a=document.createElement('div');a.className='v19-app-actions';a.innerHTML=`<button class="btn secondary">${COPY}<span>Copier</span></button><button class="btn">${txt?'Modifier l’appréciation':'Rédiger'}</button>`;(row.lastElementChild||dest).appendChild(a);a.children[0].onclick=e=>{e.preventDefault();copyText(ta.value.trim(),a.children[0])};a.children[1].onclick=e=>{e.preventDefault();editor(id,row)}}a.children[0].disabled=!txt;a.children[1].textContent=txt?'Modifier l’appréciation':'Rédiger'})}
function refresh(){licenses();orders();apps();document.querySelectorAll('.admin-table').forEach(t=>t.closest('.table-card')?.classList.add('v19-table-card'))}
if(!app.__v19status){['go','licenseFilter','clearLicenseFilters','setTerm','saveApp','validateApp','toggleOrder'].forEach(k=>{const fn=app[k];if(typeof fn!=='function')return;app[k]=function(...a){const r=fn.apply(this,a);requestAnimationFrame(refresh);return r}});app.__v19status=true}let q=false;const root=document.getElementById('app');if(root)new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;refresh()})}).observe(root,{childList:true,subtree:true});refresh();window.ASV19Status={version:'v19-status-1'};
})();