(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const COLORS={blue:'0757C9',navy:'13213A',yellow:'FFD21A',light:'F4F7FB',line:'DCE5F0',white:'FFFFFF',muted:'65738A',green:'DDF4E6',red:'FFE5E8'};
function fileName(s){return V.clean(s)+'.xlsx'}
async function addLogo(wb,ws){try{const data=await V.logoData();if(!data)return;const id=wb.addImage({base64:data,extension:'png'});ws.addImage(id,{tl:{col:.2,row:.2},ext:{width:72,height:72}})}catch{}}
function title(ws,title,subtitle,cols){ws.mergeCells(1,2,1,cols);const c=ws.getCell(1,2);c.value=title;c.font={name:'Aptos Display',size:24,bold:true,color:{argb:'FF'+COLORS.navy}};c.alignment={vertical:'middle'};ws.getRow(1).height=34;ws.mergeCells(2,2,2,cols);const s=ws.getCell(2,2);s.value=subtitle;s.font={name:'Aptos',size:10,bold:true,color:{argb:'FF'+COLORS.blue}};ws.getRow(2).height=20;ws.mergeCells(4,1,4,cols);const band=ws.getCell(4,1);band.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+COLORS.yellow}};ws.getRow(4).height=7}
function headers(ws,row,labels){labels.forEach((h,i)=>{const c=ws.getCell(row,i+1);c.value=h;c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+COLORS.blue}};c.font={name:'Aptos Display',size:10,bold:true,color:{argb:'FF'+COLORS.white}};c.alignment={vertical:'middle',horizontal:'center',wrapText:true};c.border={bottom:{style:'medium',color:{argb:'FF'+COLORS.yellow}}}});ws.getRow(row).height=30}
function styleRows(ws,start,end,cols){for(let r=start;r<=end;r++){ws.getRow(r).height=27;for(let c=1;c<=cols;c++){const x=ws.getCell(r,c);x.font={name:'Aptos',size:10,color:{argb:'FF'+COLORS.navy}};x.alignment={vertical:'middle',wrapText:true};x.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+(r%2?COLORS.white:COLORS.light)}};x.border={bottom:{style:'hair',color:{argb:'FF'+COLORS.line}}}}}}
function autoWidths(ws,widths){widths.forEach((w,i)=>ws.getColumn(i+1).width=w)}
async function save(wb,name){const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
async function makeSheet(name,titleText,subtitle,headersList,rows,widths){if(!window.ExcelJS)return alert('Le module Excel est encore en chargement.');const wb=new ExcelJS.Workbook();wb.creator='Association Sportive du Bon Sauveur';wb.created=new Date();const ws=wb.addWorksheet(name,{views:[{state:'frozen',ySplit:6}]});await addLogo(wb,ws);title(ws,titleText,subtitle,headersList.length);headers(ws,6,headersList);rows.forEach((row,ri)=>row.forEach((v,ci)=>ws.getCell(7+ri,1+ci).value=v));styleRows(ws,7,6+rows.length,headersList.length);autoWidths(ws,widths);ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.25,right:.25,top:.5,bottom:.5,header:.2,footer:.2}};return{wb,ws}}
app.exportExcel=async type=>{const d=V.read();try{
 if(type==='licenses'){const rows=(d.licenses||[]).map(l=>[l.fullName,l.className,l.category,l.sectionOption,l.contribution,l.paymentStatus,Number(l.amount||0),l.charterSigned]);const {wb,ws}=await makeSheet('Licences','LICENCES','Association Sportive du Bon Sauveur',['Nom & prénom','Classe','Catégorie','Spécialité','Cotisation','Statut','Montant (€)','Charte'],rows,[28,25,18,26,18,16,14,12]);ws.getColumn(7).numFmt='#,##0.00 [$€-fr-FR]';const r=9+rows.length;ws.getCell(r,1).value='TOTAL ENCAISSÉ';ws.getCell(r,1).font={bold:true,color:{argb:'FF'+COLORS.blue}};ws.getCell(r,7).value=(d.licenses||[]).filter(x=>x.paymentStatus==='Payé').reduce((s,x)=>s+Number(x.amount||0),0);ws.getCell(r,7).numFmt='#,##0.00 [$€-fr-FR]';ws.getCell(r,7).font={bold:true,color:{argb:'FF'+COLORS.blue}};return save(wb,fileName('Licences_AS_Bon_Sauveur'))}
 if(type==='orders'){const rows=(d.orders||[]).map(o=>[o.studentName,o.className,(d.products||[]).find(p=>p.id===o.productId)?.name||'Produit',o.size,o.quantity||1,o.paymentMethod,o.paid?'Payé':'En attente',o.distributed?'Distribué':'À distribuer',o.createdAt]);const {wb}=await makeSheet('Commandes','COMMANDES','Boutique de l’Association Sportive',['Élève','Classe','Produit','Taille','Qté','Paiement','Statut paiement','Distribution','Date'],rows,[27,24,28,14,9,18,18,18,16]);return save(wb,fileName('Commandes_AS_Bon_Sauveur'))}
 if(type==='reports'){const rows=(d.reports||[]).map(r=>[r.date,r.activity,r.teacher,r.level,r.place,r.category,Number(r.participants||0),r.comment||'']);const {wb}=await makeSheet('Bilans','BILANS AS','Suivi des activités de l’Association Sportive',['Date','Activité','Enseignant(s)','Niveau','Lieu','Catégorie','Élèves','Commentaire'],rows,[16,28,28,18,25,20,11,40]);return save(wb,fileName('Bilans_AS_Bon_Sauveur'))}
 if(type==='convocations'){const rows=(d.convocations||[]).map(c=>[c.date,c.activity,c.title,c.specialty,c.ageCategory,c.place,c.departure,c.returnTime,c.meetingPoint,c.teacher,(c.studentIds||[]).map(id=>V.studentName(d,id)).filter(Boolean).join(', '),c.extraInfo||'']);const {wb}=await makeSheet('Convocations','CONVOCATIONS','Association Sportive du Bon Sauveur',['Date','Activité','Titre','Spécialité','Catégorie','Lieu','Départ','Retour','Rendez-vous','Professeur','Élèves convoqués','Informations importantes'],rows,[15,18,30,24,18,22,12,12,28,24,45,42]);return save(wb,fileName('Convocations_AS_Bon_Sauveur'))}
 if(type==='appreciations'){const sp=V.edu();const term=Number((document.querySelector('.term-tab.active')?.textContent.match(/\d+/)||['1'])[0]);const lic=(d.licenses||[]).filter(l=>!sp||l.sectionOption===sp),rows=lic.map(l=>{const a=(d.appreciations||[]).find(x=>x.studentId===l.studentId&&Number(x.term)===term);return[l.fullName,l.className,l.sectionOption,term,a?.text||'',a?.status==='validated'?'Validé':'Brouillon / à faire']});const {wb}=await makeSheet('Appréciations','APPRÉCIATIONS',`${sp||'Toutes spécialités'} · Trimestre ${term}`,['Élève','Classe','Spécialité','Trimestre','Appréciation','Statut'],rows,[28,25,27,12,60,20]);return save(wb,fileName(`Appreciations_${sp||'AS'}_T${term}`))}
 }catch(e){console.error(e);alert('Impossible de créer le fichier Excel.')}
};
window.ASV19Excel={version:'v19-20260908-excel-1'};
})();