(()=>{
'use strict';
const V=window.ASV7,app=window.app;if(!V||!app)return;
const COLORS={blue:'#0757C9',blue2:'#2E72D9',yellow:'#FFD21A',purple:'#7552D7',ink:'#222222',navy:'#13213A',muted:'#69778E',line:'#D8E2EE',pale:'#F6F9FD',paleBlue:'#EEF5FF',paleYellow:'#FFF7D4',white:'#FFFFFF'};
const chunks={convocation:5,programme:5};
const safe=v=>String(v??'').trim();
function accent(sp){return sp==='Section Football'?COLORS.blue2:(sp==='Option Escalade'||sp==='Sport-études Gymnastique')?COLORS.purple:'#D8AE00'}
async function base64Template(kind){const n=chunks[kind],prefix=kind==='convocation'?'conv':'prog';const parts=await Promise.all(Array.from({length:n},(_,i)=>fetch(`assets/v19-${prefix}-${String(i+1).padStart(2,'0')}.txt`,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('Décor introuvable');return r.text()})));return'data:image/png;base64,'+parts.join('')}
function image(src){return new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=src})}
async function template(kind){return image(await base64Template(kind))}
function rr(ctx,x,y,w,h,r,fill,stroke=COLORS.line,lw=2){ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,r);else{const q=Math.min(r,w/2,h/2);ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q)}if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function font(ctx,size,weight=700,family='Arial Narrow, Helvetica Neue, Arial, sans-serif'){ctx.font=`${weight} ${size}px ${family}`;ctx.textBaseline='top'}
function fit(ctx,text,maxW,maxSize,minSize=20,weight=700,family){let s=maxSize;for(;s>minSize;s-=1){font(ctx,s,weight,family);if(ctx.measureText(safe(text)).width<=maxW)break}return s}
function wrap(ctx,text,maxW,maxLines=2){const words=safe(text).split(/\s+/).filter(Boolean),lines=[];let line='';for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width<=maxW||!line)line=test;else{lines.push(line);line=w;if(lines.length===maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);if(lines.length===maxLines&&words.length){const joined=lines.join(' '),orig=words.join(' ');if(joined.length<orig.length){let last=lines[lines.length-1];while(last.length>2&&ctx.measureText(last+'…').width>maxW)last=last.slice(0,-1);lines[lines.length-1]=last.replace(/[ ,.;:-]+$/,'')+'…'}}return lines}
function text(ctx,t,x,y,size=28,color=COLORS.ink,weight=700,maxW=null,maxLines=1,lineGap=1.1,family){font(ctx,size,weight,family);ctx.fillStyle=color;const lines=maxW?wrap(ctx,t,maxW,maxLines):[safe(t)];lines.forEach((l,i)=>ctx.fillText(l,x,y+i*size*lineGap));return lines.length*size*lineGap}
function labelValue(ctx,label,value,x,y,w,valueSize=28,maxLines=2){text(ctx,label.toUpperCase(),x,y,16,COLORS.blue,800,w,1,1,'Arial, Helvetica, sans-serif');font(ctx,valueSize,800,'Arial, Helvetica, sans-serif');text(ctx,value||'—',x,y+29,valueSize,COLORS.navy,800,w,maxLines,1.08,'Arial, Helvetica, sans-serif')}
function pill(ctx,label,x,y,bg,fg=COLORS.white,maxW=270){font(ctx,18,800,'Arial, Helvetica, sans-serif');let w=Math.min(maxW,Math.max(110,ctx.measureText(safe(label)).width+34));rr(ctx,x,y,w,42,21,bg,null,0);ctx.fillStyle=fg;ctx.textAlign='center';ctx.fillText(safe(label),x+w/2,y+11);ctx.textAlign='left';return w}
function dateParts(d){const x=new Date(d+'T12:00:00');return{day:String(x.getDate()).padStart(2,'0'),mon:x.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase(),month:x.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase(),weekday:x.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),year:x.getFullYear()}}
function monthTitle(events){if(!events.length)return'';const a=dateParts(events[0].date),b=dateParts(events[events.length-1].date);return a.month===b.month&&a.year===b.year?`${a.month} ${a.year}`:`${a.month} ${a.year} — ${b.month} ${b.year}`}
function eventCard(ctx,e,x,y,w,h,conv){const ac=accent(e.specialty),p=dateParts(e.date);rr(ctx,x,y,w,h,24,'rgba(255,255,255,.96)',COLORS.line,3);ctx.fillStyle=ac;rr(ctx,x,y,10,h,5,ac,null,0);rr(ctx,x+28,y+28,125,125,20,ac,null,0);ctx.textAlign='center';text(ctx,p.day,x+90,y+45,48,COLORS.white,900,null,1,1,'Arial Narrow, Impact, sans-serif');text(ctx,p.mon,x+90,y+102,22,ac==='#D8AE00'?COLORS.navy:COLORS.white,900,null,1,1,'Arial, Helvetica, sans-serif');ctx.textAlign='left';const cx=x+180,titleW=w-215;let ts=fit(ctx,e.title,titleW,h>380?38:34,24,900,'Arial Narrow, Helvetica Neue, Arial, sans-serif');text(ctx,e.title,cx,y+32,ts,COLORS.navy,900,titleW,2,1.02,'Arial Narrow, Helvetica Neue, Arial, sans-serif');let py=y+123;const pw=pill(ctx,e.specialty||'Association Sportive',cx,py,ac,ac==='#D8AE00'?COLORS.navy:COLORS.white,250);if(conv)pill(ctx,'CONVOCATION',cx+pw+12,py,COLORS.yellow,COLORS.navy,185);const infoY=y+h-150;const colW=(w-220)/3;labelValue(ctx,'Catégorie',e.ageCategory||'Toutes catégories',cx,infoY,colW-15,24,2);labelValue(ctx,'Horaires',`${safe(e.startTime)||'—'}${e.endTime?' – '+e.endTime:''}`,cx+colW,infoY,colW-15,24,2);labelValue(ctx,'Lieu',e.place||'—',cx+colW*2,infoY,colW-15,23,2)}
function programmeLayouts(n){if(n===1)return[[55,470,1338,720]];if(n===2)return[[55,470,649,720],[744,470,649,720]];if(n===3)return[[55,470,649,610],[744,470,649,610],[55,1110,1338,530]];if(n===4)return[[55,455,649,565],[744,455,649,565],[55,1050,649,565],[744,1050,649,565]];return[[55,445,649,520],[744,445,649,520],[55,995,649,520],[744,995,649,520],[55,1545,1338,315]]}
async function programmeCanvas(events,page,total,d){const bg=await template('programme'),c=document.createElement('canvas');c.width=1448;c.height=2048;const ctx=c.getContext('2d');ctx.drawImage(bg,0,0,c.width,c.height);text(ctx,monthTitle(events),64,355,39,COLORS.blue,900,1100,1,1,'Arial Narrow, Helvetica Neue, Arial, sans-serif');ctx.fillStyle=COLORS.yellow;ctx.fillRect(64,411,320,8);const lays=programmeLayouts(events.length);events.forEach((e,i)=>{const conv=(d.convocations||[]).some(x=>x.id===e.convocationId||(x.date===e.date&&x.specialty===e.specialty&&x.title===e.title));eventCard(ctx,e,...lays[i],conv)});text(ctx,`PAGE ${page}/${total}`,1280,1910,16,COLORS.muted,800,100,1,1,'Arial, Helvetica, sans-serif');return c}
app.exportCalendarPDF=async()=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),sp=V.edu();const ev=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!ev.length)return alert('Aucun événement à exporter.');try{const per=5,total=Math.ceil(ev.length/per),doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a3',compress:true});for(let p=0;p<total;p++){if(p)doc.addPage('a3','portrait');const canvas=await programmeCanvas(ev.slice(p*per,p*per+per),p+1,total,d);doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,297,420,undefined,'FAST')}doc.save(sp?`Programme_${V.clean(sp)}.pdf`:'Programme_AS_Bon_Sauveur.pdf')}catch(e){console.error(e);alert('Impossible de charger le décor PROGRAMME.')}};
function infoBox(ctx,label,value,x,y,w,h,fill=COLORS.pale){rr(ctx,x,y,w,h,18,fill,COLORS.line,2);labelValue(ctx,label,value,x+22,y+22,w-44,28,2)}
function studentChips(ctx,names,x,y,w,h){rr(ctx,x,y,w,h,20,'rgba(255,255,255,.96)',COLORS.line,2);text(ctx,'ÉLÈVES CONVOQUÉS',x+24,y+22,22,COLORS.blue,900,w-80,1,1,'Arial, Helvetica, sans-serif');text(ctx,String(names.length),x+w-42,y+22,20,COLORS.muted,800,30,1,1,'Arial, Helvetica, sans-serif');let xx=x+24,yy=y+72;for(const n of names){font(ctx,20,800,'Arial, Helvetica, sans-serif');let cw=Math.min(310,Math.max(135,ctx.measureText(n).width+40));if(xx+cw>x+w-24){xx=x+24;yy+=58}if(yy+44>y+h-15)break;rr(ctx,xx,yy,cw,42,21,COLORS.paleBlue,null,0);ctx.textAlign='center';text(ctx,n,xx+cw/2,yy+10,19,COLORS.navy,800,null,1,1,'Arial, Helvetica, sans-serif');ctx.textAlign='left';xx+=cw+14}}
async function convCanvas(c,names,page,total){const bg=await template('convocation'),canvas=document.createElement('canvas');canvas.width=2048;canvas.height=1448;const ctx=canvas.getContext('2d');ctx.drawImage(bg,0,0,canvas.width,canvas.height);const ac=accent(c.specialty),p=dateParts(c.date);text(ctx,(c.specialty||'Association Sportive').toUpperCase(),90,350,25,ac,900,500,1,1,'Arial, Helvetica, sans-serif');let ts=fit(ctx,c.title||c.activity,1500,61,38,900,'Arial Narrow, Helvetica Neue, Arial, sans-serif');text(ctx,c.title||c.activity,90,398,ts,COLORS.blue,900,1500,2,1.02,'Arial Narrow, Helvetica Neue, Arial, sans-serif');let px=90;px+=pill(ctx,c.specialty||'Association Sportive',px,510,ac,ac==='#D8AE00'?COLORS.navy:COLORS.white,300)+14;pill(ctx,c.ageCategory||'Toutes catégories',px,510,COLORS.yellow,COLORS.navy,240);const dy=590;rr(ctx,80,dy,310,610,24,COLORS.paleBlue,COLORS.line,2);text(ctx,p.weekday,115,dy+35,24,COLORS.blue,900,240,1,1,'Arial, Helvetica, sans-serif');text(ctx,p.day,112,dy+108,98,COLORS.blue,900,200,1,1,'Arial Narrow, Impact, sans-serif');ctx.fillStyle=COLORS.yellow;ctx.fillRect(110,dy+230,150,8);text(ctx,p.month,112,dy+257,36,COLORS.blue,900,230,1,1,'Arial Narrow, Helvetica Neue, Arial, sans-serif');text(ctx,String(p.year),114,dy+311,25,COLORS.muted,800,180,1,1,'Arial, Helvetica, sans-serif');text(ctx,'PROFESSEUR RÉFÉRENT',112,dy+405,16,COLORS.blue,900,230,1,1,'Arial, Helvetica, sans-serif');text(ctx,c.teacher||'À renseigner',112,dy+438,26,COLORS.navy,850,230,2,1.05,'Arial, Helvetica, sans-serif');const x=430;infoBox(ctx,'Lieu',c.place||'—',x,590,350,160);infoBox(ctx,'Départ',c.departure||'—',800,590,260,160);infoBox(ctx,'Retour',c.returnTime||'—',1080,590,260,160);infoBox(ctx,'Point de rendez-vous',c.meetingPoint||'—',1360,590,600,160);infoBox(ctx,'Informations importantes',c.extraInfo||'—',430,775,970,185,COLORS.paleYellow);studentChips(ctx,names,430,985,1530,215);text(ctx,`PAGE ${page}/${total}`,1870,1320,16,COLORS.muted,800,100,1,1,'Arial, Helvetica, sans-serif');return canvas}
app.exportConvocation=async id=>{const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const all=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),per=18,total=Math.max(1,Math.ceil(all.length/per));try{const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a3',compress:true});for(let p=0;p<total;p++){if(p)doc.addPage('a3','landscape');const canvas=await convCanvas(c,all.slice(p*per,p*per+per),p+1,total);doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,420,297,undefined,'FAST')}doc.save(`Convocation_${V.clean(c.title||c.activity||'AS')}_${c.date||''}.pdf`)}catch(e){console.error(e);alert('Impossible de charger le décor CONVOCATION.')}};
window.ASV19Exports={version:'v19-20260908-exact-templates-1'};
})();