(() => {
'use strict';
if(!window.app)return;
const C={blue:'#0757C9',navy:'#13213A',yellow:'#FFD21A',ink:'#202733',muted:'#69758A',line:'#D9E2EE',football:'#3E8FEA',escalade:'#7357D9',gym:'#9558CC',as:'#C9A20B',white:'#FFFFFF',soft:'#F6F8FB'};
const SPEC={'Association Sportive':C.as,'Section Football':C.football,'Option Escalade':C.escalade,'Sport-études Gymnastique':C.gym};
const titleFont='Anton, Impact, Arial Narrow, sans-serif';
const bodyFont='Arial, Helvetica, sans-serif';

async function ensureFonts(){try{await document.fonts?.ready;await document.fonts?.load('48px Anton')}catch{}}
async function template(kind){const path=kind==='conv'?'assets/convocation-template.png.b64':'assets/programme-template.png.b64';const r=await fetch(path+'?v=20',{cache:'force-cache'});if(!r.ok)throw new Error('Fond graphique indisponible');const b64=(await r.text()).replace(/\s+/g,'');if(!b64.startsWith('iVBOR'))throw new Error('Fond graphique invalide');return loadImage('data:image/png;base64,'+b64)}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src})}
function rr(ctx,x,y,w,h,r,fill=null,stroke=null,lw=2){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function txt(ctx,t,x,y,size,weight=700,color=C.ink,align='left',family=bodyFont){ctx.fillStyle=color;ctx.font=`${weight} ${size}px ${family}`;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.fillText(String(t??''),x,y)}
function lines(ctx,str,maxW,size,weight=700,family=bodyFont){ctx.font=`${weight} ${size}px ${family}`;const words=String(str??'').split(/\s+/).filter(Boolean),out=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxW||!line)line=test;else{out.push(line);line=word}}if(line)out.push(line);return out}
function fit(ctx,str,maxW,start,min,weight=700,family=bodyFont,maxLines=2){for(let s=start;s>=min;s--){const l=lines(ctx,str,maxW,s,weight,family);if(l.length<=maxLines)return{size:s,lines:l}}return{size:min,lines:lines(ctx,str,maxW,min,weight,family).slice(0,maxLines)}}
function block(ctx,str,x,y,maxW,start=42,min=24,maxLines=2,weight=800,color=C.ink,family=bodyFont,gap=1.12){const f=fit(ctx,str,maxW,start,min,weight,family,maxLines);ctx.fillStyle=color;ctx.font=`${weight} ${f.size}px ${family}`;ctx.textAlign='left';ctx.textBaseline='alphabetic';f.lines.forEach((ln,i)=>ctx.fillText(ln,x,y+i*f.size*gap));return y+(f.lines.length-1)*f.size*gap}
function info(ctx,label,value,x,y,w,{accent=C.blue,valueSize=30,maxLines=2}={}){txt(ctx,label.toUpperCase(),x,y,16,900,accent);block(ctx,value||'—',x,y+35,w,valueSize,20,maxLines,800,C.ink,bodyFont,1.15)}
function chip(ctx,label,x,y,{bg='#EDF4FD',fg=C.blue,maxW=330}={}){ctx.font=`800 20px ${bodyFont}`;const w=Math.min(maxW,ctx.measureText(label).width+34);rr(ctx,x,y,w,42,21,bg);txt(ctx,label,x+17,y+28,20,800,fg);return w}
function parts(date){const d=new Date(date+'T12:00:00');return{weekday:d.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),day:String(d.getDate()).padStart(2,'0'),month:d.toLocaleDateString('fr-FR',{month:'long'}).toUpperCase(),year:d.getFullYear()}}
function color(sp){return SPEC[sp]||C.blue}
function canvas(bg){const c=document.createElement('canvas');c.width=bg.naturalWidth||bg.width;c.height=bg.naturalHeight||bg.height;const ctx=c.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(bg,0,0,c.width,c.height);return{c,ctx}}
function names(c){return(c.studentIds||[]).map(id=>window.app.studentName(id)).filter(Boolean)}
function clean(s='export'){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')}

function convFirst(bg,c,studentNames){
 const {c:cv,ctx}=canvas(bg),W=cv.width,sc=W/2048,s=v=>v*sc,a=color(c.specialty);
 txt(ctx,c.specialty||'Association Sportive',s(115),s(350),22,900,a);
 block(ctx,c.title||c.activity||'Convocation',s(115),s(425),s(1260),66,38,2,400,C.blue,titleFont,1.03);
 let cx=s(115),cy=s(475);cx+=chip(ctx,c.specialty||'Association Sportive',cx,cy,{bg:'#EAF3FF',fg:a,maxW:s(390)})+s(18);chip(ctx,c.ageCategory||'Toutes catégories',cx,cy,{bg:'#FFF2A6',fg:'#6F5D0A',maxW:s(280)});
 const dp=parts(c.date);txt(ctx,dp.weekday,s(115),s(620),22,900,C.blue);txt(ctx,dp.day,s(112),s(820),120,400,C.blue,'left',titleFont);ctx.fillStyle=C.yellow;ctx.fillRect(s(110),s(845),s(210),s(12));txt(ctx,dp.month,s(115),s(915),30,400,C.blue,'left',titleFont);txt(ctx,dp.year,s(115),s(960),20,900,C.muted);
 info(ctx,'Lieu',c.place,s(470),s(620),s(280),{valueSize:31});info(ctx,'Départ',c.departure,s(810),s(620),s(230),{valueSize:33});info(ctx,'Retour',c.returnTime,s(1115),s(620),s(230),{valueSize:33});info(ctx,'Point de rendez-vous',c.meetingPoint,s(1430),s(620),s(460),{valueSize:30,maxLines:2});
 ctx.strokeStyle=C.line;ctx.lineWidth=s(2);ctx.beginPath();ctx.moveTo(s(455),s(740));ctx.lineTo(s(1930),s(740));ctx.stroke();
 info(ctx,'Professeur référent',c.teacher||'À renseigner',s(470),s(810),s(430),{valueSize:29,maxLines:2});info(ctx,'Informations importantes',c.extraInfo||'Aucune information particulière.',s(1050),s(810),s(870),{accent:'#B58C00',valueSize:27,maxLines:3});
 txt(ctx,'ÉLÈVES CONVOQUÉS',s(470),s(1080),22,900,C.blue);ctx.strokeStyle='#BFD3EF';ctx.lineWidth=s(4);ctx.beginPath();ctx.moveTo(s(470),s(1095));ctx.lineTo(s(820),s(1095));ctx.stroke();
 const shown=studentNames.slice(0,18),cols=3,cw=430,startX=470,startY=1135;shown.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=startX+col*cw,y=startY+row*70;rr(ctx,s(x),s(y),s(380),s(54),s(27),'#F0F5FB');block(ctx,n,s(x+20),s(y+36),s(340),22,17,1,800,C.ink)});if(studentNames.length>shown.length)txt(ctx,`+ ${studentNames.length-shown.length} élève(s) en page suivante`,s(470),s(1370),17,800,C.muted);txt(ctx,'BON SAUVEUR – SAINT-LÔ',W/2,s(1390),16,900,C.blue,'center');return cv
}
function convMore(bg,c,studentNames,page,total){const {c:cv,ctx}=canvas(bg),W=cv.width,sc=W/2048,s=v=>v*sc;txt(ctx,c.specialty||'Association Sportive',s(115),s(350),22,900,color(c.specialty));block(ctx,`${c.title||'Convocation'} — ÉLÈVES CONVOQUÉS`,s(115),s(430),s(1500),54,34,2,400,C.blue,titleFont);txt(ctx,`Page ${page}/${total}`,s(1900),s(380),18,800,C.muted,'right');const cols=4,cw=450,startX=110,startY=560;studentNames.forEach((n,i)=>{const col=i%cols,row=Math.floor(i/cols),x=startX+col*cw,y=startY+row*95;rr(ctx,s(x),s(y),s(400),s(70),s(20),'#F4F7FB','#DCE5F0',s(2));block(ctx,n,s(x+22),s(y+44),s(360),24,17,1,800,C.ink)});return cv}

function program(bg,events,page,total){
 const {c:cv,ctx}=canvas(bg),W=cv.width,sc=W/1448,s=v=>v*sc;const first=events[0],month=first?new Date(first.date+'T12:00:00').toLocaleDateString('fr-FR',{month:'long',year:'numeric'}).toUpperCase():'PROGRAMME';txt(ctx,`RENDEZ-VOUS À VENIR — ${month}`,s(72),s(420),28,400,C.blue,'left',titleFont);txt(ctx,`PAGE ${page}/${total}`,s(1370),s(418),16,800,C.muted,'right');
 const slots=[{x:72,y:500,w:1304,h:420},{x:72,y:970,w:1304,h:420},{x:72,y:1440,w:1304,h:420}];
 events.slice(0,3).forEach((e,i)=>{const q=slots[i],a=color(e.specialty),dp=parts(e.date);rr(ctx,s(q.x),s(q.y),s(q.w),s(q.h),s(30),'rgba(255,255,255,.94)','#DCE5F0',s(3));rr(ctx,s(q.x),s(q.y),s(12),s(q.h),s(6),a);rr(ctx,s(q.x+42),s(q.y+55),s(170),s(170),s(30),'#F4F7FB');txt(ctx,dp.day,s(q.x+127),s(q.y+145),68,400,a,'center',titleFont);txt(ctx,dp.month.slice(0,4),s(q.x+127),s(q.y+195),20,400,a,'center',titleFont);block(ctx,e.title,s(q.x+255),s(q.y+100),s(900),42,28,2,400,C.ink,titleFont,1.05);chip(ctx,e.specialty||'Association Sportive',s(q.x+255),s(q.y+165),{bg:'#EEF4FB',fg:a,maxW:s(360)});info(ctx,'Catégorie',e.ageCategory||'Toutes catégories',s(q.x+255),s(q.y+275),s(330),{valueSize:24,maxLines:1});info(ctx,'Horaires',`${e.startTime||'—'}${e.endTime?' – '+e.endTime:''}`,s(q.x+610),s(q.y+275),s(280),{valueSize:25,maxLines:1});info(ctx,'Lieu',e.place||'—',s(q.x+925),s(q.y+275),s(380),{valueSize:23,maxLines:2});const d=window.app.readData(),has=(d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&c.title===e.title));if(has){rr(ctx,s(q.x+q.w-190),s(q.y+25),s(155),s(44),s(22),C.yellow);txt(ctx,'CONVOCATION',s(q.x+q.w-112),s(q.y+54),14,900,'#4C4000','center')}});txt(ctx,'BON SAUVEUR – SAINT-LÔ',W/2,s(1980),16,900,C.blue,'center');return cv
}

window.app.exportConvocation=async id=>{try{await ensureFonts();const {jsPDF}=window.jspdf||{};if(!jsPDF)throw new Error('Module PDF indisponible');const d=window.app.readData(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');const bg=await template('conv'),studentNames=names(c),chunks=[studentNames.slice(0,18)];for(let i=18;i<studentNames.length;i+=40)chunks.push(studentNames.slice(i,i+40));const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a3',compress:true});chunks.forEach((chunk,i)=>{if(i)doc.addPage('a3','landscape');const cv=i===0?convFirst(bg,c,studentNames):convMore(bg,c,chunk,i+1,chunks.length);doc.addImage(cv.toDataURL('image/png'),'PNG',0,0,420,297,'','FAST')});doc.save(`Convocation_${clean(c.title||c.activity||'AS')}.pdf`)}catch(e){console.error(e);alert('Impossible de générer la convocation PDF.')}};
window.app.exportCalendarPDF=async()=>{try{await ensureFonts();const {jsPDF}=window.jspdf||{};if(!jsPDF)throw new Error('Module PDF indisponible');const d=window.app.readData(),sp=window.app.roleSpecialty();let events=(d.events||[]).filter(e=>!sp||e.specialty===sp).slice().sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')));if(!events.length)return alert('Aucun événement à exporter.');const bg=await template('prog'),pages=Math.ceil(events.length/3),doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a3',compress:true});for(let p=0;p<pages;p++){if(p)doc.addPage('a3','portrait');const chunk=events.slice(p*3,p*3+3),cv=program(bg,chunk,p+1,pages);doc.addImage(cv.toDataURL('image/png'),'PNG',0,0,297,420,'','FAST')}doc.save(sp?`Programme_${clean(sp)}.pdf`:'Programme_AS_Bon_Sauveur.pdf')}catch(e){console.error(e);alert('Impossible de générer le calendrier PDF.')}};
window.ASV20_EXPORTS={version:'v20-20260909-1'};
})();
