(() => {
'use strict';
const cfg=window.APP_CONFIG||{};
const root=document.getElementById('app');
const CLASSES=['6e AVIGNON','6e Georges BIZET','6e Paul CEZANNE','6e Alphonse DAUDET','5e Jacqueline AURIOL','5e Adrienne BOLLAND','5e Bessie COLEMAN','5e Elise DEROCHE','4e ESTANGUET','4e FLESSEL','4e Cyril MORE','4e DELAUNAY','3e Antonio GAUDI','3e BARCELONE','3e CASTILLE','3e DALI','Seconde Pro ECP','Seconde Pro Maslow','Seconde Pro Henderson','Seconde GT','Première Pro ECP','Première Pro Curie','Première Pro Pasteur','Première ST2S','Terminale ST2S','Terminale ASSP'];
const AGE_CATEGORIES=['Benjamin','Benjamine','Minime fille','Minime garçon','Lycéen','Lycéenne','Toutes catégories'];
const LICENSE_CATEGORIES=['Benjamin','Benjamine','Minime fille','Minime garçon','Section foot Benjamin','Section foot Benjamine','Lycéen','Lycéenne'];
const SPECIALTIES=['Association Sportive','Section Football','Option Escalade','Sport-études Gymnastique'];
const PAYMENTS=['Chèque','Espèces','Ticket Spot 50','Cart’@too','Virement'];
const ACTIVITIES=['Réunion d’organisation','AG UGSEL Manche','Renforcement - Relaxation','Kayak','Volley-Ball','Handball','Cross de l’établissement','Cross-Country','Trisports','Football','Futsal','Basket-ball','Badminton','Tennis de table','Escalade','Gymnastique','Athlétisme','Course d’orientation','Natation','VTT','Laser Run','Multisports','Autre'];
const LEVELS=['Entraînement','District','Comité','Territoire','National','Autre'];
const ROLES={public:'Élèves / Parents',educator_escalade:'Option Escalade',educator_gymnastique:'Sport-études Gymnastique',educator_football:'Section Football',teacher_as:'Association Sportive',admin:'Administrateur'};
const ROLE_SPECIALTY={educator_escalade:'Option Escalade',educator_gymnastique:'Sport-études Gymnastique',educator_football:'Section Football'};
const SPECIALTY_META={
 'Association Sportive':{css:'as',logo:'assets/logo-as.png',short:'AS'},
 'Section Football':{css:'football',logo:'assets/logo-football.png',short:'Football'},
 'Option Escalade':{css:'escalade',logo:'assets/logo-escalade.png',short:'Escalade'},
 'Sport-études Gymnastique':{css:'gymnastique',logo:'assets/logo-gymnastique.png',short:'Gymnastique'}
};
const seed={
 events:[
  {id:'e1',title:'Entraînement AS multisports',ageCategory:'Toutes catégories',specialty:'Association Sportive',date:'2026-09-09',startTime:'13:30',endTime:'16:00',place:'Gymnase du Bon Sauveur'},
  {id:'e2',title:'Entraînement section football',ageCategory:'Benjamin',specialty:'Section Football',date:'2026-09-10',startTime:'15:30',endTime:'17:30',place:'Stade'},
  {id:'e3',title:'Option escalade',ageCategory:'Minime fille',specialty:'Option Escalade',date:'2026-09-10',startTime:'15:30',endTime:'18:00',place:'Salle d’escalade'},
  {id:'e4',title:'Sport-études gymnastique',ageCategory:'Toutes catégories',specialty:'Sport-études Gymnastique',date:'2026-09-08',startTime:'14:30',endTime:'18:45',place:'Saint-Loise Gymnastique'},
  {id:'e5',title:'UGSEL Football — secteur',ageCategory:'Benjamin',specialty:'Section Football',date:'2026-09-23',startTime:'12:45',endTime:'17:30',place:'Saint-Lô',convocationId:'c1'}
 ],
 documents:[
  {id:'d1',title:'Règlement de l’Association Sportive',specialty:'Association Sportive',date:'2026-09-01',description:'Règles de fonctionnement et informations utiles.',url:'#',featured:true},
  {id:'d2',title:'Horaires section football',specialty:'Section Football',date:'2026-09-01',description:'Horaires hebdomadaires de la section.',url:'#',featured:true},
  {id:'d3',title:'Horaires option escalade',specialty:'Option Escalade',date:'2026-09-01',description:'Organisation et horaires de l’option.',url:'#',featured:true}
 ],
 products:[
  {id:'p1',name:'Sweat officiel',description:'Sweat aux couleurs de l’Association Sportive.',price:35,sizes:['XS','S','M','L','XL'],deadline:'2026-10-05',paymentLink:'',active:true},
  {id:'p2',name:'T-shirt Association Sportive',description:'T-shirt technique.',price:15,sizes:['XS','S','M','L','XL'],deadline:'2026-10-05',paymentLink:'',active:true}
 ],
 orders:[
  {id:'o1',productId:'p2',studentName:'MARTIN Léo',className:'5e Jacqueline AURIOL',size:'M',quantity:1,paymentMethod:'Chèque',paid:true,ready:false,distributed:false,createdAt:'2026-09-07'}
 ],
 students:[
  {id:'s1',fullName:'DUPONT Emma',className:'6e AVIGNON',specialty:'Sport-études Gymnastique'},
  {id:'s2',fullName:'MARTIN Léo',className:'5e Jacqueline AURIOL',specialty:'Section Football'},
  {id:'s3',fullName:'BERNARD Inès',className:'4e Cyril MORE',specialty:'Option Escalade'},
  {id:'s4',fullName:'THOMAS Jade',className:'5e Bessie COLEMAN',specialty:'Section Football'}
 ],
 appreciations:[
  {id:'a1',studentId:'s2',term:1,text:'Très bonne implication dans les séances.',status:'validated'},
  {id:'a2',studentId:'s3',term:1,text:'Bon trimestre.',status:'draft'}
 ],
 licenses:[
  {id:'l1',studentId:'s1',fullName:'DUPONT Emma',className:'6e AVIGNON',category:'Benjamine',contribution:'Chèque',paymentStatus:'Payé',amount:20,charterSigned:'Oui',sectionOption:'Sport-études Gymnastique'},
  {id:'l2',studentId:'s2',fullName:'MARTIN Léo',className:'5e Jacqueline AURIOL',category:'Benjamin',contribution:'Espèces',paymentStatus:'Payé',amount:20,charterSigned:'Oui',sectionOption:'Section Football'},
  {id:'l3',studentId:'s3',fullName:'BERNARD Inès',className:'4e Cyril MORE',category:'Minime fille',contribution:'Ticket Spot 50',paymentStatus:'En attente',amount:20,charterSigned:'Oui',sectionOption:'Option Escalade'},
  {id:'l4',studentId:'s4',fullName:'THOMAS Jade',className:'5e Bessie COLEMAN',category:'Benjamine',contribution:'Cart’@too',paymentStatus:'Payé',amount:20,charterSigned:'Oui',sectionOption:'Section Football'}
 ],
 convocations:[
  {id:'c1',title:'UGSEL Football — secteur',activity:'Football',ageCategory:'Benjamin',specialty:'Section Football',date:'2026-09-23',departure:'12:45',returnTime:'17:30',place:'Saint-Lô',meetingPoint:'Porche du Bon Sauveur',equipment:'Tenue de sport, gourde',extraInfo:'Prévoir le repas du midi.',studentIds:['s2','s4']}
 ],
 reports:[
  {id:'b1',date:'2026-09-02',activity:'Multisports',teacher:'M. RIGAUX',level:'Entraînement',place:'Bon Sauveur',category:'Toutes catégories',participants:34,comment:'Belle reprise, forte participation.'}
 ],
 termSettings:{
  1:{deadline:'2026-11-30',end:'2026-12-11'},
  2:{deadline:'2027-03-12',end:'2027-03-19'},
  3:{deadline:'2027-06-11',end:'2027-06-25'}
 },
 instagram:[], users:[]
};
const state={route:'home',role:cfg.demoMode?(localStorage.getItem('bs-demo-role-v4')||'public'):'public',data:load(),dark:localStorage.getItem('bs-dark')==='1',term:1,filters:{},search:'',selectedConv:null};
if(state.dark)document.body.classList.add('dark');
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const raw=localStorage.getItem('bs-app-data-v4');if(raw)return mergeDefaults(JSON.parse(raw));const old=localStorage.getItem('bs-app-data-v3');if(old)return migrate(JSON.parse(old));}catch(e){console.warn(e)}return clone(seed)}
function mergeDefaults(x){return {...clone(seed),...x,termSettings:{...seed.termSettings,...(x.termSettings||{})}}}
function migrate(x){const d=mergeDefaults(x||{});d.events=(d.events||[]).map(e=>({id:e.id||uid('e'),title:e.title||'',ageCategory:e.ageCategory||'Toutes catégories',specialty:e.specialty||legacySpecialty(e.category),date:e.date||today(),startTime:e.startTime||e.time||'',endTime:e.endTime||'',place:e.place||'',convocationId:e.convocationId||null}));d.documents=(d.documents||[]).map(o=>({...o,specialty:o.specialty||legacySpecialty(o.category)}));d.licenses=(d.licenses||[]).map(l=>({...l,category:l.category==='Lycée'?'Lycéen':l.category,paymentStatus:l.paymentStatus||'En attente',amount:Number(l.amount||20),sectionOption:normalizeSpecialty(l.sectionOption)}));d.convocations=(d.convocations||[]).map(c=>({...c,activity:c.activity||inferActivity(c.title),ageCategory:c.ageCategory||'Toutes catégories',specialty:c.specialty||legacySpecialty(c.category)}));d.reports=(d.reports||[]).map(r=>({...r,teacher:r.teacher||'',level:r.level||'Entraînement',place:r.place||'',category:r.category||'Toutes catégories'}));return d}
function legacySpecialty(c){return c==='Football'?'Section Football':c==='Escalade'?'Option Escalade':c==='Gymnastique'?'Sport-études Gymnastique':'Association Sportive'}
function normalizeSpecialty(s){if(s==='Sport-Études Gym')return 'Sport-études Gymnastique';if(s==='AS'||s==='Aucune')return 'Association Sportive';return s||'Association Sportive'}
function inferActivity(t=''){const s=t.toLowerCase();return s.includes('foot')?'Football':s.includes('escal')?'Escalade':s.includes('gym')?'Gymnastique':s.includes('cross')?'Cross-Country':s.includes('kayak')?'Kayak':'Autre'}
function save(){localStorage.setItem('bs-app-data-v4',JSON.stringify(state.data))}
function uid(p='x'){return p+Math.random().toString(36).slice(2,10)}
function esc(v=''){return String(v??'').replace(/[&<>\"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[s]))}
function today(){return new Date().toISOString().slice(0,10)}
function fmt(d){if(!d)return'—';return new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
function fmtLong(d){if(!d)return'—';return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function roleLabel(r=state.role){return ROLES[r]||'Utilisateur'}
function isTeacher(){return state.role==='teacher_as'||state.role==='admin'}
function isAdmin(){return state.role==='admin'}
function isEdu(){return state.role.startsWith('educator_')}
function roleSpecialty(){return ROLE_SPECIALTY[state.role]||null}
function meta(s){return SPECIALTY_META[s]||SPECIALTY_META['Association Sportive']}
function badge(s){const m=meta(s);return `<span class="badge ${m.css}">${esc(s)}</span>`}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function initials(){return roleLabel().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function nav(){return state.role==='public'?[['home','⌂','Accueil'],['convocations','✓','Convocation'],['calendar','▣','Calendrier'],['shop','◫','Boutique'],['documents','▤','Documents']]:[['home','⌂','Accueil'],['calendar','▣','Calendrier'],['documents','▤','Documents'],['shop','◫','Boutique'],['more','•••','Plus']]}
function layout(content){return `<div class="app-shell"><header class="topbar"><div class="brand" onclick="app.go('home')"><img src="assets/logo-as.png" alt="Logo AS"><div><div class="brand-title">ASSOCIATION SPORTIVE DU BON SAUVEUR</div><div class="brand-sub">Saint-Lô</div></div></div><div class="top-actions"><button class="icon-btn" onclick="app.theme()" aria-label="Thème">${state.dark?'☀':'☾'}</button><button class="profile-btn" onclick="app.profile()"><span class="avatar">${initials()}</span><span class="profile-name">${esc(roleLabel())}</span></button></div></header><main>${content}</main><nav class="bottom-nav">${nav().map(([r,i,l])=>`<button class="nav-item ${state.route===r?'active':''}" onclick="app.go('${r}')"><span class="nav-ico">${i}</span><span>${l}</span></button>`).join('')}</nav></div>`}
function render(){const pages={home:homePage,calendar:calendarPage,documents:documentsPage,shop:shopPage,convocations:convocationsPage,more:morePage,appreciations:appreciationsPage,licenses:licensesPage,reports:reportsPage,orders:ordersPage,admin:adminPage};root.innerHTML=layout((pages[state.route]||homePage)())}
function dateBox(d){const x=new Date(d+'T12:00:00');return `<div class="date-badge"><div class="day">${x.getDate()}</div><div class="month">${x.toLocaleDateString('fr-FR',{month:'short'}).replace('.','')}</div></div>`}
function convForEvent(e){return state.data.convocations.find(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&(!e.title||c.title===e.title)))}
function weekBounds(){const n=new Date(),day=(n.getDay()+6)%7,s=new Date(n);s.setDate(n.getDate()-day);const e=new Date(s);e.setDate(s.getDate()+6);return [s.toISOString().slice(0,10),e.toISOString().slice(0,10)]}
function homePage(){const[b,e]=weekBounds();let events=state.data.events.filter(x=>x.date>=b&&x.date<=e).sort(byDate);if(!events.length)events=state.data.events.filter(x=>x.date>=today()).sort(byDate).slice(0,6);const docs=state.data.documents.filter(x=>x.featured).slice(0,3);return `<div class="container"><section class="hero"><div class="hero-row"><div><div class="kicker hero-kicker">SAINT-LÔ · ASSOCIATION SPORTIVE</div><h1>L’Association Sportive<br>du Bon Sauveur</h1><p>Compétitions, entraînements, convocations et informations : retrouvez ici toute l’actualité sportive du Bon Sauveur.</p></div><div class="hero-logo-stack">${Object.values(SPECIALTY_META).map(m=>`<div class="hero-logo"><img src="${m.logo}"></div>`).join('')}</div></div></section><div class="section-head"><div><h2>Cette semaine</h2><p>Les dates importantes et les convocations associées.</p></div><button class="link-btn" onclick="app.go('calendar')">Tout voir →</button></div><div class="week-list">${events.map(eventCard).join('')||empty('Aucune date cette semaine.')}</div><div class="home-duo"><section><div class="section-head compact"><div><h2>Documents importants</h2><p>Les documents à avoir sous la main.</p></div><button class="link-btn" onclick="app.go('documents')">Tous →</button></div><div class="grid">${docs.map(docHomeCard).join('')||empty('Aucun document important.')}</div></section><section><div class="section-head compact"><div><h2>En images</h2><p>Les dernières publications de @as_bs50.</p></div><button class="link-btn" onclick="app.external('${esc(cfg.instagramUrl||'https://www.instagram.com/as_bs50/')}')">Instagram ↗</button></div>${instagramBlock()}</section></div></div>`}
function eventCard(e){const c=convForEvent(e);return `<article class="card week-card">${dateBox(e.date)}<div><div class="event-title">${esc(e.title)}</div><div class="meta"><span>${esc(e.startTime||'')}</span>${e.endTime?`<span>→ ${esc(e.endTime)}</span>`:''}<span>• ${esc(e.place||'')}</span></div><div class="meta">${esc(e.ageCategory||'')}</div></div><div class="week-tags">${badge(e.specialty)}${c?`<button class="convocation-chip" onclick="app.openConv('${c.id}')">Voir la convocation</button>`:''}</div></article>`}
function docHomeCard(d){return `<article class="card home-doc"><div class="doc-icon">PDF</div><div><div class="event-title">${esc(d.title)}</div><div class="meta">${fmt(d.date)}</div></div><button class="text-btn" onclick="app.doc('${d.id}')">Ouvrir →</button></article>`}
function instagramBlock(){const posts=state.data.instagram||[];if(posts.length)return `<div class="photo-strip">${posts.slice(0,8).map(p=>`<button class="photo-card" onclick="app.external('${esc(p.permalink||cfg.instagramUrl||'')}')"><img src="${esc(p.imageUrl)}"><span>${esc((p.caption||'Publication Instagram').slice(0,70))}</span></button>`).join('')}</div>`;return `<div class="photo-empty"><img src="assets/logo-as.png"><div><strong>@as_bs50</strong><p>Le flux automatique est prêt. La connexion officielle Instagram/Meta est nécessaire pour afficher les photos directement dans l’application.</p><button class="btn secondary tiny" onclick="app.external('${esc(cfg.instagramUrl||'https://www.instagram.com/as_bs50/')}')">Voir Instagram</button></div></div>`}
function byDate(a,b){return (a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||''))}
function calendarPage(){let a=state.data.events.slice().sort(byDate);const q=(state.search||'').toLowerCase();if(q)a=a.filter(x=>`${x.title} ${x.place} ${x.ageCategory} ${x.specialty}`.toLowerCase().includes(q));return `<div class="container"><div class="page-title"><div><div class="kicker">CALENDRIER</div><h1>À venir</h1><p>Compétitions, entraînements et rendez-vous.</p></div><div class="top-actions-inline">${isTeacher()?'<button class="btn" onclick="app.editEvent()">+ Événement</button>':''}<button class="btn secondary" onclick="app.exportCalendarPDF(false)">PDF</button><button class="btn yellow" onclick="app.exportCalendarPDF(true)">PDF affichage</button><button class="btn secondary" onclick="app.exportExcel('calendar')">Excel</button></div></div><input class="search" placeholder="Rechercher…" value="${esc(state.search)}" oninput="app.search(this.value)"><div class="grid" style="margin-top:14px">${a.map(eventCard).join('')}</div></div>`}
function documentsPage(){return `<div class="container"><div class="page-title"><div><div class="kicker">DOCUMENTS</div><h1>Documents</h1></div>${isTeacher()?'<button class="btn" onclick="app.editDocument()">+ Document</button>':''}</div><div class="grid grid-2">${state.data.documents.map(d=>`<article class="card doc-card"><div class="doc-icon">PDF</div><div class="grow"><div class="event-title">${esc(d.title)}</div><p class="info-text">${esc(d.description||'')}</p><div class="actions"><button class="btn secondary" onclick="app.doc('${d.id}')">Consulter</button><button class="btn" onclick="app.downloadDoc('${d.id}')">Télécharger</button></div></div></article>`).join('')}</div></div>`}
function shopPage(){const products=state.data.products.filter(p=>p.active!==false);return `<div class="container"><div class="page-title"><div><div class="kicker">BOUTIQUE</div><h1>Boutique AS</h1><p>Commandez les articles pour votre enfant.</p></div><div class="top-actions-inline">${isTeacher()?'<button class="btn secondary" onclick="app.go(\'orders\')">Gérer les commandes</button><button class="btn" onclick="app.editProduct()">+ Produit</button>':''}</div></div><div class="grid grid-2">${products.map(p=>`<article class="card product"><div class="product-photo"><img src="assets/logo-as.png"></div><div class="product-body"><div class="event-title">${esc(p.name)}</div><p class="info-text">${esc(p.description||'')}</p><div class="product-price">${money(p.price)}</div><div class="meta">Commande avant le ${fmt(p.deadline)}</div><button class="btn yellow" onclick="app.order('${p.id}')">Commander</button></div></article>`).join('')}</div></div>`}
function ordersPage(){if(!isTeacher())return denied();const rows=state.data.orders.slice().sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));const pending=rows.filter(x=>!x.paid).length,toDist=rows.filter(x=>x.paid&&!x.distributed).length;return `<div class="container"><div class="page-title"><div><div class="kicker">BOUTIQUE</div><h1>Gestion des commandes</h1><p>Paiement, préparation et distribution.</p></div><button class="btn" onclick="app.exportExcel('orders')">Exporter Excel</button></div><div class="stats-row"><div class="card stat"><strong>${rows.length}</strong><span>Commandes</span></div><div class="card stat"><strong>${pending}</strong><span>Paiements en attente</span></div><div class="card stat"><strong>${toDist}</strong><span>À distribuer</span></div></div><div class="card table-card"><table class="admin-table"><thead><tr><th>Élève</th><th>Classe</th><th>Produit</th><th>Taille</th><th>Qté</th><th>Paiement</th><th>Payé</th><th>Prêt</th><th>Distribué</th><th>Date</th></tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.studentName)}</strong></td><td>${esc(o.className)}</td><td>${esc(productName(o.productId))}</td><td>${esc(o.size)}</td><td>${o.quantity||1}</td><td>${esc(o.paymentMethod)}</td><td><button class="status-toggle ${o.paid?'on':''}" onclick="app.toggleOrder('${o.id}','paid')">${o.paid?'Payé':'À payer'}</button></td><td><button class="status-toggle ${o.ready?'on':''}" onclick="app.toggleOrder('${o.id}','ready')">${o.ready?'Prête':'À préparer'}</button></td><td><button class="status-toggle ${o.distributed?'on':''}" onclick="app.toggleOrder('${o.id}','distributed')">${o.distributed?'Distribuée':'À distribuer'}</button></td><td>${fmt(o.createdAt)}</td></tr>`).join('')}</tbody></table></div></div>`}
function productName(id){return state.data.products.find(p=>p.id===id)?.name||'Produit'}
function convocationsPage(){return `<div class="container"><div class="page-title"><div><div class="kicker">CONVOCATIONS</div><h1>Convocations</h1><p>Consultez l’activité, les horaires et les élèves convoqués.</p></div><div class="top-actions-inline">${isTeacher()?'<button class="btn" onclick="app.editConv()">+ Convocation</button><button class="btn secondary" onclick="app.exportExcel(\'convocations\')">Excel</button>':''}</div></div><div class="grid">${state.data.convocations.slice().sort(byDate).map(convCard).join('')}</div></div>`}
function convCard(c){const names=(c.studentIds||[]).map(studentName).filter(Boolean);return `<article class="card convocation-card clickable" onclick="app.openConv('${c.id}')"><div class="row-between"><div><div class="kicker">${esc(c.activity||'Activité')}</div><div class="event-title">${esc(c.activity||'')} — ${esc(c.title)}</div><div class="meta"><span>${fmtLong(c.date)}</span><span>• ${esc(c.place||'')}</span></div></div>${badge(c.specialty)}</div><div class="convocation-names"><strong>Élèves convoqués :</strong> ${names.length?esc(names.join(' · ')):'Aucun élève sélectionné'}</div></article>`}
function studentName(id){return state.data.students.find(s=>s.id===id)?.fullName||state.data.licenses.find(l=>l.studentId===id)?.fullName||''}
function morePage(){const tiles=[];if(isEdu())tiles.push(['✎','Appréciations','appreciations']);if(isTeacher()){tiles.push(['✓','Convocations','convocations'],['⚑','Licences','licenses'],['↗','Bilans AS','reports'],['◫','Commandes','orders']);if(isAdmin())tiles.push(['⚙','Administration','admin'])}return `<div class="container"><div class="page-title"><div><div class="kicker">PLUS</div><h1>Outils</h1><p>Les fonctions adaptées à votre espace.</p></div></div><div class="grid more-grid">${tiles.map(([i,t,r])=>`<button class="card more-tile" onclick="app.go('${r}')"><span class="big-icon">${i}</span><strong>${t}</strong></button>`).join('')}</div></div>`}
function appreciationsPage(){if(!isEdu()&&!isAdmin())return denied();const sp=roleSpecialty()||'Tous';const licensed=state.data.licenses.filter(l=>isAdmin()||l.sectionOption===sp);const term=state.term;const settings=state.data.termSettings[term]||{};return `<div class="container"><div class="page-title"><div><div class="kicker">${esc(sp)}</div><h1>Appréciations</h1><p>Suivi annuel et transfert rapide vers ÉcoleDirecte.</p></div><button class="btn secondary" onclick="app.exportExcel('appreciations')">Exporter Excel</button></div><div class="term-tabs">${[1,2,3].map(t=>`<button class="term-tab ${t===term?'active':''}" onclick="app.setTerm(${t})">Trimestre ${t}</button>`).join('')}</div><div class="card term-info"><div><span>Date limite de saisie</span><strong>${fmtLong(settings.deadline)}</strong></div><div><span>Fin du trimestre</span><strong>${fmtLong(settings.end)}</strong></div><div class="grammar-indicator">✓ Vérification orthographe + grammaire à la validation</div></div><div class="card table-card"><table class="admin-table appreciation-table"><thead><tr><th>Élève</th><th>Trimestre précédent</th><th>Appréciation</th><th>Statut</th><th>Copier</th></tr></thead><tbody>${licensed.map(l=>appRow(l,term)).join('')}</tbody></table></div></div>`}
function appRow(l,term){const cur=getApp(l.studentId,term),prev=term>1?getApp(l.studentId,term-1):null;return `<tr><td><strong>${esc(l.fullName)}</strong><div class="meta">${esc(l.className)}</div></td><td class="previous-app">${prev?.text?esc(prev.text):'<span class="muted">—</span>'}</td><td><textarea id="app-${l.studentId}" class="appreciation-text" placeholder="Saisir l’appréciation…">${esc(cur?.text||'')}</textarea><div class="inline-check"><button class="btn tiny" onclick="app.validateApp('${l.studentId}',${term})">Vérifier & valider</button></div></td><td><span class="status-pill ${cur?.status==='validated'?'ok':'todo'}">${cur?.status==='validated'?'VALIDÉ':'À FAIRE'}</span></td><td><button class="copy-btn" title="Copier l’appréciation" onclick="app.copyApp('${l.studentId}',${term})">⧉</button></td></tr>`}
function getApp(id,term){return state.data.appreciations.find(a=>a.studentId===id&&Number(a.term)===Number(term))}
function licensesPage(){if(!isTeacher())return denied();const f=state.filters.licenses||{};let rows=state.data.licenses.slice();if(f.category)rows=rows.filter(x=>x.category===f.category);if(f.specialty)rows=rows.filter(x=>x.sectionOption===f.specialty);if(f.paymentStatus)rows=rows.filter(x=>x.paymentStatus===f.paymentStatus);if(f.className)rows=rows.filter(x=>x.className===f.className);if(f.paymentMethod)rows=rows.filter(x=>x.contribution===f.paymentMethod);const total=rows.filter(x=>x.paymentStatus==='Payé').reduce((s,x)=>s+Number(x.amount||0),0);return `<div class="container"><div class="page-title"><div><div class="kicker">GESTION</div><h1>Licences</h1><p>La base centrale des élèves licenciés.</p></div><div class="top-actions-inline"><button class="btn secondary" onclick="app.exportExcel('licenses')">Exporter Excel</button><button class="btn" onclick="app.editLicense()">+ Licence</button></div></div><div class="filter-panel">${selectFilter('category','Catégorie',['',...LICENSE_CATEGORIES],f.category)}${selectFilter('specialty','Spécialité',['',...SPECIALTIES],f.specialty)}${selectFilter('className','Classe',['',...CLASSES],f.className)}${selectFilter('paymentStatus','Paiement',['','Payé','En attente'],f.paymentStatus)}${selectFilter('paymentMethod','Mode',['',...PAYMENTS],f.paymentMethod)}<button class="btn secondary tiny" onclick="app.clearLicenseFilters()">Effacer</button></div><div class="card mini-accounting"><span>${rows.length} licence(s)</span><strong>${money(total)} encaissés dans la sélection</strong></div><div class="card table-card"><table class="admin-table"><thead><tr><th>Nom & prénom</th><th>Classe</th><th>Catégorie</th><th>Spécialité</th><th>Cotisation</th><th>Statut</th><th>Montant</th><th>Charte</th><th></th></tr></thead><tbody>${rows.map(l=>`<tr><td><strong>${esc(l.fullName)}</strong></td><td>${esc(l.className)}</td><td>${esc(l.category)}</td><td>${esc(l.sectionOption)}</td><td>${esc(l.contribution)}</td><td><span class="status-pill ${l.paymentStatus==='Payé'?'ok':'todo'}">${esc(l.paymentStatus)}</span></td><td>${money(l.amount)}</td><td>${esc(l.charterSigned)}</td><td><button class="btn secondary tiny" onclick="app.editLicense('${l.id}')">Modifier</button></td></tr>`).join('')}</tbody></table></div></div>`}
function selectFilter(key,label,items,val){return `<label class="filter-field"><span>${label}</span><select onchange="app.licenseFilter('${key}',this.value)">${items.map(x=>`<option value="${esc(x)}" ${x===val?'selected':''}>${esc(x||'Tous')}</option>`).join('')}</select></label>`}
function reportsPage(){if(!isTeacher())return denied();const rows=state.data.reports.slice().sort((a,b)=>b.date.localeCompare(a.date));return `<div class="container"><div class="page-title"><div><div class="kicker">BILANS</div><h1>Bilans AS</h1><p>Un bilan par semaine, exploitable pour vos déclarations.</p></div><div class="top-actions-inline"><button class="btn secondary" onclick="app.exportExcel('reports')">Exporter Excel</button><button class="btn" onclick="app.editReport()">+ Bilan</button></div></div><div class="grid">${rows.map(r=>`<article class="card report-card"><div class="row-between"><div><div class="event-title">${esc(r.activity)}</div><div class="meta">${fmt(r.date)} · ${esc(r.teacher||'')} · ${esc(r.participants||0)} participant(s)</div></div><button class="btn secondary tiny" onclick="app.editReport('${r.id}')">Modifier</button></div><div class="report-grid"><span><b>Niveau</b>${esc(r.level||'')}</span><span><b>Lieu</b>${esc(r.place||'')}</span><span><b>Catégorie</b>${esc(r.category||'')}</span></div>${r.comment?`<p class="info-text">${esc(r.comment)}</p>`:''}</article>`).join('')}</div></div>`}
function adminPage(){if(!isAdmin())return denied();const t=state.data.termSettings;return `<div class="container"><div class="page-title"><div><div class="kicker">ADMINISTRATION</div><h1>Réglages</h1></div></div><div class="grid grid-2"><div class="card"><h2>Dates des trimestres</h2>${[1,2,3].map(n=>`<div class="admin-term"><strong>Trimestre ${n}</strong><label>Date limite<input type="date" id="td-${n}" value="${esc(t[n]?.deadline||'')}"></label><label>Fin du trimestre<input type="date" id="te-${n}" value="${esc(t[n]?.end||'')}"></label></div>`).join('')}<button class="btn" onclick="app.saveTermDates()">Enregistrer</button></div><div class="card"><h2>Instagram</h2><p class="info-text">Compte officiel : <strong>@as_bs50</strong></p><button class="btn secondary" onclick="app.external('${esc(cfg.instagramUrl||'https://www.instagram.com/as_bs50/')}')">Ouvrir le compte</button><p class="note">Pour afficher automatiquement les photos, la connexion officielle Meta/Instagram doit être activée côté serveur.</p></div><div class="card"><h2>Exports</h2><p class="info-text">Les exports Excel sont disponibles directement dans chaque rubrique : licences, convocations, bilans, commandes, appréciations et calendrier.</p></div></div></div>`}
function denied(){return `<div class="container">${empty('Cet espace n’est pas disponible pour ce profil.')}</div>`}
function empty(txt){return `<div class="empty">${esc(txt)}</div>`}
function money(v){return `${Number(v||0).toFixed(2).replace('.',',')} €`}
function optionList(items,current){return items.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
function modal(title,body,wide=false){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal ${wide?'wide':''}"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" onclick="app.closeModal()">×</button></div>${body}</div></div>`)}
function modalForm(fields,submitLabel='Enregistrer'){return `<form onsubmit="event.preventDefault();app.submitModal(this)" class="form-grid">${fields}<div class="field full modal-actions"><button class="btn" type="submit">${submitLabel}</button></div></form>`}
function f(name,label,type='text',value='',opts=null,full=false){if(type==='select')return `<label class="field ${full?'full':''}"><span>${label}</span><select name="${name}">${optionList(opts||[],value)}</select></label>`;if(type==='textarea')return `<label class="field ${full?'full':''}"><span>${label}</span><textarea name="${name}">${esc(value)}</textarea></label>`;return `<label class="field ${full?'full':''}"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}"></label>`}
const modalHandlers={};
function setModalHandler(fn){modalHandlers.submit=fn}
async function checkFrench(text){const url=cfg.languageToolUrl||'https://api.languagetool.org/v2/check';const params=new URLSearchParams({text,language:'fr'});const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Service indisponible');return r.json()}
function applyCorrections(text,matches){let out=text;const sorted=[...matches].filter(m=>m.replacements?.length).sort((a,b)=>b.offset-a.offset);for(const m of sorted){out=out.slice(0,m.offset)+m.replacements[0].value+out.slice(m.offset+m.length)}return out}
function excelBook(sheets,filename){if(!window.XLSX){toast('Module Excel en cours de chargement. Réessayez dans quelques secondes.');return}const wb=XLSX.utils.book_new();for(const [name,rows] of Object.entries(sheets)){const ws=XLSX.utils.json_to_sheet(rows.length?rows:[{Information:'Aucune donnée'}]);XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31))}XLSX.writeFile(wb,filename)}
function exportExcel(kind){if(kind==='licenses')return exportLicenses();if(kind==='reports')return excelBook({'Bilans AS':state.data.reports.map(r=>({'Date':r.date,'Activité':r.activity,'Professeur référent':r.teacher,'Niveau':r.level,'Lieu':r.place,'Catégorie':r.category,"Nombre d'élèves":r.participants,'Commentaire':r.comment||''}))},'Bilans_AS.xlsx');if(kind==='orders')return excelBook({'Commandes':state.data.orders.map(o=>({'Élève':o.studentName,'Classe':o.className,'Produit':productName(o.productId),'Taille':o.size,'Quantité':o.quantity,'Paiement':o.paymentMethod,'Payé':o.paid?'Oui':'Non','Prêt':o.ready?'Oui':'Non','Distribué':o.distributed?'Oui':'Non','Date':o.createdAt}))},'Commandes_AS.xlsx');if(kind==='appreciations')return excelBook({'Appréciations':state.data.appreciations.map(a=>{const s=state.data.students.find(x=>x.id===a.studentId)||{};return {'Élève':s.fullName||studentName(a.studentId),'Classe':s.className||'',Trimestre:a.term,'Appréciation':a.text||'','Statut':a.status||''}})},'Appreciations_AS.xlsx');if(kind==='convocations'){const rows=[];state.data.convocations.forEach(c=>(c.studentIds||[]).forEach(id=>rows.push({'Activité':c.activity,'Titre':c.title,'Catégorie':c.ageCategory,'Spécialité':c.specialty,'Date':c.date,'Lieu':c.place,'Départ':c.departure,'Retour':c.returnTime,'Point de rendez-vous':c.meetingPoint,'Élève':studentName(id)})));return excelBook({'Convocations':rows},'Convocations_AS.xlsx')}if(kind==='calendar')return excelBook({'Calendrier':state.data.events.map(e=>({'Titre':e.title,'Catégorie':e.ageCategory,'Spécialité':e.specialty,'Date':e.date,'Départ':e.startTime,'Retour':e.endTime,'Lieu':e.place,'Convocation':convForEvent(e)?'Oui':'Non'}))},'Calendrier_AS.xlsx')}
function exportLicenses(){const rows=filteredLicenses();const methods=PAYMENTS.map(p=>({Mode:p,Total:rows.filter(x=>x.paymentStatus==='Payé'&&x.contribution===p).reduce((s,x)=>s+Number(x.amount||0),0)}));const total=methods.reduce((s,x)=>s+x.Total,0);const remaining=rows.filter(x=>x.paymentStatus!=='Payé').reduce((s,x)=>s+Number(x.amount||0),0);excelBook({'Licences':rows.map(l=>({'Nom & prénom':l.fullName,'Classe':l.className,'Catégorie':l.category,'Spécialité':l.sectionOption,'Cotisation':l.contribution,'Statut paiement':l.paymentStatus,'Montant':Number(l.amount||0),'Charte signée':l.charterSigned})),'Synthèse comptable':[...methods.map(x=>({'Mode de paiement':x.Mode,'Total encaissé':x.Total})),{'Mode de paiement':'TOTAL ENCAISSÉ','Total encaissé':total},{'Mode de paiement':'RESTANT À ENCAISSER','Total encaissé':remaining}]},'Licences_AS.xlsx')}
function filteredLicenses(){const f=state.filters.licenses||{};return state.data.licenses.filter(x=>(!f.category||x.category===f.category)&&(!f.specialty||x.sectionOption===f.specialty)&&(!f.paymentStatus||x.paymentStatus===f.paymentStatus)&&(!f.className||x.className===f.className)&&(!f.paymentMethod||x.contribution===f.paymentMethod))}
async function exportCalendarPDF(poster){if(!window.jspdf?.jsPDF){toast('Module PDF en cours de chargement. Réessayez dans quelques secondes.');return}const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:poster?'landscape':'portrait',unit:'mm',format:'a4'});const events=state.data.events.slice().sort(byDate);if(!poster){doc.setFontSize(22);doc.text('Calendrier - Association Sportive du Bon Sauveur',15,18);let y=30;for(const e of events){if(y>275){doc.addPage();y=20}doc.setFontSize(12);doc.setFont(undefined,'bold');doc.text(`${fmtLong(e.date)} - ${e.title}`,15,y);doc.setFont(undefined,'normal');doc.setFontSize(10);doc.text(`${e.ageCategory} | ${e.specialty} | ${e.startTime||''}${e.endTime?' - '+e.endTime:''} | ${e.place||''}`,15,y+6);y+=15}doc.save('Calendrier_AS_Bon_Sauveur.pdf');return}const W=297,H=210;let page=0;for(let i=0;i<events.length;i+=8){if(page++)doc.addPage();doc.setFillColor(7,87,201);doc.rect(0,0,W,38,'F');doc.setTextColor(255,255,255);doc.setFontSize(25);doc.setFont(undefined,'bold');doc.text('ASSOCIATION SPORTIVE DU BON SAUVEUR',14,17);doc.setFontSize(12);doc.text('CALENDRIER DES RENDEZ-VOUS SPORTIFS',14,28);if(page===1){const logo=await imageData('assets/logo-as.png');if(logo)try{doc.addImage(logo,'PNG',258,4,27,27)}catch{}}doc.setTextColor(19,33,58);const chunk=events.slice(i,i+8);chunk.forEach((e,j)=>{const col=j%2,row=Math.floor(j/2),x=14+col*138,y=48+row*37;const m=meta(e.specialty);const rgb=m.css==='football'?[72,150,255]:m.css==='escalade'?[83,100,210]:m.css==='gymnastique'?[137,83,200]:[255,210,26];doc.setFillColor(...rgb);doc.roundedRect(x,y,132,30,4,4,'F');doc.setFillColor(255,255,255);doc.roundedRect(x+2,y+2,128,26,3,3,'F');doc.setTextColor(7,87,201);doc.setFontSize(15);doc.setFont(undefined,'bold');doc.text(new Date(e.date+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'short'}).toUpperCase(),x+6,y+10);doc.setTextColor(19,33,58);doc.setFontSize(11);doc.text(trimText(e.title,50),x+38,y+9);doc.setFont(undefined,'normal');doc.setFontSize(8.5);doc.text(trimText(`${e.ageCategory} • ${e.specialty}`,65),x+38,y+15);doc.text(trimText(`${e.startTime||''}${e.endTime?' → '+e.endTime:''} • ${e.place||''}`,65),x+38,y+21);if(convForEvent(e)){doc.setFillColor(7,87,201);doc.roundedRect(x+101,y+21,25,5,2,2,'F');doc.setTextColor(255,255,255);doc.setFontSize(6.5);doc.text('CONVOCATION',x+103,y+24.7)}});doc.setFillColor(255,210,26);doc.rect(0,H-8,W,8,'F')}doc.save('Calendrier_Affichage_AS_Bon_Sauveur.pdf')}
function trimText(t,n){t=String(t||'');return t.length>n?t.slice(0,n-1)+'…':t}
async function loadInstagram(){try{let endpoint=cfg.instagramFeedEndpoint||'';if(!endpoint&&cfg.supabaseUrl)endpoint=cfg.supabaseUrl.replace(/\/$/,'')+'/functions/v1/instagram-feed';if(!endpoint)return;const headers={};if(cfg.supabaseAnonKey){headers.apikey=cfg.supabaseAnonKey;headers.Authorization='Bearer '+cfg.supabaseAnonKey}const r=await fetch(endpoint,{headers});if(!r.ok)return;const j=await r.json();const a=Array.isArray(j)?j:(j.data||[]);state.data.instagram=a.filter(x=>!x.media_type||['IMAGE','CAROUSEL_ALBUM'].includes(x.media_type)).slice(0,10).map(x=>({imageUrl:x.media_url||x.thumbnail_url,caption:x.caption||'',permalink:x.permalink||cfg.instagramUrl||''}));save();render()}catch(e){console.warn('Instagram:',e)}}
async function imageData(url){try{const r=await fetch(url);const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b)})}catch{return null}}
const app={
 go(r){state.route=r;state.search='';render()},theme(){state.dark=!state.dark;document.body.classList.toggle('dark',state.dark);localStorage.setItem('bs-dark',state.dark?'1':'0');render()},search(v){state.search=v;render()},external(u){if(u)window.open(u,'_blank','noopener')},closeModal(){document.getElementById('modal')?.remove()},submitModal(form){modalHandlers.submit?.(new FormData(form),form)},exportExcel,exportCalendarPDF,
 profile(){if(!cfg.demoMode){modal('Connexion',`<p class="note">La connexion sécurisée sera active dès que Supabase sera configuré.</p>`);return}modal('Choisir un espace',`<p class="note">Mode de démonstration.</p><div class="role-grid">${Object.entries(ROLES).map(([r,l])=>`<button class="role-btn ${r===state.role?'active':''}" onclick="app.setRole('${r}')"><strong>${esc(l)}</strong></button>`).join('')}</div>`)},
 setRole(r){state.role=r;localStorage.setItem('bs-demo-role-v4',r);app.closeModal();state.route='home';render()},setTerm(t){state.term=t;render()},
 doc(id){const d=state.data.documents.find(x=>x.id===id);if(!d)return;if(d.url&&d.url!=='#')window.open(d.url,'_blank');else toast('Le fichier PDF réel pourra être joint depuis l’administration.')},downloadDoc(id){const d=state.data.documents.find(x=>x.id===id);if(!d)return;if(d.url&&d.url!=='#'){const a=document.createElement('a');a.href=d.url;a.download='';a.target='_blank';a.click()}else toast('Aucun PDF réel n’est encore joint à ce document.')},
 order(id){const p=state.data.products.find(x=>x.id===id);if(!p)return;const fields=f('studentName','Nom & prénom de l’élève','text','',null,true)+f('className','Classe','select',CLASSES[0],CLASSES)+f('size','Taille','select',p.sizes?.[0]||'',p.sizes||[])+f('quantity','Quantité','number','1')+f('paymentMethod','Mode de paiement','select',PAYMENTS[0],PAYMENTS)+`<div class="field full order-summary"><strong>${esc(p.name)} — ${money(p.price)}</strong>${p.paymentLink?`<a href="${esc(p.paymentLink)}" target="_blank">Lien de virement</a>`:''}</div>`;modal('Commander',modalForm(fields,'Valider la commande'));setModalHandler(fd=>{const o={id:uid('o'),productId:id,studentName:fd.get('studentName')?.trim(),className:fd.get('className'),size:fd.get('size'),quantity:Number(fd.get('quantity')||1),paymentMethod:fd.get('paymentMethod'),paid:false,ready:false,distributed:false,createdAt:today()};if(!o.studentName)return toast('Nom et prénom obligatoires.');state.data.orders.push(o);save();app.closeModal();toast('Commande enregistrée.');render()})},
 toggleOrder(id,k){const o=state.data.orders.find(x=>x.id===id);if(!o)return;o[k]=!o[k];save();render()},
 openConv(id){const c=state.data.convocations.find(x=>x.id===id);if(!c)return;const names=(c.studentIds||[]).map(studentName).filter(Boolean);modal(`${c.activity||'Activité'} — ${c.title}`,`<div class="convocation-detail"><div class="detail-block"><span>Date</span><strong>${fmtLong(c.date)}</strong></div><div class="detail-block"><span>Lieu</span><strong>${esc(c.place||'')}</strong></div><div class="detail-block"><span>Départ</span><strong>${esc(c.departure||'')}</strong></div><div class="detail-block"><span>Retour</span><strong>${esc(c.returnTime||'')}</strong></div><div class="detail-block full"><span>Activité</span><strong>${esc(c.activity||'')}</strong></div><div class="detail-block full"><span>Point de rendez-vous</span><strong>${esc(c.meetingPoint||'')}</strong></div><div class="detail-block full"><span>Matériel</span><strong>${esc(c.equipment||'')}</strong></div><div class="detail-block full"><span>Informations</span><strong>${esc(c.extraInfo||'')}</strong></div></div><div class="convocation-students"><strong>Élèves convoqués</strong><div class="student-chip-list">${names.map(n=>`<span class="student-chip">${esc(n)}</span>`).join('')||'<span class="muted">Aucun élève.</span>'}</div></div>`,true)},
 editLicense(id){const l=id?state.data.licenses.find(x=>x.id===id):null;const fields=f('fullName','Nom & prénom','text',l?.fullName||'',null,true)+f('className','Classe','select',l?.className||CLASSES[0],CLASSES)+f('category','Catégorie','select',l?.category||LICENSE_CATEGORIES[0],LICENSE_CATEGORIES)+f('contribution','Cotisation','select',l?.contribution||PAYMENTS[0],PAYMENTS)+f('paymentStatus','Statut du paiement','select',l?.paymentStatus||'En attente',['En attente','Payé'])+f('amount','Montant','number',String(l?.amount??20))+f('charterSigned','Charte signée','select',l?.charterSigned||'Oui',['Oui','Non'])+f('sectionOption','Spécialité','select',l?.sectionOption||SPECIALTIES[0],SPECIALTIES);modal(id?'Modifier une licence':'Ajouter une licence',modalForm(fields));setModalHandler(fd=>{const obj={id:l?.id||uid('l'),studentId:l?.studentId||uid('s'),fullName:fd.get('fullName')?.trim(),className:fd.get('className'),category:fd.get('category'),contribution:fd.get('contribution'),paymentStatus:fd.get('paymentStatus'),amount:Number(fd.get('amount')||0),charterSigned:fd.get('charterSigned'),sectionOption:fd.get('sectionOption')};if(!obj.fullName)return toast('Nom et prénom obligatoires.');if(l)Object.assign(l,obj);else{state.data.licenses.push(obj);state.data.students.push({id:obj.studentId,fullName:obj.fullName,className:obj.className,specialty:obj.sectionOption})}save();app.closeModal();render()})},
 licenseFilter(k,v){state.filters.licenses={...(state.filters.licenses||{}),[k]:v};render()},clearLicenseFilters(){state.filters.licenses={};render()},
 editEvent(id){const e=id?state.data.events.find(x=>x.id===id):null;const fields=f('title','Titre','text',e?.title||'',null,true)+f('ageCategory','Catégorie','select',e?.ageCategory||AGE_CATEGORIES[0],AGE_CATEGORIES)+f('specialty','Spécialité','select',e?.specialty||SPECIALTIES[0],SPECIALTIES)+f('date','Jour','date',e?.date||today())+f('startTime','Heure de départ','time',e?.startTime||'')+f('endTime','Heure de retour','time',e?.endTime||'')+f('place','Lieu de compétition','text',e?.place||'',null,true);modal(id?'Modifier un événement':'Ajouter un événement',modalForm(fields));setModalHandler(fd=>{const obj={id:e?.id||uid('e'),title:fd.get('title')?.trim(),ageCategory:fd.get('ageCategory'),specialty:fd.get('specialty'),date:fd.get('date'),startTime:fd.get('startTime'),endTime:fd.get('endTime'),place:fd.get('place')?.trim(),convocationId:e?.convocationId||null};if(e)Object.assign(e,obj);else state.data.events.push(obj);save();app.closeModal();render()})},
 editConv(id){const c=id?state.data.convocations.find(x=>x.id===id):null;const licensed=state.data.licenses;const checked=new Set(c?.studentIds||[]);const picker=`<div class="field full"><span>Élèves convoqués</span><div class="student-options">${licensed.map(l=>`<label class="student-option"><input type="checkbox" name="studentIds" value="${l.studentId}" ${checked.has(l.studentId)?'checked':''}><span><strong>${esc(l.fullName)}</strong><small>${esc(l.className)} · ${esc(l.category)}</small></span></label>`).join('')}</div></div>`;const fields=f('activity','Activité','select',c?.activity||ACTIVITIES[0],ACTIVITIES)+f('title','Titre','text',c?.title||'')+f('ageCategory','Catégorie','select',c?.ageCategory||AGE_CATEGORIES[0],AGE_CATEGORIES)+f('specialty','Spécialité','select',c?.specialty||SPECIALTIES[0],SPECIALTIES)+f('date','Date','date',c?.date||today())+f('place','Lieu','text',c?.place||'')+f('departure','Heure de départ','time',c?.departure||'')+f('returnTime','Heure de retour','time',c?.returnTime||'')+f('meetingPoint','Point de rendez-vous','text',c?.meetingPoint||'',null,true)+f('equipment','Matériel nécessaire','textarea',c?.equipment||'',null,true)+f('extraInfo','Informations complémentaires','textarea',c?.extraInfo||'',null,true)+picker;modal(id?'Modifier une convocation':'Ajouter une convocation',modalForm(fields),true);setModalHandler(fd=>{const obj={id:c?.id||uid('c'),activity:fd.get('activity'),title:fd.get('title')?.trim(),ageCategory:fd.get('ageCategory'),specialty:fd.get('specialty'),date:fd.get('date'),place:fd.get('place')?.trim(),departure:fd.get('departure'),returnTime:fd.get('returnTime'),meetingPoint:fd.get('meetingPoint')?.trim(),equipment:fd.get('equipment')?.trim(),extraInfo:fd.get('extraInfo')?.trim(),studentIds:fd.getAll('studentIds')};if(c)Object.assign(c,obj);else state.data.convocations.push(obj);const ev=state.data.events.find(e=>e.date===obj.date&&e.specialty===obj.specialty&&e.title===obj.title);if(ev)ev.convocationId=obj.id;save();app.closeModal();render()})},
 editReport(id){const r=id?state.data.reports.find(x=>x.id===id):null;const fields=f('date','Date','date',r?.date||today())+f('activity','Activité(s)','select',r?.activity||ACTIVITIES[0],ACTIVITIES)+f('teacher','Nom du professeur référent','text',r?.teacher||'',null,true)+f('level','Niveau de la compétition','select',r?.level||LEVELS[0],LEVELS)+f('place','Lieu de compétition','text',r?.place||'')+f('category','Catégorie','select',r?.category||AGE_CATEGORIES.at(-1),AGE_CATEGORIES)+f('participants',"Nombre d'élèves",'number',String(r?.participants||0))+f('comment','Commentaire','textarea',r?.comment||'',null,true);modal(id?'Modifier un bilan':'Ajouter un bilan',modalForm(fields));setModalHandler(fd=>{const obj={id:r?.id||uid('b'),date:fd.get('date'),activity:fd.get('activity'),teacher:fd.get('teacher')?.trim(),level:fd.get('level'),place:fd.get('place')?.trim(),category:fd.get('category'),participants:Number(fd.get('participants')||0),comment:fd.get('comment')?.trim()};if(r)Object.assign(r,obj);else state.data.reports.push(obj);save();app.closeModal();render()})},
 async validateApp(studentId,term){const ta=document.getElementById(`app-${studentId}`);const text=(ta?.value||'').trim();if(!text)return toast('Saisissez une appréciation.');toast('Vérification orthographe et grammaire…');try{const res=await checkFrench(text);const matches=(res.matches||[]).filter(m=>!['TYPOS','STYLE'].includes(m.rule?.issueType));if(matches.length){const corrected=applyCorrections(text,matches);modal('Correction proposée',`<p class="note">${matches.length} point(s) à vérifier avant validation.</p><div class="correction-compare"><div><strong>Texte saisi</strong><p>${esc(text)}</p></div><div><strong>Proposition</strong><p>${esc(corrected)}</p></div></div><div class="actions modal-actions"><button class="btn secondary" onclick="app.closeModal()">Reprendre</button><button class="btn" onclick="app.acceptAppCorrection('${studentId}',${term},'${encodeURIComponent(corrected).replace(/'/g,'%27')}')">Accepter et valider</button></div>`,true);return}app.saveApp(studentId,term,text,'validated');toast('Appréciation validée sans erreur détectée.')}catch(e){modal('Vérification indisponible',`<p>Le service de correction n’a pas répondu. Pour éviter de valider une appréciation sans contrôle, la validation est bloquée.</p><p class="note">Réessayez avec une connexion internet.</p>`)}},
 acceptAppCorrection(id,term,text){app.closeModal();app.saveApp(id,term,decodeURIComponent(text),'validated');toast('Correction appliquée et appréciation validée.')},saveApp(id,term,text,status){let a=getApp(id,term);if(!a){a={id:uid('a'),studentId:id,term,text,status};state.data.appreciations.push(a)}else Object.assign(a,{text,status});save();render()},copyApp(id,term){const a=getApp(id,term);if(!a?.text)return toast('Aucune appréciation à copier.');navigator.clipboard.writeText(a.text).then(()=>toast('Appréciation copiée.')).catch(()=>toast('Copie impossible.'))},
 editDocument(id){toast('Ajout de documents PDF : à relier au stockage Supabase lors de l’activation en ligne.')},editProduct(id){toast('Gestion des produits : disponible dans la prochaine étape Supabase.')},saveTermDates(){[1,2,3].forEach(n=>{state.data.termSettings[n]={deadline:document.getElementById(`td-${n}`)?.value||'',end:document.getElementById(`te-${n}`)?.value||''}});save();toast('Dates enregistrées.');render()}
};
window.app=app;
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
loadInstagram();
})();
