(() => {
'use strict';
const V=window.ASV7;if(!V||!window.app)return;
function clip(doc,text,width,max=2){return doc.splitTextToSize(String(text||''),width).slice(0,max)}
function relevantEvents(){const d=V.read();let list=(d.events||[]).slice(),sp=V.edu();if(sp)list=list.filter(e=>e.specialty===sp);return list.sort((a,b)=>(a.date+(a.startTime||'')).localeCompare(b.date+(b.startTime||'')))}
function drawHeader(doc,{title,subtitle='',rightTop='',rightBottom=''},logo){
 const W=297,navy=V.hex(V.NAVY),blue=V.hex(V.BLUE),yellow=V.hex(V.YELLOW);
 doc.setFillColor(...navy);doc.rect(0,0,W,45,'F');doc.setFillColor(...blue);doc.triangle(219,0,276,0,276,45,'F');doc.setFillColor(...yellow);doc.triangle(276,0,297,0,297,45,'F');
 doc.setFillColor(255,255,255);doc.roundedRect(10,5,34,34,6,6,'F');if(logo)try{doc.addImage(logo,'PNG',12,7,30,30)}catch{}
 doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.text('ASSOCIATION SPORTIVE DU BON SAUVEUR',51,11);doc.setFontSize(24);doc.text(title,51,26);if(subtitle){doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(subtitle,51,35)}
 doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(8);if(rightTop)doc.text(rightTop,281,12,{align:'right'});doc.setFontSize(10);if(rightBottom)doc.text(rightBottom,289,28,{align:'right'});
}
function drawFooter(doc,page=1){
 const W=297,H=210,navy=V.hex(V.NAVY),yellow=V.hex(V.YELLOW);doc.setFillColor(...navy);doc.rect(0,H-8,W,8,'F');doc.setFillColor(...yellow);doc.rect(0,H-8,67,8,'F');doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.text('BON SAUVEUR · SAINT-LÔ',10,H-3);doc.setTextColor(255,255,255);doc.setFont('helvetica','normal');doc.text(`PAGE ${page}`,286,H-3,{align:'right'});
}
async function calendarPDF(){
 if(!window.jspdf?.jsPDF)return alert('Le module PDF est encore en chargement.');const events=relevantEvents();if(!events.length)return alert('Aucun événement à exporter.');
 const d=V.read(),{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),logo=await V.logoData(),navy=V.hex(V.NAVY),blue=V.hex(V.BLUE),yellow=V.hex(V.YELLOW),light=V.hex(V.LIGHT),muted=V.hex(V.MUTED),sp=V.edu();
 for(let start=0,page=0;start<events.length;start+=6,page++){
  if(page)doc.addPage();doc.setFillColor(...light);doc.rect(0,0,297,210,'F');const chunk=events.slice(start,start+6);drawHeader(doc,{title:'CALENDRIER',subtitle:sp||'Association Sportive',rightTop:'SAINT-LÔ',rightBottom:`${V.fmtShort(chunk[0].date)} → ${V.fmtShort(chunk[chunk.length-1].date)}`},logo);
  chunk.forEach((e,j)=>{const col=j%3,row=Math.floor(j/3),x=11+col*94,y=56+row*66,w=86,h=55,accent=V.hex(V.SPEC_COLOR[e.specialty]||V.YELLOW);doc.setFillColor(255,255,255);doc.setDrawColor(220,227,238);doc.roundedRect(x,y,w,h,5,5,'FD');doc.setFillColor(...accent);doc.roundedRect(x,y,w,6,5,5,'F');doc.rect(x,y+3,w,3,'F');const dt=new Date(e.date+'T12:00:00');doc.setFillColor(...navy);doc.circle(x+14,y+20,9,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(String(dt.getDate()).padStart(2,'0'),x+9.7,y+19.5);doc.setFontSize(5.6);doc.text(dt.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase(),x+9,y+24);doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(10.5);doc.text(clip(doc,e.title,54,2),x+27,y+16);doc.setFont('helvetica','normal');doc.setTextColor(...muted);doc.setFontSize(7.2);doc.text(clip(doc,e.ageCategory||'Toutes catégories',53,1),x+27,y+31);doc.setFont('helvetica','bold');doc.setTextColor(...accent.map(v=>Math.max(0,v-40)));doc.text(clip(doc,e.specialty||'',53,1),x+27,y+38);doc.setFont('helvetica','normal');doc.setTextColor(...navy);doc.setFontSize(7.2);doc.text(`${e.startTime||'—'}${e.endTime?' → '+e.endTime:''}`,x+8,y+48);doc.setTextColor(...muted);doc.text(clip(doc,e.place||'',43,1),x+40,y+48);const conv=(d.convocations||[]).some(c=>c.id===e.convocationId||(c.date===e.date&&c.specialty===e.specialty&&c.title===e.title));if(conv){doc.setFillColor(...blue);doc.roundedRect(x+w-29,y+8,24,6,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(5.5);doc.text('CONVOCATION',x+w-26.4,y+12.1)}});
  drawFooter(doc,page+1);
 }
 doc.save(sp?`Calendrier_${V.clean(sp)}.pdf`:'Calendrier_AS_Bon_Sauveur.pdf');
}
function infoCard(doc,x,y,w,h,label,value,accent=false){
 const navy=V.hex(V.NAVY),blue=V.hex(V.BLUE),yellow=V.hex(V.YELLOW),muted=V.hex(V.MUTED);doc.setFillColor(255,255,255);doc.setDrawColor(222,228,239);doc.roundedRect(x,y,w,h,4,4,'FD');if(accent){doc.setFillColor(...yellow);doc.rect(x,y,3,h,'F')}doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.setTextColor(...(accent?blue:muted));doc.text(label.toUpperCase(),x+7,y+7);doc.setTextColor(...navy);doc.setFontSize(10.2);doc.text(clip(doc,value||'—',w-14,2),x+7,y+15);
}
function studentGrid(doc,names,yStart,max=8){
 const navy=V.hex(V.NAVY),blue=V.hex(V.BLUE),yellow=V.hex(V.YELLOW);doc.setFillColor(255,255,255);doc.setDrawColor(222,228,239);doc.roundedRect(12,yStart,273,45,5,5,'FD');doc.setFillColor(...yellow);doc.roundedRect(12,yStart,52,45,5,5,'F');doc.rect(58,yStart,6,45,'F');doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('ÉLÈVES',21,yStart+18);doc.text('CONVOQUÉS',21,yStart+25);names.slice(0,max).forEach((n,i)=>{const col=i%4,row=Math.floor(i/4),x=71+col*52,y=yStart+13+row*17;doc.setFillColor(...blue);doc.circle(x,y-2,2.2,'F');doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text(clip(doc,n,44,1),x+5,y)});
}
async function convocationPDF(id){
 if(!window.jspdf?.jsPDF)return alert('Le module PDF est encore en chargement.');const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return alert('Convocation introuvable.');
 const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),logo=await V.logoData(),navy=V.hex(V.NAVY),blue=V.hex(V.BLUE),yellow=V.hex(V.YELLOW),light=V.hex(V.LIGHT),accent=V.hex(V.SPEC_COLOR[c.specialty]||V.YELLOW),names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean);
 doc.setFillColor(...light);doc.rect(0,0,297,210,'F');drawHeader(doc,{title:'CONVOCATION',subtitle:c.specialty||'Association Sportive',rightTop:'SAINT-LÔ',rightBottom:V.fmtShort(c.date).toUpperCase()},logo);doc.setFillColor(...navy);doc.roundedRect(12,52,273,31,5,5,'F');doc.setFillColor(...accent);doc.rect(12,52,5,31,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text(clip(doc,c.title||c.activity||'Convocation',190,1),24,66);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(`${c.activity||''}  ·  ${c.ageCategory||''}`,24,76);doc.setFillColor(...yellow);doc.roundedRect(235,59,39,12,3,3,'F');doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(7);doc.text(clip(doc,c.specialty||'',33,2),254.5,64,{align:'center'});
 const dt=new Date(c.date+'T12:00:00');doc.setFillColor(255,255,255);doc.setDrawColor(222,228,239);doc.roundedRect(12,91,54,51,5,5,'FD');doc.setTextColor(...blue);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(dt.toLocaleDateString('fr-FR',{weekday:'long'}).toUpperCase(),20,103);doc.setFontSize(34);doc.text(String(dt.getDate()).padStart(2,'0'),20,124);doc.setFontSize(9);doc.setTextColor(...navy);doc.text(dt.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}).toUpperCase(),20,134);
 infoCard(doc,72,91,57,23,'Lieu',c.place);infoCard(doc,134,91,44,23,'Départ',c.departure);infoCard(doc,183,91,44,23,'Retour',c.returnTime);infoCard(doc,232,91,53,23,'Prof. référent',c.teacher);infoCard(doc,72,119,74,23,'Point de rendez-vous',c.meetingPoint);infoCard(doc,151,119,134,23,'Informations importantes',c.extraInfo,true);studentGrid(doc,names,151,8);drawFooter(doc,1);
 let rem=names.slice(8),page=2;while(rem.length){doc.addPage();doc.setFillColor(...light);doc.rect(0,0,297,210,'F');drawHeader(doc,{title:'CONVOCATION',subtitle:c.title||c.activity||'',rightTop:'ÉLÈVES CONVOQUÉS',rightBottom:V.fmtShort(c.date)},logo);doc.setTextColor(...navy);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('ÉLÈVES CONVOQUÉS',14,60);const list=rem.slice(0,24);list.forEach((n,i)=>{const col=i%3,row=Math.floor(i/3),x=14+col*92,y=72+row*15;doc.setFillColor(255,255,255);doc.setDrawColor(222,228,239);doc.roundedRect(x,y-7,84,11,3,3,'FD');doc.setFillColor(...blue);doc.circle(x+6,y-1.5,2,'F');doc.setTextColor(...navy);doc.setFontSize(8.5);doc.text(clip(doc,n,70,1),x+11,y)});drawFooter(doc,page++);rem=rem.slice(24)}
 doc.save(`Convocation_${V.clean(c.title||c.activity||c.date)}.pdf`);
}
function selectedFilters(){const out={};document.querySelectorAll('.filter-field,.filter-field-v7').forEach(f=>{const k=V.norm(f.querySelector('span')?.textContent||''),v=f.querySelector('select')?.value||'';if(k)out[k]=v});return out}
function filteredLicenses(d){const f=selectedFilters();return(d.licenses||[]).filter(l=>(!f.categorie||l.category===f.categorie)&&(!f.specialite||l.sectionOption===f.specialite)&&(!f.classe||l.className===f.classe)&&(!f.paiement||l.paymentStatus===f.paiement)&&(!f.mode||l.contribution===f.mode))}
function exportInfo(kind){
 const d=V.read(),sp=V.edu();
 if(kind==='licenses')return{title:'LICENCES',subtitle:'Base centrale des élèves licenciés',rows:filteredLicenses(d).map(l=>({'Nom & prénom':l.fullName,'Classe':l.className,'Catégorie':l.category,'Spécialité':l.sectionOption,'Cotisation':l.contribution||'','Statut paiement':l.paymentStatus,'Montant (€)':Number(l.amount||0),'Charte signée':l.charterSigned}))};
 if(kind==='reports')return{title:'BILANS AS',subtitle:'Suivi des séances, compétitions et réunions',rows:(d.reports||[]).map(r=>({'Date':r.date,'Activité':r.activity,'Enseignant(s) référent(s)':r.teacher||'','Niveau':r.level||'','Lieu':r.place||'','Catégorie':r.category||'',"Nombre d'élèves":Number(r.participants||0),'Commentaire':r.comment||''}))};
 if(kind==='orders'){const p=Object.fromEntries((d.products||[]).map(x=>[x.id,x.name]));return{title:'COMMANDES BOUTIQUE',subtitle:'Suivi des paiements et de la distribution',rows:(d.orders||[]).map(o=>({'Élève':o.studentName,'Classe':o.className,'Produit':p[o.productId]||'Produit','Couleur':o.color||'','Taille':o.size,'Quantité':Number(o.quantity||1),'Paiement':o.paymentMethod,'Payé':o.paid?'Oui':'Non','Distribué':o.distributed?'Oui':'Non','Date':o.createdAt}))}}
 if(kind==='convocations'){const rows=[];(d.convocations||[]).filter(c=>!sp||c.specialty===sp).forEach(c=>(c.studentIds||[]).forEach(id=>rows.push({'Activité':c.activity||'','Titre':c.title,'Catégorie':c.ageCategory||'','Spécialité':c.specialty,'Date':c.date,'Lieu':c.place,'Départ':c.departure,'Retour':c.returnTime,'Point de rendez-vous':c.meetingPoint||'','Professeur référent':c.teacher||'','Informations importantes':c.extraInfo||'','Élève':V.studentName(d,id)})));return{title:'CONVOCATIONS',subtitle:'Élèves convoqués et informations pratiques',rows}}
 if(kind==='appreciations'){const allowed=new Set((d.licenses||[]).filter(l=>!sp||l.sectionOption===sp).map(l=>l.studentId));return{title:'APPRÉCIATIONS',subtitle:sp||'Suivi annuel des appréciations',rows:(d.appreciations||[]).filter(a=>!sp||allowed.has(a.studentId)).map(a=>{const s=(d.students||[]).find(x=>x.id===a.studentId)||(d.licenses||[]).find(x=>x.studentId===a.studentId)||{};return{'Élève':s.fullName||'','Classe':s.className||'','Trimestre':a.term,'Appréciation':a.text||'','Statut':a.status==='validated'?'Validé':'À faire'}})}}
 if(kind==='calendar')return{title:'CALENDRIER',subtitle:sp||'Association Sportive du Bon Sauveur',rows:relevantEvents().map(e=>({'Date':e.date,'Titre':e.title,'Catégorie':e.ageCategory,'Spécialité':e.specialty,'Départ':e.startTime,'Retour':e.endTime,'Lieu':e.place}))};return{title:'EXPORT AS',subtitle:'Association Sportive du Bon Sauveur',rows:[]}
}
const argb=h=>'FF'+h.replace('#','').toUpperCase();
function styleTable(ws,start,end,count){const hr=ws.getRow(start);hr.height=25;for(let c=1;c<=count;c++){const x=hr.getCell(c);x.fill={type:'pattern',pattern:'solid',fgColor:{argb:argb(V.BLUE)}};x.font={name:'Aptos Display',size:11,bold:true,color:{argb:'FFFFFFFF'}};x.alignment={vertical:'middle',horizontal:'center',wrapText:true};x.border={bottom:{style:'medium',color:{argb:argb(V.YELLOW)}}}}for(let r=start+1;r<=end;r++){const row=ws.getRow(r);row.height=23;for(let c=1;c<=count;c++){const x=row.getCell(c);x.font={name:'Aptos',size:10,color:{argb:argb(V.NAVY)}};x.alignment={vertical:'middle',wrapText:true};x.fill={type:'pattern',pattern:'solid',fgColor:{argb:r%2===0?'FFF7FAFF':'FFFFFFFF'}};x.border={bottom:{style:'hair',color:{argb:'FFDCE4EF'}}}}}}
async function excel(kind){
 if(!window.ExcelJS)return alert('Le module Excel est encore en chargement.');const info=exportInfo(kind),rows=info.rows||[],wb=new ExcelJS.Workbook();wb.creator='Association Sportive du Bon Sauveur';wb.created=new Date();const ws=wb.addWorksheet(info.title.slice(0,31),{views:[{state:'frozen',ySplit:6}]});ws.properties.defaultRowHeight=20;ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,paperSize:9,margins:{left:.25,right:.25,top:.35,bottom:.35,header:.15,footer:.15}};const headers=rows.length?Object.keys(rows[0]):['Information'],count=Math.max(headers.length,6),last=ws.getColumn(count).letter,logo=await V.logoData();ws.mergeCells(`C1:${last}1`);ws.getCell('C1').value=info.title;ws.getCell('C1').font={name:'Aptos Display',size:24,bold:true,color:{argb:argb(V.BLUE)}};ws.mergeCells(`C2:${last}2`);ws.getCell('C2').value=info.subtitle;ws.getCell('C2').font={name:'Aptos',size:12,color:{argb:argb(V.MUTED)}};ws.mergeCells(`C3:${last}3`);ws.getCell('C3').value=`Association Sportive du Bon Sauveur · Saint-Lô · ${new Date().toLocaleDateString('fr-FR')}`;ws.getCell('C3').font={name:'Aptos',size:9,italic:true,color:{argb:'FF8592A6'}};ws.mergeCells(`A4:${last}4`);ws.getCell('A4').fill={type:'pattern',pattern:'solid',fgColor:{argb:argb(V.YELLOW)}};ws.getRow(4).height=6;if(logo)try{const id=wb.addImage({base64:logo,extension:'png'});ws.addImage(id,{tl:{col:.1,row:.15},ext:{width:76,height:76}})}catch{}const start=6;headers.forEach((h,i)=>ws.getCell(start,i+1).value=h);if(rows.length)rows.forEach((o,ri)=>headers.forEach((h,ci)=>ws.getCell(start+1+ri,ci+1).value=o[h]??''));else ws.getCell(start+1,1).value='Aucune donnée';const end=start+Math.max(rows.length,1);styleTable(ws,start,end,headers.length);ws.autoFilter={from:{row:start,column:1},to:{row:end,column:headers.length}};headers.forEach((h,i)=>{const vals=[h,...rows.map(r=>String(r[h]??''))],max=Math.min(45,Math.max(12,...vals.map(v=>Math.min(45,v.length+2))));ws.getColumn(i+1).width=max});
 if(kind==='licenses'){const fl=filteredLicenses(V.read()),sum=wb.addWorksheet('Synthèse comptable');sum.mergeCells('C1:F1');sum.getCell('C1').value='SYNTHÈSE COMPTABLE';sum.getCell('C1').font={name:'Aptos Display',size:22,bold:true,color:{argb:argb(V.BLUE)}};sum.mergeCells('C2:F2');sum.getCell('C2').value='Cotisations des licences';sum.getCell('C2').font={name:'Aptos',size:12,color:{argb:argb(V.MUTED)}};sum.mergeCells('A4:F4');sum.getCell('A4').fill={type:'pattern',pattern:'solid',fgColor:{argb:argb(V.YELLOW)}};sum.getRow(4).height=6;if(logo)try{const id=wb.addImage({base64:logo,extension:'png'});sum.addImage(id,{tl:{col:.1,row:.15},ext:{width:76,height:76}})}catch{}const vals=V.PAYMENTS.map(m=>({Mode:m,Total:fl.filter(l=>l.paymentStatus==='Payé'&&l.contribution===m).reduce((s,l)=>s+Number(l.amount||0),0)}));sum.getCell('A6').value='Mode de paiement';sum.getCell('B6').value='Total encaissé (€)';vals.forEach((x,i)=>{sum.getCell(7+i,1).value=x.Mode;sum.getCell(7+i,2).value=x.Total});sum.getCell('A12').value='TOTAL ENCAISSÉ';sum.getCell('B12').value=vals.reduce((s,x)=>s+x.Total,0);sum.getCell('A13').value='RESTANT À ENCAISSER';sum.getCell('B13').value=fl.filter(l=>l.paymentStatus!=='Payé').reduce((s,l)=>s+Number(l.amount||0),0);styleTable(sum,6,13,2);sum.getColumn(1).width=28;sum.getColumn(2).width=22}
 const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${V.clean(info.title)}_AS.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
app.exportCalendarPDF=calendarPDF;app.exportConvocation=convocationPDF;app.exportExcel=excel;
})();