(() => {
'use strict';
const V=window.ASV7;if(!V||!window.app)return;
function cat(raw){const n=V.norm(raw),m={benjamin:'Benjamin',benjamine:'Benjamine','minime fille':'Minime fille','minime garcon':'Minime garçon',lyceen:'Lycéen',lyceenne:'Lycéenne'};return m[n]||''}
function classe(raw){const n=V.norm(raw);if(!n)return'';const exact=V.CLASSES.find(c=>V.norm(c)===n);if(exact)return exact;const grade=(n.match(/^(6e|5e|4e|3e|seconde|premiere|terminale)/)||[])[1],last=n.split(' ').at(-1),cand=V.CLASSES.filter(c=>(!grade||V.norm(c).startsWith(grade))&&V.norm(c).split(' ').includes(last));return cand.length===1?cand[0]:''}
function val(row,aliases){const e=Object.entries(row).map(([k,v])=>[V.norm(k),v]);for(const a of aliases){const n=V.norm(a),h=e.find(([k])=>k===n);if(h&&String(h[1]).trim())return String(h[1]).trim()}return''}
async function parse(file){
 if(!window.XLSX)throw new Error('Le module Excel n’est pas chargé.');const ab=await file.arrayBuffer(),wb=XLSX.read(ab,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false}),seen=new Set(),rows=[];
 raw.forEach((r,idx)=>{let full=val(r,['Nom & prénom','Nom et prénom','Nom prénom','Élève','Eleve']);if(!full)full=[val(r,['Nom']),val(r,['Prénom','Prenom'])].filter(Boolean).join(' ').trim();const rc=val(r,['Classe']),rg=val(r,['Catégorie','Categorie']),cl=classe(rc),ca=cat(rg),key=V.norm(full)+'|'+V.norm(cl||rc),errors=[];if(!full)errors.push('Nom manquant');if(!cl)errors.push(`Classe inconnue : ${rc||'vide'}`);if(!ca)errors.push(`Catégorie inconnue : ${rg||'vide'}`);if(seen.has(key))errors.push('Doublon dans le fichier');seen.add(key);rows.push({line:idx+2,fullName:full,className:cl,category:ca,valid:!errors.length,errors})});return rows
}
function openImport(){
 if(!V.isAdmin())return;const m=V.modal('Importer des licenciés',`<div class="v7-import"><label class="field full"><span>Spécialité attribuée à tout le fichier</span><select id="v7-import-specialty">${V.options(V.SPECIALTIES,'Section Football',null)}</select></label><div id="v7-dropzone" class="v7-dropzone"><strong>Déposez votre fichier Excel ou CSV ici</strong><span>ou touchez pour choisir un fichier</span><small>.xlsx · .xls · .csv</small><input id="v7-import-file" type="file" accept=".xlsx,.xls,.csv,text/csv" hidden></div><div id="v7-import-preview"></div></div>`,true),zone=m.querySelector('#v7-dropzone'),input=m.querySelector('#v7-import-file');zone.onclick=()=>input.click();zone.ondragover=e=>{e.preventDefault();zone.classList.add('drag')};zone.ondragleave=()=>zone.classList.remove('drag');zone.ondrop=e=>{e.preventDefault();zone.classList.remove('drag');if(e.dataTransfer.files[0])preview(e.dataTransfer.files[0],m)};input.onchange=()=>input.files[0]&&preview(input.files[0],m)
}
async function preview(file,m){
 const box=m.querySelector('#v7-import-preview');box.innerHTML='<div class="v7-loading">Lecture du fichier…</div>';
 try{const rows=await parse(file),d=V.read();rows.forEach(r=>r.existing=r.valid&&(d.licenses||[]).find(l=>V.norm(l.fullName)===V.norm(r.fullName)&&V.norm(l.className)===V.norm(r.className))||null);window.__v7ImportRows=rows;const valid=rows.filter(r=>r.valid).length,dups=rows.filter(r=>r.existing).length,errors=rows.length-valid;box.innerHTML=`<div class="v7-import-summary"><strong>${V.esc(file.name)}</strong><span>${valid} ligne(s) prête(s) · ${dups} déjà présente(s) · ${errors} erreur(s)</span></div><div class="v7-import-table"><table><thead><tr><th>Ligne</th><th>Nom & prénom</th><th>Classe</th><th>Catégorie</th><th>État</th></tr></thead><tbody>${rows.slice(0,80).map(r=>`<tr class="${r.valid?'':'bad'}"><td>${r.line}</td><td>${V.esc(r.fullName||'—')}</td><td>${V.esc(r.className||'—')}</td><td>${V.esc(r.category||'—')}</td><td>${r.valid?(r.existing?'Déjà présent':'Prêt'):V.esc(r.errors.join(' · '))}</td></tr>`).join('')}</tbody></table></div><div class="v7-import-controls"><label class="field"><span>Si l’élève existe déjà</span><select id="v7-dup-mode"><option value="update">Mettre à jour classe / catégorie / spécialité</option><option value="skip">Ignorer le doublon</option></select></label><button class="btn" id="v7-import-confirm" ${valid?'':'disabled'}>Importer ${valid} élève(s)</button></div>`;box.querySelector('#v7-import-confirm')?.addEventListener('click',()=>commit(m))}
 catch(e){box.innerHTML=`<div class="note">${V.esc(e.message||'Impossible de lire ce fichier.')}</div>`}
}
function commit(m){
 if(!V.isAdmin())return;const rows=(window.__v7ImportRows||[]).filter(r=>r.valid),sp=m.querySelector('#v7-import-specialty').value,mode=m.querySelector('#v7-dup-mode')?.value||'update',d=V.read();d.licenses=d.licenses||[];d.students=d.students||[];let added=0,updated=0,skipped=0;
 rows.forEach(r=>{const existing=d.licenses.find(l=>V.norm(l.fullName)===V.norm(r.fullName)&&V.norm(l.className)===V.norm(r.className));if(existing){if(mode==='skip'){skipped++;return}existing.className=r.className;existing.category=r.category;existing.sectionOption=sp;const st=d.students.find(s=>s.id===existing.studentId);if(st)Object.assign(st,{fullName:r.fullName,className:r.className,specialty:sp});updated++;return}const es=d.students.find(s=>V.norm(s.fullName)===V.norm(r.fullName)&&V.norm(s.className)===V.norm(r.className)),studentId=es?.id||V.uid('s');d.licenses.push({id:V.uid('l'),studentId,fullName:r.fullName,className:r.className,category:r.category,contribution:'',paymentStatus:'En attente',amount:20,charterSigned:'Non',sectionOption:sp});es?Object.assign(es,{fullName:r.fullName,className:r.className,specialty:sp}):d.students.push({id:studentId,fullName:r.fullName,className:r.className,specialty:sp});added++});
 V.write(d);alert(`${added} élève(s) ajouté(s) · ${updated} mis à jour · ${skipped} ignoré(s).`);location.reload()
}
async function template(){
 if(!V.isAdmin())return;if(!window.ExcelJS)return alert('Le module Excel est encore en chargement.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Import'),logo=await V.logoData();ws.mergeCells('C1:F1');ws.getCell('C1').value='IMPORT LICENCIÉS';ws.getCell('C1').font={name:'Aptos Display',size:22,bold:true,color:{argb:'FF'+V.BLUE}};ws.mergeCells('C2:F2');ws.getCell('C2').value='Complétez les trois colonnes puis importez ce fichier dans l’application.';ws.getCell('C2').font={name:'Aptos',size:11,color:{argb:'FF'+V.MUTED}};ws.mergeCells('A4:F4');ws.getCell('A4').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+V.YELLOW}};ws.getRow(4).height=6;if(logo)try{const id=wb.addImage({base64:logo,extension:'png'});ws.addImage(id,{tl:{col:.1,row:.1},ext:{width:70,height:70}})}catch{};['Nom & prénom','Classe','Catégorie'].forEach((h,i)=>{const c=ws.getCell(6,i+1);c.value=h;c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+V.BLUE}};c.font={name:'Aptos',size:11,bold:true,color:{argb:'FFFFFFFF'}};c.alignment={horizontal:'center'}});ws.getCell('A7').value='MARTIN Léo';ws.getCell('B7').value='5e Jacqueline AURIOL';ws.getCell('C7').value='Benjamin';ws.getColumn(1).width=30;ws.getColumn(2).width=30;ws.getColumn(3).width=22;ws.views=[{state:'frozen',ySplit:6}];for(let r=7;r<=200;r++)ws.getCell(r,3).dataValidation={type:'list',allowBlank:false,formulae:[`"${V.LICENSE_CATEGORIES.join(',')}"`]};const h=wb.addWorksheet('Aide');h.getCell('A1').value='CATÉGORIES AUTORISÉES';h.getCell('A1').font={bold:true,color:{argb:'FF'+V.BLUE}};V.LICENSE_CATEGORIES.forEach((x,i)=>h.getCell(i+2,1).value=x);h.getCell('C1').value='CLASSES AUTORISÉES';h.getCell('C1').font={bold:true,color:{argb:'FF'+V.BLUE}};V.CLASSES.forEach((x,i)=>h.getCell(i+2,3).value=x);h.getColumn(1).width=24;h.getColumn(3).width=34;const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Modele_Import_Licencies_AS.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
app.openLicenseImport=openImport;app.downloadLicenseTemplate=template;
})();