(()=>{'use strict';const V=window.ASV7;if(!V||!window.app)return;const C={navy:'#10213f',blue:'#0757c9',yellow:'#ffd21a',ink:'#13213a',muted:'#68768d',light:'#f3f6fa',line:'#dbe4ef',white:'#fff'};const accent=s=>s==='Section Football'?'#2582e9':s==='Option Escalade'?'#7057d9':s==='Sport-études Gymnastique'?'#9859ce':'#d5ae00';const esc=V.esc;
function textWrap(t,n=28){const a=String(t||'').split(/\s+/),o=[];let l='';for(const w of a){const q=(l+' '+w).trim();if(q.length>n&&l){o.push(l);l=w}else l=q}if(l)o.push(l);return o}
function tx(t,x,y,size=5,weight=700,color=C.ink,anchor='start'){return `<text x="${x}" y="${y}" font-family="Arial,Helvetica,sans-serif" font-size="${size}" font-weight="${weight}" fill="${color}" text-anchor="${anchor}">${esc(t)}</text>`}
function multiline(t,x,y,n,size=5,weight=700,color=C.ink,lh=6){return textWrap(t,n).slice(0,3).map((l,i)=>tx(l,x,y+i*lh,size,weight,color)).join('')}
function frame(title,sub){return `<rect width="297" height="210" fill="#fff"/><rect x="0" y="0" width="297" height="36" fill="${C.navy}"/><rect x="0" y="36" width="297" height="3" fill="${C.yellow}"/><rect x="12" y="9" width="20" height="20" rx="5" fill="#fff"/>${tx('ASSOCIATION SPORTIVE DU BON SAUVEUR',40,12,3.2,800,'#b9c8df')}${tx(title,40,25,11,900,'#fff')}${tx(sub,286,23,4.2,800,C.yellow,'end')}<rect x="12" y="199" width="273" height="1" fill="${C.line}"/>${tx('BON SAUVEUR · SAINT-LÔ',12,205,2.8,800,C.muted)}`}
async function makePdf(pages,name){const {jsPDF}=window.jspdf||{};if(!jsPDF)return alert('Export PDF indisponible.');const pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),logo=await V.logoData();for(let i=0;i<pages.length;i++){if(i)pdf.addPage('a4','landscape');const el=new DOMParser().parseFromString(pages[i],'image/svg+xml').documentElement;await pdf.svg(el,{x:0,y:0,width:297,height:210});if(logo)try{pdf.addImage(logo,'PNG',14,10,16,16)}catch{}tx;pdf.setFont('helvetica','bold');pdf.setFontSize(7);pdf.setTextColor(104,118,141);pdf.text(`${i+1}/${pages.length}`,285,205,{align:'right'})}pdf.save(name)}
function calCard(e,x,y,w,h){const a=accent(e.specialty),d=new Date(e.date+'T12:00:00'),day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').toUpperCase();return `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="5" fill="#fff" stroke="${C.line}"/><rect x="${x}" y="${y}" width="5" height="${h}" rx="2.5" fill="${a}"/><rect x="${x+10}" y="${y+10}" width="24" height="24" rx="6" fill="${C.navy}"/>${tx(day,x+22,y+23,9,900,'#fff','middle')}${tx(mon,x+22,y+29,2.8,900,C.yellow,'middle')}${multiline(e.title,x+41,y+15,28,5.5,900,C.ink,6)}${tx(e.specialty||'',x+41,y+32,3.1,800,a)}${tx(`${e.startTime||'—'}${e.endTime?'  →  '+e.endTime:''}`,x+10,y+h-15,4.1,900,C.ink)}${tx(e.place||'—',x+10,y+h-8,3.4,600,C.muted)}${tx(e.ageCategory||'Toutes catégories',x+w-8,y+h-8,3.2,700,C.muted,'end')}</g>`}
app.exportCalendarPDF=async()=>{const d=V.read(),sp=V.edu(),events=(d.events||[]).filter(e=>!sp||e.specialty===sp).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(!events.length)return alert('Aucun événement à exporter.');const chunks=[];for(let i=0;i<events.length;i+=6)chunks.push(events.slice(i,i+6));const pages=chunks.map(ch=>{let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 297 210">${frame('CALENDRIER AS',sp||'Association Sportive')}${tx('LES PROCHAINS RENDEZ-VOUS',12,51,3.2,900,C.blue)}`;ch.forEach((e,i)=>{const col=i%2,row=Math.floor(i/2);s+=calCard(e,12+col*138.5,58+row*44,132,38)});return s+'</svg>'});await makePdf(pages,'Calendrier_AS.pdf')};
function info(label,value,x,y,w){return `<rect x="${x}" y="${y}" width="${w}" height="24" rx="4" fill="${C.light}"/>${tx(label.toUpperCase(),x+6,y+8,2.7,900,C.muted)}${multiline(value||'—',x+6,y+17,Math.floor(w/2.2),4.6,900,C.ink,5)}`}
app.exportConvocation=async id=>{const d=V.read(),c=(d.convocations||[]).find(x=>x.id===id);if(!c)return;const names=(c.studentIds||[]).map(x=>V.studentName(d,x)).filter(Boolean),a=accent(c.specialty),date=V.fmtLong(c.date);let s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 297 210">${frame('CONVOCATION',c.specialty||'Association Sportive')}<rect x="12" y="48" width="273" height="31" rx="6" fill="${C.navy}"/><rect x="12" y="48" width="6" height="31" rx="3" fill="${a}"/>${tx((c.activity||'ACTIVITÉ').toUpperCase(),25,58,3,900,C.yellow)}${multiline(c.title||c.activity,25,70,46,8.5,900,'#fff',8)}${tx(c.ageCategory||'',277,69,3.5,800,'#c8d3e5','end')}${info('Date',date,12,87,65)}${info('Lieu',c.place,82,87,63)}${info('Départ',c.departure,150,87,42)}${info('Retour',c.returnTime,197,87,42)}${info('Professeur référent',c.teacher||'À renseigner',244,87,41)}${info('Point de rendez-vous',c.meetingPoint,12,117,92)}<rect x="109" y="117" width="176" height="24" rx="4" fill="#fff9dc" stroke="#f1d45c"/><rect x="109" y="117" width="4" height="24" rx="2" fill="${C.yellow}"/>${tx('INFORMATIONS IMPORTANTES',118,125,2.7,900,C.blue)}${multiline(c.extraInfo||'Aucune information particulière.',118,134,70,4.2,800,C.ink,5)}${tx('ÉLÈVES CONVOQUÉS',12,154,3.2,900,C.blue)}`;names.slice(0,16).forEach((n,i)=>{const col=i%4,row=Math.floor(i/4),x=12+col*68,y=161+row*8;s+=`<rect x="${x}" y="${y-5}" width="63" height="7" rx="3.5" fill="${C.light}"/>${tx(n,x+4,y,3.1,800,C.ink)}`});if(names.length>16)s+=tx(`+ ${names.length-16} autre(s) élève(s)`,12,194,3.2,800,C.muted);s+='</svg>';await makePdf([s],`Convocation_${V.clean(c.title||'AS')}.pdf`)};
})();